import {services,tasks,spaces} from './content.mjs';
import {createGame,gameAction,active,completed} from './engine.mjs';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='terms-apply-v1';let state=createGame(),selected='lamp',storage=true;
try{const saved=JSON.parse(localStorage.getItem(key));if(saved&&saved.version===1&&[1,2].includes(saved.mode)&&saved.players.length===saved.mode&&saved.taskState.length===tasks.length&&saved.taskState.every(t=>tasks.some(d=>d.id===t.id))&&['roll','act','finished'].includes(saved.phase))state=saved;}catch{}
const positions=[[5,5],[5,4],[5,3],[5,2],[5,1],[4,1],[3,1],[2,1],[1,1],[1,2],[1,3],[1,4],[1,5],[2,5],[3,5],[4,5]];
function send(action){state=gameAction(state,action);try{localStorage.setItem(key,JSON.stringify(state));}catch{storage=false;}render();}
const ready=()=>state.phase==='act';
function render(){
 const focused=document.activeElement?.dataset?.action;
 const p=active(state),ts=state.taskState.find(x=>x.id===selected),def=tasks.find(x=>x.id===selected);
 $('#goal').textContent=`Complete ${state.target} tasks and resolve every obligation before the end of round four.`;
 $('#status').innerHTML=`<div><span class="label">Round</span><br><strong>${state.round} / 4</strong></div>${state.players.map((x,i)=>`<div class="player ${i===state.current?'active':''}"><span class="label">${esc(x.name)}</span><br><strong>${x.time}</strong> time${x.bank?` <span class="small">+ ${x.bank} reserved</span>`:''}</div>`).join('')}<div><span class="label">Ready tasks</span><br><strong>${completed(state)} / ${state.target}</strong></div><div><span class="label">Open terms</span><br><strong>${state.pending.length}</strong></div>`;
 $('#board').innerHTML=spaces.map((s,i)=>{const color=services.find(v=>v.id===s.service)?.color||'';return `<div class="space ${s.kind==='service'?'service '+color:''} ${state.players.some(x=>x.position===i)?'occupied':''}" style="grid-row:${positions[i][0]};grid-column:${positions[i][1]}" aria-label="${esc(s.name)}${state.players.filter(x=>x.position===i).map(x=>', '+x.name).join('')}"><span class="number">${String(i+1).padStart(2,'0')}</span><strong>${esc(s.name)}</strong><div class="tokens">${state.players.map((x,j)=>x.position===i?`<span class="token ${j?'second':''}">${state.mode===1?'Y':j+1}</span>`:'').join('')}</div></div>`;}).join('')+`<div class="board-center"><span class="stamp">TERMS APPLY</span><h2>A little<br>convenience.</h2><p>What do you gain?<br>What do you still need to do?</p><span class="label">${state.mode===1?'Solo':'Two-player cooperative'} / four rounds</span>${state.phase==='finished'?`<div class="finish"><strong>${state.outcome==='complete'?'Ready to hand over.':'Some work remains.'}</strong><p>${completed(state)} completed tasks.<br>${state.pending.length} open obligations.</p><button data-action="restart">Play again</button></div>`:''}</div>`;
 $('#roll').disabled=state.phase!=='roll';$('#end').disabled=!ready();$('#die').textContent=state.roll?`You rolled ${state.roll}.`:'Roll to begin the turn.';
 $('#notice').textContent=state.notice;$('#log').innerHTML=state.log.map(x=>`<li>${esc(x)}</li>`).join('');
 $('#finished-count').textContent=`${completed(state)} ready`;
 $('#task-select').innerHTML=tasks.map(t=>`<option value="${t.id}" ${selected===t.id?'selected':''}>${state.taskState.find(x=>x.id===t.id).done?'✓ ':''}${esc(t.title)}</option>`).join('');
 const canSubmit=ready()&&!ts.done&&ts.work>=def.work&&ts.read.length===2&&!state.pending.some(x=>x.task===ts.id);
 $('#task').innerHTML=`<h3 class="task-title">${esc(def.title)}</h3><p>${esc(def.question)}</p><div class="claim"><span class="label">The proposed answer</span>${esc(def.claim)}</div><div class="progress" aria-label="${ts.work} of ${def.work} work marks">${Array.from({length:def.work},(_,i)=>`<span class="mark ${i<ts.work?'filled':''}"></span>`).join('')}</div><p class="small">${ts.work} / ${def.work} work marks. ${ts.read.length} / 2 sources inspected.</p>${ts.done?`<p class="notice">Ready. ${esc(def.resolution)}</p>`:`<button data-action="work" ${!ready()||!p.time||ts.work>=def.work?'disabled':''}>Work on this task <span class="small">/ 1 time</span></button>`}<div class="sources">${def.sources.map((source,i)=>`<details class="source"><summary>${esc(source[0])}<span class="small">${ts.read.includes(i)?'Inspected':'Open source'}</span></summary><p>${esc(source[1])}</p>${!ts.read.includes(i)&&!ts.done?`<button data-action="source" data-index="${i}" ${!ready()||(!p.time&&!state.freeSource)?'disabled':''}>Mark inspected / ${state.freeSource?'free source pass':'1 time'}</button>`:''}</details>`).join('')}</div>${ts.done?'':`<span class="label">Your conclusion</span><div class="verdict">${[['accept','Accept'],['revise','Revise'],['unknown','Not enough information']].map(([v,l])=>`<button data-action="submit" data-verdict="${v}" ${!canSubmit?'disabled':''}>${l}</button>`).join('')}</div><p class="small">Finish the work, inspect both sources, and close this task’s obligations before handing it over. Conclusions cost no time.</p>`}`;
 $('#term-count').textContent=`(${state.pending.length})`;$('#pending').innerHTML=state.pending.length?state.pending.map(t=>`<div class="term"><span>${esc(services.find(x=>x.id===t.service).name)}<br><span class="small">${t.task?esc(tasks.find(x=>x.id===t.task).title):'Saved return point'}</span></span><button data-action="resolve-open" data-id="${t.id}" ${!ready()?'disabled':''}>Inspect</button></div>`).join(''):'<p class="small">No open obligations. Used services add their terms here.</p>';
 $('#services').innerHTML=services.map(s=>{const owned=state.owned.includes(s.id),used=state.used.includes(s.id),cost=spaces[p.position].service===s.id?1:2;return `<article class="service-row"><div><h3>${esc(s.name)}</h3><span class="label">${owned?'Shared by the team':'Available'}</span></div><p>${esc(s.benefit)}</p><p class="term-copy small">${esc(s.term)}</p><div class="actions">${!owned?`<button data-action="buy" data-service="${s.id}" ${!ready()||p.time<cost?'disabled':''}>Acquire / ${cost} time</button>`:s.id==='memory'?'<span class="small">Automatic on interruptions</span>':`<button data-action="use-open" data-service="${s.id}" ${!ready()||used||(s.id==='schedule'&&(p.time<2||state.round===4))||(['writing','recommend'].includes(s.id)&&(!p.time||ts.done||ts.work>=def.work))?'disabled':''}>${used?'Used this turn':esc(s.action)}</button>`}</div></article>`;}).join('');
 if(!storage)$('#save-status').textContent='Browser storage is unavailable. Keep this tab open or save the game record.';
 if(focused)document.querySelector(`[data-action="${focused}"]:not(:disabled)`)?.focus({preventScroll:true});
}
const dialog=$('#dialog');function show(html){$('#dialog-content').innerHTML=html;dialog.showModal();}$('#close-dialog').onclick=()=>dialog.close();
function newGame(){show('<h2>Begin again</h2><p>Starting a new game replaces the current game saved in this browser.</p><label for="mode">Players</label><select id="mode"><option value="1">Solo: 3 tasks, 6 time each turn</option><option value="2">Two players: 4 tasks, 4 time each turn</option></select><button id="confirm-new" class="primary">Start new game</button>');$('#confirm-new').onclick=()=>{state=createGame(Number($('#mode').value));selected='lamp';try{localStorage.setItem(key,JSON.stringify(state));}catch{storage=false;}dialog.close();render();};}
$('#new').onclick=newGame;$('#rules').onclick=()=>show(`<h2>How to play</h2><ol><li>Complete ${state.target} shared tasks in four rounds. All open service obligations must be resolved.</li><li>Roll once, then spend time on any task or service. Passing Begin again returns 1 time; a new round is governed by turns, not laps.</li><li>Work costs 1 time per mark. Inspecting each source costs 1 time. Source and review spaces grant a free pass for the current turn.</li><li>Acquire services for the team. Buying costs 1 time when you land on that service, or 2 through the market.</li><li>Use a service at most once per turn. Read its benefit and obligation. Writing and recommendation add work but create a later check.</li><li>After enough work and both sources, choose Accept, Revise, or Not enough information. Use the supplied evidence; a wrong conclusion costs no time.</li><li>End the turn when ready. Unused time expires unless reserved. Tasks, sources, ownership, and obligations carry forward. In two-player mode, players alternate.</li></ol><p class="small">No property rent, player elimination, or live AI. Services and scenarios are fictional. This is an untested game prototype.</p><p><a href="rules.md">Read the complete rulebook</a></p>`);
$('#task-select').onchange=e=>{selected=e.target.value;render();};$('#roll').onclick=()=>{const v=new Uint32Array(1);crypto.getRandomValues(v);send({type:'roll',value:1+v[0]%6});};
$('#end').onclick=()=>{if(active(state).time){show(`<h2>End this turn?</h2><p>${active(state).time} unused time will expire. Open obligations carry forward.</p><button id="confirm-end" class="primary">End turn</button>`);$('#confirm-end').onclick=()=>{dialog.close();send({type:'end'});};}else send({type:'end'});};
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;
 if(a==='restart'){newGame();return;}
 if(['work','source','submit','buy'].includes(a)){send({type:a,task:selected,index:Number(b.dataset.index),verdict:b.dataset.verdict,service:b.dataset.service});return;}
 if(a==='resolve-open'){
  const term=state.pending.find(x=>x.id===b.dataset.id),d=tasks.find(x=>x.id===term.task);let copy='';
  if(term.service==='writing')copy=`<p>Check this generated claim against the task’s supplied sources.</p><div class="evidence"><strong>${esc(d.claim)}</strong>${d.sources.map(x=>`<p>${esc(x[0])}: ${esc(x[1])}</p>`).join('')}</div>`;
  if(term.service==='recommend')copy='<p>The recommended task route uses the supplied sources. A wider fictional route also adds an archive recipient. No extra progress is gained from sharing more.</p><label for="scope">Choose a scope</label><select id="scope"><option value="task-only">Task-only: supplied sources</option><option value="wider">Wider: sources plus fictional archive</option></select>';
  if(term.service==='memory')copy=`<p>Saved return point: ${(term.snapshot||[]).map(x=>`${esc(tasks.find(t=>t.id===x.id).title)} (${x.work} work marks, ${x.read.length} inspected sources)`).join('; ')||'No task work had started when the interruption occurred'}.</p><p>Check this against the workbench before resuming. The note records the moment of interruption.</p>`;
  show(`<h2>${esc(services.find(x=>x.id===term.service).name)}: the term</h2>${copy}<p class="small">${term.service==='memory'?'No time cost':state.freeReview?'Free review pass available':'Resolving costs 1 time'}</p><label><input type="checkbox" id="ack"> I inspected this obligation</label><button id="resolve" class="primary" ${term.service!=='memory'&&!active(state).time&&!state.freeReview?'disabled':''}>Resolve obligation</button>`);
  $('#resolve').onclick=()=>{if(!$('#ack').checked){$('#ack').focus();return;}const choice=$('#scope')?.value;dialog.close();send({type:'resolve',id:term.id,acknowledged:true,choice});};return;
 }
 if(a==='use-open'){
  const id=b.dataset.service;
  if(id==='companion'){show('<h2>A little reassurance</h2><p>“You have a next step. Take it one action at a time.”</p><p>This is the same authored message for every player. It is not an assessment of how you feel.</p><label><input type="checkbox" id="ack"> I read how this message was produced</label><button id="use-companion" class="primary">Use the reassurance / +1 time</button>');$('#use-companion').onclick=()=>{if(!$('#ack').checked){$('#ack').focus();return;}dialog.close();send({type:'use',service:id,acknowledged:true});};}
  else send({type:'use',service:id,task:selected});
 }
});
$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='terms-apply-game-record.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
render();
