import test from 'node:test';import assert from 'node:assert/strict';
import {createGame,gameAction,active,completed} from './engine.mjs';import {tasks} from './content.mjs';
const act=(s,a)=>gameAction(s,a);
test('actions require a roll and do not mutate the previous state',()=>{const s=createGame();const n=act(s,{type:'work',task:'lamp'});assert.equal(n.taskState[0].work,0);assert.equal(s.taskState[0].work,0);const r=act(s,{type:'roll',value:1});assert.equal(r.phase,'act');assert.equal(s.phase,'roll');assert.equal(act(r,{type:'roll',value:2}).players[0].position,1);});
test('sources, evidence verdict, and service terms gate task completion',()=>{let s=act(createGame(),{type:'roll',value:3});s=act(s,{type:'buy',service:'writing'});assert.equal(s.owned[0],'writing');s=act(s,{type:'use',service:'writing',task:'lamp'});assert.equal(s.taskState[0].work,3);assert.equal(s.pending.length,1);assert.equal(act(s,{type:'use',service:'writing',task:'lamp'}).taskState[0].work,3);s.players[0].time=10;s=act(s,{type:'work',task:'lamp'});s=act(s,{type:'work',task:'lamp'});for(let i=0;i<2;i++)s=act(s,{type:'source',task:'lamp',index:i});assert.equal(act(s,{type:'submit',task:'lamp',verdict:'revise'}).taskState[0].done,false);s=act(s,{type:'resolve',id:s.pending[0].id,acknowledged:true});assert.equal(act(s,{type:'submit',task:'lamp',verdict:'accept'}).taskState[0].done,false);s=act(s,{type:'submit',task:'lamp',verdict:'revise'});assert.equal(s.taskState[0].done,true);});
test('schedule reserves time; memory protects an interruption and creates a free acknowledgement',()=>{let s=createGame();s.phase='act';s.owned=['schedule','memory'];s=act(s,{type:'use',service:'schedule'});assert.equal(active(s).time,4);assert.equal(active(s).bank,2);s=act(s,{type:'end'});assert.equal(active(s).time,8);s.players[0].position=3;s=act(s,{type:'roll',value:1});assert.equal(active(s).time,8);assert.equal(s.pending[0].service,'memory');s=act(s,{type:'resolve',id:s.pending[0].id,acknowledged:true});assert.equal(active(s).time,8);assert.equal(s.pending.length,0);s.round=4;assert.equal(act(s,{type:'use',service:'schedule'}).players[0].bank,0);});
test('routing needs a scope and reassurance needs provenance acknowledgement',()=>{let s=createGame();s.phase='act';s.owned=['recommend','companion'];s=act(s,{type:'use',service:'recommend',task:'lamp'});assert.equal(act(s,{type:'resolve',id:s.pending[0].id,acknowledged:true}).pending.length,1);s=act(s,{type:'resolve',id:s.pending[0].id,acknowledged:true,choice:'task-only'});assert.equal(s.pending.length,0);const before=active(s).time;assert.equal(active(act(s,{type:'use',service:'companion'})).time,before);s=act(s,{type:'use',service:'companion',acknowledged:true});assert.equal(active(s).time,before+1);assert.equal(active(act(s,{type:'use',service:'companion',acknowledged:true})).time,before+1);});
function finishWithoutServices(mode){let s=createGame(mode);let guard=0;while(s.phase!=='finished'&&guard++<200){if(s.phase==='roll')s=act(s,{type:'roll',value:1});const t=s.taskState.find(x=>!x.done),d=tasks.find(x=>x.id===t?.id);if(!t){s=act(s,{type:'end'});continue;}if(t.work===d.work&&t.read.length===2){s=act(s,{type:'submit',task:t.id,verdict:d.answer});continue;}if(active(s).time===0&&!s.freeSource){s=act(s,{type:'end'});continue;}if(t.read.length<2&&s.freeSource){s=act(s,{type:'source',task:t.id,index:[0,1].find(x=>!t.read.includes(x))});continue;}if(t.work<d.work&&active(s).time){s=act(s,{type:'work',task:t.id});continue;}s=act(s,{type:'source',task:t.id,index:[0,1].find(x=>!t.read.includes(x))});}return s;}
test('complete solo and cooperative paths reach a real end condition',()=>{for(const mode of[1,2]){const s=finishWithoutServices(mode);assert.equal(s.phase,'finished');assert.equal(s.outcome,'complete');assert.ok(completed(s)>=s.target);assert.equal(s.round,4);assert.equal(s.pending.length,0);}});
test('not enough information is a valid supported task outcome',()=>{let s=createGame();s.phase='act';s.players[0].time=10;for(let i=0;i<4;i++)s=act(s,{type:'work',task:'booking'});for(let i=0;i<2;i++)s=act(s,{type:'source',task:'booking',index:i});s=act(s,{type:'submit',task:'booking',verdict:'unknown'});assert.equal(s.taskState.find(t=>t.id==='booking').done,true);});
test('memory records the interruption moment rather than a changing live task',()=>{let s=createGame();s.owned=['memory'];s.players[0].position=3;s.taskState[0].work=1;s=act(s,{type:'roll',value:1});assert.equal(s.pending[0].snapshot[0].work,1);s=act(s,{type:'work',task:'lamp'});assert.equal(s.taskState[0].work,2);assert.equal(s.pending[0].snapshot[0].work,1);});
test('deadline loses with incomplete work, cannot spend negative time, and terminal actions are locked',()=>{let s=createGame();s.phase='act';s.players[0].time=0;assert.equal(act(s,{type:'work',task:'lamp'}).taskState[0].work,0);for(let i=0;i<4;i++){if(s.phase==='roll')s=act(s,{type:'roll',value:1});s=act(s,{type:'end'});}assert.equal(s.phase,'finished');assert.equal(s.outcome,'unfinished');assert.equal(act(s,{type:'roll',value:1}).phase,'finished');});
