import {test} from 'node:test';import assert from 'node:assert/strict';
import {startMatch,legalActions,applyMove,botMove,observation,result,demoRoster,spaces,rent,netWorth,MAX_TURNS} from './game.mjs';
import {parseReply,modelMove,catalog} from './provider.mjs';
const table=()=>startMatch(demoRoster.slice(0,2),1,42);
function land(m,index){const peek=applyMove(m,{type:'roll'}),sum=peek.dice.reduce((a,b)=>a+b,0);m.players[0].position=(index-sum+spaces.length)%spaces.length;return applyMove(m,{type:'roll'});}
test('five players finish a finite shared game and the richest players win',()=>{let m=startMatch(demoRoster,1,42);const initial=structuredClone(m);for(let i=0;i<1800&&!m.finishedAt;i++){const p=m.players[m.current],move=botMove(m,p);assert.ok(legalActions(m).some(a=>JSON.stringify(a)===JSON.stringify(move.action)));m=applyMove(m,move.action,move.reason);}assert.ok(m.finishedAt);assert.ok(m.players.every(p=>p.bankrupt||p.turns===MAX_TURNS));assert.ok(m.players.every(p=>p.cash>=0));assert.equal(m.players.reduce((n,p)=>n+p.rejected,0),0);assert.ok(result(m).winners.length);assert.equal(result(m).rows[0].netWorth,Math.max(...m.players.map(p=>netWorth(m,p))));assert.equal(initial.properties.filter(p=>p.owner).length,0);});
test('buying transfers cash to the bank and shared ownership prevents another purchase',()=>{let m=table();m.phase='act';m.players[0].position=1;const before=structuredClone(m);m=applyMove(m,{type:'buy',space:1});assert.equal(m.players[0].cash,1080);assert.equal(m.properties[1].owner,demoRoster[0].id);assert.equal(before.properties[1].owner,null);assert.ok(!legalActions(m).some(a=>a.type==='buy'));});
test('rent transfers cash to the owner and color sets and houses increase it',()=>{let m=table();m.properties[1].owner=demoRoster[1].id;m.properties[2].owner=demoRoster[1].id;m.properties[1].houses=1;assert.equal(rent(m,1),120);const before=m.players[1].cash;m=land(m,1);assert.equal(m.players[1].cash,before+120);assert.match(m.events.at(-1).outcome,/Paid \$120 rent/);});
test('passing Start pays $200 exactly once',()=>{let m=table();m.players[0].position=19;const before=m.players[0].cash;m=applyMove(m,{type:'roll'});const outcome=m.events.at(-1).outcome;assert.match(outcome,/collected \$200/);assert.ok(m.players[0].cash>=before+110);});
test('houses need a complete set, cost cash and are capped at three',()=>{let m=table();m.phase='act';m.properties[1].owner=demoRoster[0].id;assert.ok(!legalActions(m).some(a=>a.type==='build'));m.properties[2].owner=demoRoster[0].id;for(let i=0;i<3;i++)m=applyMove(m,{type:'build',space:1});assert.equal(m.properties[1].houses,3);assert.equal(m.players[0].cash,900);assert.ok(!legalActions(m).some(a=>a.type==='build'&&a.space===1));});
test('selling clears houses and returns half of property and house costs',()=>{let m=table();m.phase='act';m.properties[1]={owner:demoRoster[0].id,houses:2};m=applyMove(m,{type:'sell',space:1});assert.equal(m.players[0].cash,1360);assert.deepEqual(m.properties[1],{owner:null,houses:0});});
test('timeout moves to visiting corner and skips exactly one turn',()=>{let m=land(table(),15);assert.equal(m.players[0].position,5);assert.equal(m.players[0].jail,1);m=applyMove(m,{type:'end'});m=applyMove(m,{type:'roll'});m=applyMove(m,{type:'end'});assert.equal(m.current,0);m=applyMove(m,{type:'roll'});assert.equal(m.players[0].jail,0);assert.equal(m.players[0].position,5);assert.equal(m.current,1);assert.equal(m.players[0].turns,2);});
test('unpayable rent causes bankruptcy and early victory without negative cash',()=>{let m=table();m.properties[18]={owner:demoRoster[1].id,houses:3};m.properties[19]={owner:demoRoster[1].id,houses:3};m.players[0].cash=1;m=land(m,19);assert.equal(m.players[0].cash,0);assert.equal(m.players[0].bankrupt,true);assert.ok(m.finishedAt);assert.deepEqual(result(m).winners,[demoRoster[1].id]);});
test('illegal moves cannot buy remotely or stall a game indefinitely',()=>{let m=table();const before=m.players[0].cash;m=applyMove(m,{type:'buy',space:1});assert.equal(m.properties[1].owner,null);assert.equal(m.players[0].cash,before);assert.equal(m.current,1);assert.equal(m.players[0].rejected,1);for(let i=0;i<50&&!m.finishedAt;i++)m=applyMove(m,{type:'invalid'});assert.ok(m.finishedAt);});
test('model observation describes shared ownership but hides future dice and cards',()=>{const m=table(),obs=observation(m,m.players[0]);assert.equal(obs.board.length,20);assert.equal(obs.you.cash,1200);assert.equal('rng' in obs,false);assert.deepEqual(obs.legalActions,[{type:'roll'}]);});
test('OpenRouter request uses selected identity, legal observation and server credential',async()=>{let captured;const r=await modelMove({id:'provider/model'},{legalActions:[{type:'roll'}]},'test-key',async(url,opts)=>{captured={url,opts};return {ok:true,json:async()=>({model:'provider/model',choices:[{message:{content:'{"action":{"type":"roll"},"reason":"Start."}'}}],usage:{cost:.001}})};});assert.equal(captured.url,'https://openrouter.ai/api/v1/chat/completions');assert.equal(captured.opts.headers.Authorization,'Bearer test-key');assert.equal(JSON.parse(captured.opts.body).provider.allow_fallbacks,false);assert.equal(parseReply(r.text).action.type,'roll');assert.equal(r.usage.cost,.001);});
test('provider failures and malformed moves never silently substitute bots',async()=>{await assert.rejects(()=>modelMove({id:'x'},{},'key',async()=>({ok:false,status:401,json:async()=>({error:{message:'key invalid'}})})),/Match paused/);assert.throws(()=>parseReply('not JSON'),/paused/);const reply=await modelMove({id:'x'},{},'key',async()=>({ok:true,json:async()=>({model:'y',choices:[{message:{content:'{}'}}],usage:{cost:.01}})}));assert.equal(reply.reportedModel,'y');assert.equal(reply.usage.cost,.01);});
test('catalog excludes nontext models and malformed pricing',async()=>{const rows=await catalog(async()=>({ok:true,json:async()=>({data:[{id:'p/text',name:'Text',architecture:{output_modalities:['text']},pricing:{prompt:'0.001',completion:'0.002'}},{id:'p/image',architecture:{output_modalities:['image']},pricing:{prompt:'0',completion:'0'}}]})}));assert.equal(rows.length,1);assert.equal(rows[0].promptPrice,.001);});
