import * as THREE from 'three';
import {spaces} from './game.mjs';
const locations=Array.from({length:20},(_,i)=>i<6?[2.5-i,2.5]:i<11?[-2.5,7.5-i]:i<16?[i-12.5,-2.5]:[2.5,i-17.5]);
export function createBoard(host,onSelect=()=>{}){let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});}catch{host.innerHTML='<p class="board-unavailable">3D is unavailable. Use the property list and turn controls below.</p>';return {update(){}};}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;host.append(renderer.domElement);renderer.domElement.setAttribute('aria-hidden','true');
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.1,100);camera.position.set(0,9.7,7.4);camera.lookAt(0,0,0);scene.add(new THREE.HemisphereLight(0xffffff,0x797363,2.4));const sun=new THREE.DirectionalLight(0xffffff,2.6);sun.position.set(-3,8,4);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);
const material=color=>new THREE.MeshStandardMaterial({color,roughness:.72});const base=new THREE.Mesh(new THREE.BoxGeometry(6.2,.18,6.2),material('#a3ae97'));base.position.y=-.14;base.receiveShadow=true;scene.add(base);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(50,50),new THREE.ShadowMaterial({opacity:.15}));ground.rotation.x=-Math.PI/2;ground.position.y=-.24;ground.receiveShadow=true;scene.add(ground);
function texture(lines,color='#253128',size=55,background=null){const c=document.createElement('canvas');c.width=512;c.height=512;const ctx=c.getContext('2d');if(background){ctx.fillStyle=background;ctx.fillRect(0,0,512,512);}ctx.fillStyle=color;ctx.font=`600 ${size}px Arial`;ctx.textAlign='center';ctx.textBaseline='middle';lines.forEach((text,i)=>ctx.fillText(text,256,215+i*67));return new THREE.CanvasTexture(c);}
const tiles=[],owners=[],buildings=[];
locations.forEach(([x,z],i)=>{const s=spaces[i],tile=new THREE.Mesh(new THREE.BoxGeometry(.98,.1,.98),material(s.kind==='property'?'#faf5e6':s.kind==='chance'?'#e7d6bd':'#dce5cf'));tile.position.set(x,0,z);tile.receiveShadow=true;tile.userData.space=i;tiles.push(tile);scene.add(tile);const lines=s.name.split(' ');if(s.price)lines.push('$'+s.price);const label=new THREE.Mesh(new THREE.PlaneGeometry(.94,.94),new THREE.MeshBasicMaterial({map:texture(lines,'#253128',s.name.length>16?45:55),transparent:true,toneMapped:false,depthWrite:false}));label.rotation.x=-Math.PI/2;label.position.set(x,.058,z);scene.add(label);if(s.color){const stripe=new THREE.Mesh(new THREE.BoxGeometry(.98,.015,.17),material(s.color));stripe.position.set(x,.063,z-.39);scene.add(stripe);}const owner=new THREE.Mesh(new THREE.BoxGeometry(.68,.035,.08),material('#faf5e6'));owner.position.set(x,.095,z+.38);owner.visible=false;scene.add(owner);owners.push(owner);buildings.push([]);});
const center=new THREE.Mesh(new THREE.PlaneGeometry(3.5,3.5),new THREE.MeshBasicMaterial({map:texture(['TERMS APPLY','BUY • BUILD • COLLECT'],'#36533c',46),transparent:true,toneMapped:false}));center.rotation.x=-Math.PI/2;center.position.y=-.041;scene.add(center);
function diceTexture(value){const c=document.createElement('canvas');c.width=c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#fffdf1';ctx.fillRect(0,0,128,128);ctx.fillStyle='#283d32';const points={1:[[64,64]],2:[[34,34],[94,94]],3:[[34,34],[64,64],[94,94]],4:[[34,34],[94,34],[34,94],[94,94]],5:[[34,34],[94,34],[64,64],[34,94],[94,94]],6:[[34,30],[94,30],[34,64],[94,64],[34,98],[94,98]]};for(const [x,y] of points[value]){ctx.beginPath();ctx.arc(x,y,9,0,Math.PI*2);ctx.fill();}return new THREE.CanvasTexture(c);}
const dice=Array.from({length:2},(_,i)=>{const mesh=new THREE.Mesh(new THREE.BoxGeometry(.4,.4,.4),new THREE.MeshStandardMaterial({map:diceTexture(1),roughness:.6}));mesh.position.set(i*.65-.325,.21,1);mesh.castShadow=true;scene.add(mesh);return mesh;});
let pieces=[],targets=[],last=performance.now(),current=0,lastRoll='',spin=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function update(match){current=match.current;while(pieces.length<match.players.length){const i=pieces.length,group=new THREE.Group(),mat=material(match.players[i].model.color),body=new THREE.Mesh(new THREE.CylinderGeometry(.07,.12,.27,24),mat);body.position.y=.2;body.castShadow=true;group.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.09,20,12),mat);head.position.y=.39;head.castShadow=true;group.add(head);scene.add(group);pieces.push(group);}pieces.forEach((piece,i)=>piece.visible=i<match.players.length&&!match.players[i].bankrupt);match.players.forEach((p,i)=>{const [x,z]=locations[p.position],angle=i*Math.PI*2/Math.max(6,match.players.length);targets[i]=new THREE.Vector3(x+Math.cos(angle)*.27,.07,z+Math.sin(angle)*.27);pieces[i].traverse(mesh=>{if(mesh.material)mesh.material.color.set(p.model.color);});if(!pieces[i].userData.ready||reduced){pieces[i].position.copy(targets[i]);pieces[i].userData.ready=true;}});
match.properties.forEach((lot,i)=>{const p=match.players.find(p=>p.model.id===lot.owner);owners[i].visible=!!p;if(p)owners[i].material.color.set(p.model.color);while(buildings[i].length>lot.houses){const house=buildings[i].pop();scene.remove(house);house.geometry.dispose();house.material.dispose();}while(buildings[i].length<lot.houses){const j=buildings[i].length,house=new THREE.Mesh(new THREE.BoxGeometry(.14,.15,.16),material('#447650'));house.position.set(locations[i][0]-.23+j*.23,.17,locations[i][1]-.34);house.castShadow=true;scene.add(house);buildings[i].push(house);}});
const roll=match.id+':'+(match.lastRoll?.tick||0);if(roll!==lastRoll){lastRoll=roll;spin=reduced?0:1;dice.forEach((die,i)=>{die.material.map?.dispose();die.material.map=diceTexture(match.dice[i]);die.material.needsUpdate=true;});}}
const ray=new THREE.Raycaster();renderer.domElement.addEventListener('click',e=>{const rect=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const hit=ray.intersectObjects(tiles)[0];if(hit)onSelect(hit.object.userData.space);});
const resize=new ResizeObserver(()=>{renderer.setSize(host.clientWidth,host.clientHeight,false);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();});resize.observe(host);
renderer.setAnimationLoop(now=>{const dt=Math.min((now-last)/1000,.1);last=now;pieces.forEach((piece,i)=>{if(targets[i]){piece.position.lerp(targets[i],1-Math.exp(-9*dt));piece.scale.setScalar(i===current?1.2:1);}});if(spin>0){spin=Math.max(0,spin-dt*1.7);dice.forEach((die,i)=>die.rotation.set(spin*Math.PI*2,spin*Math.PI*(i+1),0));}renderer.render(scene,camera);});return {update};}
