import * as THREE from 'three';
import {spaces} from './game.mjs';
import {movementRoute} from './movement.mjs';
const locations=Array.from({length:20},(_,i)=>i<6?[2.5-i,2.5]:i<11?[-2.5,7.5-i]:i<16?[i-12.5,-2.5]:[2.5,i-17.5]);
export function createBoard(host,onSelect=()=>{}){let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});}catch{host.innerHTML='<p class="board-unavailable">3D is unavailable. Use the property list and turn controls below.</p>';return {update(){},setSelected(){},setView(){}};}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;host.append(renderer.domElement);renderer.domElement.setAttribute('aria-hidden','true');const activeLabel=document.createElement('span');activeLabel.className='board-token-label';host.append(activeLabel);let activeName='';
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.1,100);camera.position.set(0,8.8,5.2);camera.lookAt(0,0,0);scene.add(new THREE.HemisphereLight(0xffffff,0xb2c7bd,1.3));const sun=new THREE.DirectionalLight(0xffffff,1.5);sun.position.set(-3,8,4);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);
const material=color=>new THREE.MeshStandardMaterial({color,roughness:.48});const base=new THREE.Mesh(new THREE.BoxGeometry(6.2,.18,6.2),material('#c6e4d3'));base.position.y=-.14;base.receiveShadow=true;scene.add(base);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(50,50),new THREE.ShadowMaterial({opacity:.15}));ground.rotation.x=-Math.PI/2;ground.position.y=-.24;ground.receiveShadow=true;scene.add(ground);
function texture(lines,color='#101c15',size=55,background=null){const c=document.createElement('canvas');c.width=512;c.height=512;const ctx=c.getContext('2d');if(background){ctx.fillStyle=background;ctx.fillRect(0,0,512,512);}ctx.fillStyle=color;ctx.font=`600 ${size}px Arial`;ctx.textAlign='center';ctx.textBaseline='middle';lines.forEach((text,i)=>ctx.fillText(text,256,215+i*67));const map=new THREE.CanvasTexture(c);map.colorSpace=THREE.SRGBColorSpace;return map;}
const tiles=[],owners=[],buildings=[];
locations.forEach(([x,z],i)=>{const s=spaces[i],tile=new THREE.Mesh(new THREE.BoxGeometry(.98,.1,.98),material(s.kind==='chance'?'#ffe3b1':'#eff5e7'));tile.position.set(x,0,z);tile.receiveShadow=true;tile.userData.space=i;tiles.push(tile);scene.add(tile);const lines=(s.kind==='chance'?'News':s.name).split(' ');if(s.price)lines.push('$'+s.price);const label=new THREE.Mesh(new THREE.PlaneGeometry(.94,.94),new THREE.MeshBasicMaterial({map:texture(lines,'#101c15',s.name.length>16?65:70),transparent:true,toneMapped:false,depthWrite:false}));label.rotation.x=-Math.PI/2;label.position.set(x,.058,z);scene.add(label);if(s.color){const stripe=new THREE.Mesh(new THREE.BoxGeometry(.98,.015,.17),new THREE.MeshBasicMaterial({color:s.color}));stripe.position.set(x,.063,z-.39);scene.add(stripe);}const owner=new THREE.Mesh(new THREE.BoxGeometry(.68,.035,.08),material('#eff5e7'));owner.position.set(x,.095,z+.38);owner.visible=false;scene.add(owner);owners.push(owner);buildings.push([]);});
const frame=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(6.2,.18,6.2)),new THREE.LineBasicMaterial({color:'#153e2a'}));frame.position.y=-.14;scene.add(frame);
const centerCanvas=document.createElement('canvas');centerCanvas.width=1024;centerCanvas.height=512;const centerContext=centerCanvas.getContext('2d');centerContext.fillStyle='#d71920';centerContext.fillRect(45,140,934,165);centerContext.strokeStyle='#ffffff';centerContext.lineWidth=6;centerContext.strokeRect(55,150,914,145);centerContext.fillStyle='#ffffff';centerContext.textAlign='center';centerContext.font='bold 95px Arial';centerContext.fillText('TERMS APPLY',512,260);centerContext.fillStyle='#193c2a';centerContext.font='600 35px Arial';centerContext.fillText('BUY · BUILD · LEARN',512,380);const center=new THREE.Mesh(new THREE.PlaneGeometry(3.5,1.75),new THREE.MeshBasicMaterial({map:(()=>{const map=new THREE.CanvasTexture(centerCanvas);map.colorSpace=THREE.SRGBColorSpace;return map;})(),transparent:true,toneMapped:false}));center.rotation.x=-Math.PI/2;center.position.set(0,-.039,-.35);scene.add(center);
function diceTexture(value){const c=document.createElement('canvas');c.width=c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#fffdf1';ctx.fillRect(0,0,128,128);ctx.fillStyle='#283d32';const points={1:[[64,64]],2:[[34,34],[94,94]],3:[[34,34],[64,64],[94,94]],4:[[34,34],[94,34],[34,94],[94,94]],5:[[34,34],[94,34],[64,64],[34,94],[94,94]],6:[[34,30],[94,30],[34,64],[94,64],[34,98],[94,98]]};for(const [x,y] of points[value]){ctx.beginPath();ctx.arc(x,y,9,0,Math.PI*2);ctx.fill();}const map=new THREE.CanvasTexture(c);map.colorSpace=THREE.SRGBColorSpace;return map;}
const dice=Array.from({length:2},(_,i)=>{const mesh=new THREE.Mesh(new THREE.BoxGeometry(.4,.4,.4),new THREE.MeshStandardMaterial({map:diceTexture(1),roughness:.6}));mesh.position.set(i*.65-.325,.21,1);mesh.castShadow=true;scene.add(mesh);return mesh;});
let pieces=[],targets=[],paths=[],matchId=null,last=performance.now(),current=0,lastRoll='',spin=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function update(match){if(matchId!==match.id){pieces.forEach(p=>p.userData.ready=false);paths=[];matchId=match.id;}current=match.current;activeName=match.finishedAt?'':match.players[current].model.name;activeLabel.textContent=activeName;while(pieces.length<match.players.length){const group=new THREE.Group();scene.add(group);pieces.push(group);}match.players.forEach((p,i)=>{const group=pieces[i];if(group.userData.identity===p.model.id)return;while(group.children.length){const mesh=group.children[0];group.remove(mesh);mesh.geometry.dispose();mesh.material.dispose();}group.userData.identity=p.model.id;group.userData.ready=false;const mat=new THREE.MeshStandardMaterial({color:p.model.color,metalness:.55,roughness:.25}),base=new THREE.Mesh(new THREE.CylinderGeometry(.15,.17,.07,24),mat);base.position.y=.05;base.castShadow=true;group.add(base);const id=p.model.id.toLowerCase();const shape=id.includes('claude')?new THREE.SphereGeometry(.14,24,16):id.includes('gemini')?new THREE.ConeGeometry(.16,.32,24):id.includes('codex')?new THREE.BoxGeometry(.23,.26,.23):id.includes('grok')?new THREE.OctahedronGeometry(.18):id.includes('deepseek')?new THREE.CylinderGeometry(.12,.12,.29,6):new THREE.TorusGeometry(.12,.045,12,24);const token=new THREE.Mesh(shape,mat.clone());token.position.y=.25;token.castShadow=true;group.add(token);});pieces.forEach((piece,i)=>piece.visible=i<match.players.length&&!match.players[i].bankrupt);match.players.forEach((p,i)=>{const [x,z]=locations[p.position],angle=i*Math.PI*2/Math.max(6,match.players.length);targets[i]=new THREE.Vector3(x+Math.cos(angle)*.27,.07,z+Math.sin(angle)*.27);if(pieces[i].userData.ready&&pieces[i].userData.square!==p.position){const steps=match.lastRoll?.player===p.model.id?match.dice.reduce((a,b)=>a+b,0):null;paths[i]=movementRoute(pieces[i].userData.square,p.position,steps).map(j=>new THREE.Vector3(locations[j][0]+Math.cos(angle)*.27,.07,locations[j][1]+Math.sin(angle)*.27));}pieces[i].userData.square=p.position;pieces[i].traverse(mesh=>{if(mesh.material)mesh.material.color.set(p.model.color);});if(!pieces[i].userData.ready||reduced){pieces[i].position.copy(targets[i]);paths[i]=[];pieces[i].userData.ready=true;}});
match.properties.forEach((lot,i)=>{const p=match.players.find(p=>p.model.id===lot.owner);owners[i].visible=!!p;if(p)owners[i].material.color.set(p.model.color);while(buildings[i].length>lot.houses){const house=buildings[i].pop();scene.remove(house);house.traverse(mesh=>{mesh.geometry?.dispose();mesh.material?.dispose();});}while(buildings[i].length<lot.houses){const j=buildings[i].length,house=new THREE.Group(),walls=new THREE.Mesh(new THREE.BoxGeometry(.16,.15,.19),material('#008b46')),roof=new THREE.Mesh(new THREE.ConeGeometry(.155,.11,4),material('#005b30'));walls.position.y=.075;roof.rotation.y=Math.PI/4;roof.position.y=.20;walls.castShadow=roof.castShadow=true;house.add(walls,roof);house.position.set(locations[i][0]-.24+j*.24,.09,locations[i][1]-.32);scene.add(house);buildings[i].push(house);}});
const roll=match.id+':'+(match.lastRoll?.tick||0);if(roll!==lastRoll){lastRoll=roll;spin=reduced?0:1;dice.forEach((die,i)=>{die.material.map?.dispose();die.material.map=diceTexture(match.dice[i]);die.material.needsUpdate=true;});}}
const ray=new THREE.Raycaster();renderer.domElement.addEventListener('click',e=>{const rect=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const hit=ray.intersectObjects(tiles)[0];if(hit)onSelect(hit.object.userData.space);});
const resize=new ResizeObserver(()=>{renderer.setSize(host.clientWidth,host.clientHeight,false);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();});resize.observe(host);
renderer.setAnimationLoop(now=>{const dt=Math.min((now-last)/1000,.1);last=now;pieces.forEach((piece,i)=>{if(targets[i]){const target=paths[i]?.[0]||targets[i];piece.position.lerp(target,1-Math.exp(-17*dt));if(paths[i]?.length&&piece.position.distanceTo(target)<.06)paths[i].shift();piece.scale.setScalar(i===current?1.2:1);}});if(spin>0){spin=Math.max(0,spin-dt*1.7);dice.forEach((die,i)=>die.rotation.set(spin*Math.PI*2,spin*Math.PI*(i+1),0));}if(pieces[current]&&activeName){const point=pieces[current].position.clone();point.y+=.55;point.project(camera);activeLabel.hidden=false;activeLabel.style.left=(point.x+1)/2*host.clientWidth+'px';activeLabel.style.top=(1-point.y)/2*host.clientHeight+'px';}else activeLabel.hidden=true;renderer.render(scene,camera);});return {update,setSelected(index){tiles.forEach((tile,i)=>{tile.material.emissive.set(i===index?'#8cae60':'#000000');tile.material.emissiveIntensity=.35;});},setView(view){camera.position.set(0,view==='top'?11.6:8.8,view==='top'?.01:5.2);camera.lookAt(0,0,0);}};}
