import * as THREE from 'three';
const labels=Array.from({length:16},(_,i)=>i===0?'START':String(i+1));
const locations=Array.from({length:16},(_,i)=>i<5?[2-i,2]:i<9?[-2,6-i]:i<13?[i-10,-2]:[2,i-14]);
export function createBoard(host){let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});}catch{host.innerHTML='<p class="board-unavailable">3D is unavailable on this device. Follow every move and score below.</p>';return {update(){}};}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;host.append(renderer.domElement);renderer.domElement.setAttribute('aria-hidden','true');
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,1,.1,100);camera.position.set(0,7.7,6.1);camera.lookAt(0,0,0);scene.add(new THREE.HemisphereLight(0xffffff,0x797363,2.8));const sun=new THREE.DirectionalLight(0xffffff,3);sun.position.set(-3,7,4);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);
const material=(color)=>new THREE.MeshStandardMaterial({color,roughness:.75});const base=new THREE.Mesh(new THREE.BoxGeometry(5.35,.18,5.35),material('#b9bdaf'));base.position.y=-.14;base.receiveShadow=true;scene.add(base);
const plane=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.ShadowMaterial({opacity:.12}));plane.rotation.x=-Math.PI/2;plane.position.y=-.24;plane.receiveShadow=true;scene.add(plane);
function textTexture(text,color='#42483f',size=23){const c=document.createElement('canvas');c.width=512;c.height=512;const ctx=c.getContext('2d');ctx.fillStyle=color;ctx.font=`600 ${size}px Arial`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,256,256);return new THREE.CanvasTexture(c);}
locations.forEach(([x,z],i)=>{const tile=new THREE.Mesh(new THREE.BoxGeometry(.96,.1,.96),material(i===3?'#e8c8b7':i===5||i===12?'#c6dbcb':'#f1f0e5'));tile.position.set(x,0,z);tile.receiveShadow=true;scene.add(tile);const label=new THREE.Mesh(new THREE.PlaneGeometry(.95,.95),new THREE.MeshBasicMaterial({map:textTexture(labels[i],'#343a32',labels[i]==='START'?66:100),transparent:true,depthWrite:false,toneMapped:false}));label.rotation.x=-Math.PI/2;label.position.set(x,.056,z);scene.add(label);});
const center=new THREE.Mesh(new THREE.PlaneGeometry(2.8,2.8),new THREE.MeshBasicMaterial({map:textTexture('TERMS APPLY','#566657',43),transparent:true}));center.rotation.x=-Math.PI/2;center.position.y=.001;scene.add(center);
let pieces=[],targets=[],last=performance.now(),current=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function update(match){current=match.current;while(pieces.length<match.players.length){const i=pieces.length,group=new THREE.Group(),mat=material(match.players[i].model.color);const body=new THREE.Mesh(new THREE.CylinderGeometry(.085,.15,.28,24),mat);body.position.y=.2;body.castShadow=true;group.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.095,24,16),mat);head.position.y=.39;head.castShadow=true;group.add(head);scene.add(group);pieces.push(group);}pieces.forEach((piece,i)=>piece.visible=i<match.players.length);match.players.forEach((p,i)=>{const [x,z]=locations[p.game.players[0].position],angle=i*Math.PI*2/Math.max(5,match.players.length),offset=[Math.cos(angle)*.28,Math.sin(angle)*.28];targets[i]=new THREE.Vector3(x+offset[0],.07,z+offset[1]);pieces[i].traverse(mesh=>{if(mesh.material){mesh.material.color.set(p.model.color);mesh.material.emissive.set(i===current?'#242822':'#000000');}});if(!pieces[i].userData.ready||reduced){pieces[i].position.copy(targets[i]);pieces[i].userData.ready=true;}});}
const resize=new ResizeObserver(()=>{const width=host.clientWidth,height=host.clientHeight;renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();});resize.observe(host);
renderer.setAnimationLoop(now=>{const dt=Math.min((now-last)/1000,.1);last=now;pieces.forEach((piece,i)=>{if(targets[i]){piece.position.lerp(targets[i],1-Math.exp(-9*dt));piece.scale.setScalar(i===current?1.18:1);}});renderer.render(scene,camera);});return {update};}
