import {participantRoster,withoutHuman} from './participants.mjs';
import {startMatch,applyMove,botMove,result,demoRoster,humanPlayer,legalActions,upgradeMatch} from './game.mjs';
const storageKey='terms-apply-property-v1';let singleton;
export function browserDemo(){if(singleton)return singleton;let state={version:5,browserDemo:true,mode:'demo',running:true,status:'running',connected:false,thinking:false,requiresAdmin:false,interval:3000,roster:demoRoster,match:startMatch(demoRoster,1,Math.floor(Math.random()*1e8)),history:[],totals:{},limits:{requestsPerDay:200,usdPerDay:1},usage:{requests:0,cost:0,unknownCosts:0},message:'Demo strategies, no model calls. Your game is saved on this device.'};try{const saved=JSON.parse(localStorage.getItem(storageKey));if([4,5].includes(saved?.version)&&saved.browserDemo){state={...saved,version:5,match:upgradeMatch(saved.match)};state.match.players.forEach(p=>{p.model=demoRoster.find(d=>d.id===p.model.id)||p.model;});state.roster=state.roster.map(p=>demoRoster.find(d=>d.id===p.id)||p);}}catch{}
const stream={onmessage:null,onerror:null};let timer;const isHuman=()=>state.match.players[state.match.current].model.human;const hasHuman=()=>state.match.players.some(p=>p.model.human);
const emit=()=>{state.humanJoined=hasHuman();state.awaitingHuman=!!(state.running&&!state.match.finishedAt&&isHuman());try{localStorage.setItem(storageKey,JSON.stringify(state));}catch{}stream.onmessage?.({data:JSON.stringify(state)});};
const schedule=()=>{clearTimeout(timer);if(!state.running||(!state.match.finishedAt&&isHuman())||(state.match.finishedAt&&hasHuman()))return;timer=setTimeout(tick,state.match.finishedAt?6000:state.interval);};
function record(){const r={...result(state.match),mode:'demo'};state.history.unshift(r);state.history=state.history.slice(0,15);for(const row of r.rows){const key='demo:'+row.id,t=state.totals[key]||{id:row.id,name:row.name,mode:'demo',games:0,wins:0,wealth:0,properties:0,rejected:0};t.games++;t.wins+=r.winners.includes(row.id)?1:0;t.wealth+=row.netWorth;t.properties+=row.properties;t.rejected+=row.rejected;state.totals[key]=t;}try{localStorage.setItem(storageKey+'-match-'+r.id,JSON.stringify({result:r,match:state.match}));if(r.id>15)localStorage.removeItem(storageKey+'-match-'+(r.id-15));}catch{}}
function tick(){try{if(state.running){if(state.match.finishedAt)state.match=startMatch(state.roster.filter(p=>!p.human),state.match.id+1,Math.floor(Math.random()*1e8));else if(!isHuman()){const p=state.match.players[state.match.current],move=botMove(state.match,p);state.match=applyMove(state.match,move.action,move.reason);if(state.match.finishedAt)record();}emit();}}catch{state.running=false;state.status='error';state.message='The game stopped. Reload to restore your last saved turn.';emit();}schedule();}
const reset=roster=>{state.roster=roster;state.match=startMatch(roster,state.match.id+1,Math.floor(Math.random()*1e8));state.running=true;state.status='running';};
async function request(path,options={}){let status=200,body;if(path==='/api/control'){const b=JSON.parse(options.body||'{}');if(b.action==='pause'){state.running=false;state.status='paused';}else if(b.action==='resume'){state.running=true;state.status='running';}else if(b.action==='pace'&&Number.isFinite(Number(b.interval))&&Number(b.interval)>=300&&Number(b.interval)<=60000){state.interval=Number(b.interval);}else if(b.action==='step'){if(state.running||isHuman()||state.match.finishedAt){status=400;body={error:'Pause first. Next move advances a demo player; take human turns with the game controls.'};}else{const move=botMove(state.match,state.match.players[state.match.current]);state.match=applyMove(state.match,move.action,move.reason);if(state.match.finishedAt)record();}}else if(b.action==='participants'){try{reset(participantRoster(b.players,b.includeHuman===true));}catch(e){status=400;body={error:e.message};}}else if(b.action==='join'){if(!hasHuman())reset([humanPlayer,...state.roster.filter(p=>!p.human)]);}else if(b.action==='again')reset(state.roster);else if(b.action==='leave')reset(withoutHuman(state.roster));else if(b.action==='move'){const legal=legalActions(state.match);if(!state.running||!isHuman()||!legal.some(a=>JSON.stringify(a)===JSON.stringify(b.move))){status=400;body={error:'Wait for your turn and choose an available move.'};}else{state.match=applyMove(state.match,b.move,'Human player chose this move.');if(state.match.finishedAt)record();}}else if(b.action==='configure'&&b.mode==='demo'&&Number.isFinite(Number(b.interval))&&Number(b.interval)>=300&&Number(b.interval)<=60000){state.interval=Number(b.interval);reset(state.roster);}else{status=400;body={error:'The browser game uses demo strategies. Real model play requires the server.'};}if(!body){body={ok:true};emit();schedule();}}
else if(path==='/api/models')body={models:[],error:'Model selection is available on the full server.',connected:false};else if(path.startsWith('/api/matches/')){try{body=JSON.parse(localStorage.getItem(storageKey+'-match-'+path.split('/').at(-1)));}catch{}if(!body){status=404;body={error:'This record is unavailable on this device.'};}}else if(path==='/api/state'||path==='/api/export')body=state;else{status=404;body={error:'Not available in this demo.'};}return {ok:status===200,status,json:async()=>structuredClone(body)};}
singleton={stream,request,dispose:()=>{state.running=false;clearTimeout(timer);singleton=null;}};queueMicrotask(emit);schedule();return singleton;}
