import {browserDemo} from './browser-demo.mjs';
import {spaces,result,owned,netWorth,legalActions,rent,MAX_TURNS} from './game.mjs';
import {createBoard} from './board3d.mjs';
const $=s=>document.querySelector(s),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const isBrowserDemo=!!document.querySelector('meta[name="arena-runtime"][content="browser-demo"]')||new URLSearchParams(location.search).has('play');
const transport=isBrowserDemo?browserDemo():null;
const apiFetch=(path,options)=>transport?transport.request(path,options):fetch(path,options);
let state,selected=null,selectedSpace=null,connected=false,models=[],chosen=new Set(),catalogLoaded=false,board3d;
const token=(p,i)=>`<span class="token" style="--color:${esc(p.model.color)}">${p.model.human?'Y':i+1}</span>`;
const shortName=p=>p.model.name.replace(/^[^:]+:\s*/,''),time=x=>new Date(x).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'}),money=x=>'$'+Math.round(x).toLocaleString();
function render(){if(!state)return;const focused=document.activeElement,focusPlayer=focused?.dataset?.player,focusSpace=focused?.dataset?.space,focusMove=focused?.dataset?.move,manageOpen=$('#turn-actions .manage-properties')?.open;const m=state.match,players=m.players,current=players[m.current],human=players.find(p=>p.model.human);$('#loading').hidden=true;$('#arena').hidden=false;
 const source=state.mode==='demo'?'Demo strategies · no model calls':'Connected AI models';$('#connection-label').textContent=!connected?'Reconnecting…':m.finishedAt?'Game finished':state.awaitingHuman?'Your turn':state.running?source:state.status==='paused'?'Game paused':'Game stopped';$('#connection-detail').textContent=state.running?(state.awaitingHuman?'The game is waiting for your move.':state.browserDemo?'Saved on this device.':'Players take turns automatically.'):state.message;$('#pause').textContent=state.running?'Pause':'Resume';$('#pause').disabled=!connected||state.thinking||(state.requiresAdmin&&!$('#operator-token').value);$('#status-dot').className='status-dot '+(state.running&&!m.finishedAt?'running':'');
 $('#join').hidden=!!human;$('#leave').hidden=!human;$('#again').hidden=!human||!m.finishedAt;$('#join-note').textContent=human?'Your seat is saved. The game waits for you.':'Start a personal game against five demo players.';$('#join').disabled=!connected;
 $('#match-number').textContent=m.id;$('#table-meta').textContent=m.finishedAt?'Finished':`Turn ${Math.min(MAX_TURNS,current.turns+1)} of ${MAX_TURNS}`;if($('#follow').checked||!players.some(p=>p.model.id===selected)||state.awaitingHuman)selected=current.model.id;
 const p=players.find(p=>p.model.id===selected),properties=owned(m,p);
 if(!board3d)board3d=createBoard($('#board'),index=>{selectedSpace=index;render();});board3d.update(m);$('#board').setAttribute('aria-label',`Property game board. Dice ${m.dice.join(' and ')}. ${players.map(p=>shortName(p)+' at '+spaces[p.position].name).join('. ')}`);
 $('#seat-strip').innerHTML=players.map((p,i)=>`<button class="seat ${m.current===i&&!m.finishedAt?'active':''}" style="--color:${esc(p.model.color)}" data-player="${esc(p.model.id)}" aria-pressed="${selected===p.model.id}">${token(p,i)}<span><strong>${esc(shortName(p))}</strong><span>${p.bankrupt?'Bankrupt':money(p.cash)}</span></span></button>`).join('');
 $('#board-list').innerHTML=spaces.map((s,i)=>`<button data-space="${i}"><span>${i+1}. ${esc(s.name)}</span><small>${s.price?money(s.price)+' · '+esc(players.find(p=>p.model.id===m.properties[i].owner)?.model.name||'Available'):esc(s.kind)}</small></button>`).join('');const latest=m.events.at(-1);$('#latest-move').textContent=latest?`${latest.name}: ${latest.outcome}`:'Everyone starts with $1,200. The first player is ready to roll.';
 $('#inspected-player').textContent=shortName(p);$('#turn-label').textContent=m.finishedAt?'Game finished':p===current?(p.model.human?'Your turn':"Taking a turn"):'Following this player';$('#workspace-stats').innerHTML=`<p class="score"><strong>${money(p.cash)}</strong> cash</p><p class="turns">${properties.length} ${properties.length===1?'property':'properties'} · ${money(netWorth(m,p))} net worth${p.bankrupt?' · Bankrupt':''}</p><p class="dice-result">Dice: <strong>${m.lastRoll?m.dice.join(' + '):'Ready to roll'}</strong></p>`;
 const available=legalActions(m),labels=a=>a.type==='roll'?(current.jail?'Serve timeout turn':'Roll dice'):a.type==='buy'?`Buy for ${money(spaces[a.space].price)}`:a.type==='end'?'End turn':a.type==='build'?`Build on ${spaces[a.space].name} · $100`:`Sell ${spaces[a.space].name} · ${money((spaces[a.space].price+m.properties[a.space].houses*100)/2)}`;
 $('#turn-actions').innerHTML=m.finishedAt?'<p class="turn-prompt">Game over. The highest net worth wins.</p>':human&&current===human&&!human.bankrupt?`<p class="turn-prompt">${m.phase==='roll'?'Your turn. Roll the dice to move.':'Choose a move, then end your turn.'}</p><div class="move-buttons">${available.filter(a=>!['build','sell'].includes(a.type)).sort((a,b)=>({roll:0,buy:1,end:2}[a.type]-{roll:0,buy:1,end:2}[b.type])).map((a,i)=>`<button class="${i===0?'primary':''}" data-move="${esc(JSON.stringify(a))}" ${!state.running?'disabled':''}>${esc(labels(a))}</button>`).join('')}</div>${available.some(a=>['build','sell'].includes(a.type))?`<details class="manage-properties" ${manageOpen?'open':''}><summary>Build houses or sell properties</summary>${available.filter(a=>['build','sell'].includes(a.type)).map(a=>`<button data-move="${esc(JSON.stringify(a))}" ${!state.running?'disabled':''}>${esc(labels(a))}</button>`).join('')}</details>`:''}`:human?`<p class="turn-prompt">${human.bankrupt?'You are out of this game. Watch the remaining players.':`Waiting for ${esc(current.model.name)}. Your controls appear when the dice reach you.`}</p>`:'<p class="turn-prompt">Watching the demo. Join to roll your own dice.</p>';
 const i=selectedSpace??p.position,square=spaces[i],lot=m.properties[i],owner=players.find(p=>p.model.id===lot.owner);
 $('#workspace-tasks').innerHTML=`<div class="current-job"><h3>${selectedSpace===null?'Current square':'Selected square'}</h3><h4>${esc(square.name)}</h4>${square.kind==='property'?`<p>Price ${money(square.price)} · Rent ${money(rent(m,i))}</p><p class="property-owner">${owner?'Owned by '+esc(owner.model.name)+(lot.houses?' · '+lot.houses+' houses':''):'Available to buy when you land here.'}</p>`:`<p>${{start:'Collect $200 every time you pass Start.',chance:'Draw a card. You might gain cash or pay an unexpected bill.',tax:'Pay $80 to the bank.',jail:'Just visiting. A player sent here skips their next turn.',parking:'A free square. Nothing to pay.',timeout:'Move to timeout and skip your next turn.'}[square.kind]}</p>`}${selectedSpace!==null?'<button id="clear-space">Follow current square</button>':''}</div>`;
 $('#workspace-terms').innerHTML=properties.length?properties.map(i=>`<button class="property-row" data-space="${i}"><span class="property-swatch" style="background:${spaces[i].color}"></span><span>${esc(spaces[i].name)}</span><strong>${money(rent(m,i))} rent${m.properties[i].houses?' · '+m.properties[i].houses+' houses':''}</strong></button>`).join(''):'<p>No properties yet. Buy one when you land on it.</p>';
 $('#event-count').textContent=m.tick+' moves';const log=$('#event-log'),scroll=log.scrollTop;log.innerHTML=m.events.slice(-40).reverse().map(e=>`<div class="event"><time>${time(e.time)}</time><strong>${esc(e.name)}</strong><details><summary>${esc(e.outcome)}</summary><p>${esc(e.reason)}</p></details></div>`).join('')||'<p>No moves yet.</p>';log.scrollTop=scroll;
 const rows=Object.values(state.totals).filter(t=>t.mode===state.mode).sort((a,b)=>b.wins-a.wins);$('#results-caption').textContent=source;$('#results').innerHTML=rows.length?rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${r.games}</td><td>${r.wins}</td><td>${money((r.wealth||0)/r.games)}</td><td>${((r.properties||0)/r.games).toFixed(1)}</td><td>${r.rejected}</td></tr>`).join(''):'<tr><td colspan="6">Scores appear after the first game.</td></tr>';
 const openHistory=new Set([...$('#history').querySelectorAll('details[open]')].map(d=>d.dataset.match));$('#history').innerHTML=state.history.filter(h=>h.mode===state.mode).slice(0,15).map(h=>`<details class="history-item" data-match="${h.id}" ${openHistory.has(String(h.id))?'open':''}><summary>Game ${h.id} · ${esc(h.rows.filter(r=>h.winners.includes(r.id)).map(r=>r.name).join(' + '))} won</summary><p>${h.rows.map(r=>esc(r.name)+': '+money(r.netWorth)+' net worth').join('<br>')}</p><button data-record="${h.id}">Read moves</button><div id="record-${h.id}"></div></details>`).join('')||'<p>No finished games yet.</p>';
 if(m.finishedAt){const r=result(m);$('#turn-label').textContent='Winner'+(r.winners.length>1?'s':'');$('#inspected-player').textContent=r.rows.filter(p=>r.winners.includes(p.id)).map(p=>p.name).join(' + ');$('#workspace-stats').innerHTML=`<p class="score"><strong>${money(r.rows[0].netWorth)}</strong></p><p class="turns">Winning net worth · ${r.winners.length>1?'Shared win':'Game complete'}</p>`;}
if(focusPlayer||focusSpace||focusMove){const replacement=[...document.querySelectorAll('[data-player],[data-space],[data-move]')].find(el=>focusPlayer?el.dataset.player===focusPlayer:focusSpace?el.dataset.space===focusSpace:el.dataset.move===focusMove);replacement?.focus({preventScroll:true});}
}
async function control(payload){const r=await apiFetch('/api/control',{method:'POST',headers:{'Content-Type':'application/json',...(state?.requiresAdmin?{'X-Admin-Token':$('#operator-token').value}:{})},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok)throw Error(b.error||'Runner control failed.');return b;}
$('#pause').onclick=async()=>{const b=$('#pause');b.disabled=true;try{await control({action:state.running?'pause':'resume'});$('#feedback').textContent='';}catch(e){$('#feedback').textContent=e.message;}finally{render();}};
const recordCache=new Map();$('#history').onclick=async e=>{const b=e.target.closest('[data-record]');if(!b)return;const id=b.dataset.record;b.disabled=true;try{if(!recordCache.has(id)){const r=await apiFetch('/api/matches/'+id);const data=await r.json();if(!r.ok)throw Error(data.error);recordCache.set(id,data);}showRecord(id);}catch(err){b.textContent=err.message;b.disabled=false;}};
function showRecord(id){const el=$('#record-'+id),record=recordCache.get(String(id));if(!el||!record)return;el.innerHTML='<div class="event-log">'+record.match.events.map(e=>`<div class="event"><time>${time(e.time)}</time><span>${esc(e.name)}</span><details><summary>${esc(e.outcome)}</summary><p>${esc(e.reason)}</p><code>${esc(JSON.stringify(e.action))}</code></details></div>`).join('')+'</div>';const b=document.querySelector(`[data-record="${id}"]`);if(b){b.textContent='Transcript loaded';b.disabled=true;}}
$('#follow').onchange=render;$('#seat-strip').onclick=e=>{const b=e.target.closest('[data-player]');if(b){selected=b.dataset.player;$('#follow').checked=false;render();}};
function renderModels(){const q=$('#model-search').value.toLowerCase(),filtered=models.filter(m=>(m.id+' '+m.name).toLowerCase().includes(q));$('#model-list').innerHTML=filtered.slice(0,80).map(m=>`<label class="model-option"><input type="checkbox" value="${esc(m.id)}" ${chosen.has(m.id)?'checked':''}><span>${esc(m.name)}<span class="small">${esc(m.id)} · $${(m.promptPrice*1e6).toFixed(2)} / $${(m.completionPrice*1e6).toFixed(2)}</span></span></label>`).join('')||'<p class="empty">No matching text models.</p>';$('#selected-models').textContent=`${chosen.size} selected: ${[...chosen].join(', ')||'none'}`;$('#catalog-status').textContent=catalogLoaded?`${models.length} text models in the current catalog${filtered.length>80?' · refine your search to see more':''}`:'Loading the current model catalog…';}
function modeChanged(){$('#model-settings').hidden=$('#mode').value==='demo';$('#start').textContent=$('#mode').value==='demo'?'Start bot demo':'Start model table';$('#start').disabled=$('#mode').value==='real'&&!state?.connected;}
$('#configure').onclick=async()=>{if(!state){$('#feedback').textContent='Wait for the runner connection first.';return;}$('#settings-error').textContent='';$('#operator-settings').hidden=!state.requiresAdmin;$('#mode').value=state.browserDemo?'demo':'real';$('#requests').value=state.limits.requestsPerDay;$('#budget').value=state.limits.usdPerDay;$('#pace').value=state.interval/1000;$('#usage-summary').textContent=`Today: ${state.usage.requests} API requests · $${state.usage.cost.toFixed(4)} tracked usage${state.usage.estimatedCost?' (includes $'+state.usage.estimatedCost.toFixed(4)+' in unreconciled reservations)':''}${state.usage.unknownCosts?' · cost missing for one or more responses':''}`;$('#key-status').innerHTML=state.browserDemo?'This free public page runs bots in your browser. Results are saved on this device. The full server and deployment instructions are in the GitHub repository. No model API calls are made.':state.connected?'OpenRouter key is configured on the server. Choose models and limits below.':'OpenRouter is not connected. Add your key to the server’s private <code>terms-apply/.env<br>OPENROUTER_API_KEY=your_key_here</code>Then restart with <code>npm start</code>Do not enter a key in the browser or commit this file.';$('#settings').showModal();chosen=new Set(state.mode==='real'?state.roster.map(m=>m.id):[]);modeChanged();renderModels();if(state.browserDemo){$('#mode').querySelector('option[value=real]').disabled=true;return;}try{const res=await apiFetch('/api/models'),data=await res.json();if(!res.ok||data.error)throw Error(data.error||'Catalog unavailable.');models=data.models;catalogLoaded=true;if(!chosen.size){for(const family of ['openai','anthropic','google','deepseek']){const options=models.filter(m=>m.family===family&&(family!=='google'||m.id.includes('gemini'))&&(family!=='openai'||(!m.id.includes('oss')&&!m.id.includes('audio')))).sort((a,b)=>(a.promptPrice+a.completionPrice)-(b.promptPrice+b.completionPrice));if(options[0])chosen.add(options[0].id);}}renderModels();}catch(e){$('#catalog-status').textContent=e.message;$('#model-list').innerHTML='';}};
$('#close-settings').onclick=()=>$('#settings').close();$('#mode').onchange=modeChanged;$('#model-search').oninput=renderModels;$('#model-list').onchange=e=>{if(e.target.type==='checkbox'){if(e.target.checked){if(chosen.size>=24){e.target.checked=false;$('#settings-error').textContent='Select at most 24 models.';return;}chosen.add(e.target.value);}else chosen.delete(e.target.value);renderModels();}};
$('#settings-form').onsubmit=async e=>{e.preventDefault();$('#start').disabled=true;try{await control({action:'configure',mode:$('#mode').value,models:[...chosen],requestsPerDay:Number($('#requests').value),usdPerDay:Number($('#budget').value),interval:Number($('#pace').value)*1000});$('#settings').close();$('#feedback').textContent='';}catch(e){$('#settings-error').textContent=e.message;}finally{modeChanged();}};
if(isBrowserDemo){$('#configure').textContent='Demo controls';$('#requests').parentElement.hidden=true;$('#budget').parentElement.hidden=true;$('#usage-summary').hidden=true;$('#settings-note').textContent='Starting a new game resets the current game. This demo makes no paid API calls.';document.querySelector('#records .section-heading p').textContent='Finished games and their moves are saved in this browser.';document.querySelector('#players .section-heading p').textContent='Scores from the demo bots on this device. Tied players share the win.';const exportAnchor=document.querySelector('a[href="/api/export"]');exportAnchor.href='#';exportAnchor.addEventListener('click',async e=>{e.preventDefault();const data=await (await apiFetch('/api/export')).json(),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='terms-apply-browser-record.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}
const stream=transport?transport.stream:new EventSource('/api/events');stream.onmessage=e=>{try{state=JSON.parse(e.data);connected=true;render();for(const id of recordCache.keys())showRecord(id);if($('#feedback').textContent==='Unable to read the latest table update.')$('#feedback').textContent='';}catch{$('#feedback').textContent='Unable to read the latest table update.';}};stream.onerror=()=>{connected=false;render();if(!state){$('#loading').textContent='The arena server is unavailable. Start it with npm start, then reload.';}};

async function humanControl(action){try{await control({action});selectedSpace=null;$('#feedback').textContent='';}catch(e){$('#feedback').textContent=e.message;}}
$('#join').onclick=()=>{if(!transport){location.href='?play=1#live';return;}humanControl('join');};
$('#leave').onclick=()=>humanControl('leave');$('#again').onclick=()=>humanControl('again');
$('#turn-actions').onclick=async e=>{const button=e.target.closest('[data-move]');if(!button)return;button.disabled=true;try{await control({action:'move',move:JSON.parse(button.dataset.move)});selectedSpace=null;$('#feedback').textContent='';}catch(err){$('#feedback').textContent=err.message;}finally{render();}};
$('#workspace-tasks').onclick=e=>{if(e.target.id==='clear-space'){selectedSpace=null;render();}};
$('#workspace-terms').onclick=e=>{const button=e.target.closest('[data-space]');if(button){selectedSpace=Number(button.dataset.space);render();}};
if(new URLSearchParams(location.search).has('play'))humanControl('join');

$('#board-list').onclick=e=>{const button=e.target.closest('[data-space]');if(button){selectedSpace=Number(button.dataset.space);render();}};
