import {browserDemo} from './browser-demo.mjs';
import {tasks,result} from './game.mjs';
import {createBoard} from './board3d.mjs';
const $=s=>document.querySelector(s),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const isBrowserDemo=!!document.querySelector('meta[name="arena-runtime"][content="browser-demo"]');
const transport=isBrowserDemo?browserDemo():null;
const apiFetch=(path,options)=>transport?transport.request(path,options):fetch(path,options);
let state,selected=null,connected=false,models=[],chosen=new Set(),catalogLoaded=false,board3d;
const token=(p,i)=>`<span class="token" style="--color:${esc(p.model.color)}">${i+1}</span>`;
const shortName=p=>p.model.name.replace(/^[^:]+:\s*/,''),time=x=>new Date(x).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'});
const verdicts={accept:'Right',revise:'Wrong',unknown:'Not enough information'};
function render(){if(!state)return;const focus=document.activeElement?.dataset?.player,m=state.match,players=m.players;$('#loading').hidden=true;$('#arena').hidden=false;
 const source=state.mode==='demo'?'Demo players · no model calls':'Connected AI models';$('#connection-label').textContent=!connected?'Reconnecting…':state.running?source+' · playing':state.status==='paused'?'Game paused':'Game stopped';$('#connection-detail').textContent=state.running?(state.browserDemo?'Runs while this page is open.':'Players take turns automatically.'):state.message;$('#pause').textContent=state.running?'Pause':'Resume';$('#pause').disabled=!connected||state.thinking||(state.requiresAdmin&&!$('#operator-token').value);$('#status-dot').className='status-dot '+(state.running?'running':'');
 $('#match-number').textContent=m.id;$('#table-meta').textContent=m.finishedAt?'Finished · next game in a moment':'12 turns per player';if($('#follow').checked||!players.some(p=>p.model.id===selected))selected=players[m.current].model.id;
 const p=players.find(p=>p.model.id===selected),g=p.game,done=g.taskState.filter(t=>t.done).length;
 if(!board3d)board3d=createBoard($('#board'));board3d.update(m);$('#board').setAttribute('aria-label',`Game board. ${players.map(p=>shortName(p)+' on square '+(p.game.players[0].position+1)).join('. ')}`);
 $('#seat-strip').innerHTML=players.map((p,i)=>`<button class="seat ${m.current===i&&!m.finishedAt?'active':''}" style="--color:${esc(p.model.color)}" data-player="${esc(p.model.id)}" aria-pressed="${selected===p.model.id}">${token(p,i)}<span><strong>${esc(shortName(p))}</strong><span>${p.game.taskState.filter(t=>t.done).length} jobs finished</span></span></button>`).join('');
 const latest=m.events.findLast(e=>e.player===p.model.id);$('#latest-move').textContent=latest?`${latest.name}: ${latest.outcome}`:'This player is waiting for their first turn.';
 $('#inspected-player').textContent=shortName(p);$('#turn-label').textContent=m.finishedAt?'Game finished':p===players[m.current]?'Playing next':'Following this player';$('#workspace-stats').innerHTML=`<p class="score"><strong>${done}</strong> jobs finished</p><p class="turns">${g.players[0].time} turns left · ${done>=3?'Goal reached':'Goal: 3 jobs'}${p.incorrect?' · '+p.incorrect+' wrong answers':''}</p>`;
 const latestOwn=m.events.findLast(e=>e.player===p.model.id&&e.action.task),t=g.taskState.find(t=>t.id===latestOwn?.action.task&&!t.done)||g.taskState.find(t=>!t.done)||g.taskState.at(-1),d=tasks.find(d=>d.id===t.id),step=t.done?3:t.work<2?0:t.read.length<2?1:2;
 $('#workspace-tasks').innerHTML=`<div class="current-job"><h3>${t.done?'Last finished job':'Current job'}</h3><h4>${esc(d.title)}</h4><p>${esc(d.question)}</p><p class="claim"><strong>Answer to check</strong> “${esc(d.claim)}”</p><ol class="job-steps">${['Prepare the answer','Check the facts','Make a decision'].map((label,i)=>`<li class="${i<step?'done':i===step?'next':''}"><span>${i<step?'Done':i+1}</span>${label}</li>`).join('')}</ol>${t.read.length===2?`<div class="facts"><h3>The two facts</h3>${d.sources.map(s=>`<p><strong>${esc(s[0])}</strong> ${esc(s[1])}</p>`).join('')}<p class="answer">${t.done?'Decision: '+verdicts[t.verdict]:'Does the answer hold up? Right, Wrong, or Not enough information.'}</p></div>`:'<p class="hint">The facts appear when this player checks them.</p>'}</div>`;
 $('#workspace-terms').innerHTML=g.taskState.map(t=>`<p class="job-row">${esc(tasks.find(d=>d.id===t.id).title)}<strong>${t.done?'Finished':t.work>=2&&t.read.length===2?'Ready to decide':t.work>=2?'Needs a fact check':'Not ready'}</strong></p>`).join('');
 $('#event-count').textContent=m.tick+' moves';const log=$('#event-log'),scroll=log.scrollTop;log.innerHTML=m.events.slice(-30).reverse().map(e=>`<div class="event"><time>${time(e.time)}</time><strong>${esc(e.name)}</strong><details><summary>${esc(e.outcome)}</summary><p>${esc(e.reason)}</p><code>${esc(JSON.stringify(e.action))}</code></details></div>`).join('')||'<p>No moves yet.</p>';log.scrollTop=scroll;
 const rows=Object.values(state.totals).filter(t=>t.mode===state.mode).sort((a,b)=>b.wins-a.wins);$('#results-caption').textContent=source;$('#results').innerHTML=rows.length?rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${r.games}</td><td>${r.wins}</td><td>${(r.tasks/r.games).toFixed(1)}</td><td>${r.open}</td><td>${r.incorrect}</td><td>${r.rejected}</td></tr>`).join(''):'<tr><td colspan="7">Scores appear after the first game.</td></tr>';
 const openHistory=new Set([...$('#history').querySelectorAll('details[open]')].map(d=>d.dataset.match));$('#history').innerHTML=state.history.filter(h=>h.mode===state.mode).slice(0,15).map(h=>`<details class="history-item" data-match="${h.id}" ${openHistory.has(String(h.id))?'open':''}><summary>Game ${h.id} · ${esc(h.rows.filter(r=>h.winners.includes(r.id)).map(r=>r.name).join(' + '))} won</summary><p>${h.rows.map(r=>esc(r.name)+': '+r.tasks+' finished jobs').join('<br>')}</p><button data-record="${h.id}">Read moves</button><div id="record-${h.id}"></div></details>`).join('')||'<p>No finished games yet.</p>';
 if(m.finishedAt){const r=result(m);$('#turn-label').textContent='Winner'+(r.winners.length>1?'s':'');$('#inspected-player').textContent=r.rows.filter(p=>r.winners.includes(p.id)).map(p=>p.name).join(' + ');}
 if(focus)document.querySelector(`[data-player="${CSS.escape(focus)}"]`)?.focus({preventScroll:true});
}
async function control(payload){const r=await apiFetch('/api/control',{method:'POST',headers:{'Content-Type':'application/json',...(state?.requiresAdmin?{'X-Admin-Token':$('#operator-token').value}:{})},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok)throw Error(b.error||'Runner control failed.');return b;}
$('#pause').onclick=async()=>{const b=$('#pause');b.disabled=true;try{await control({action:state.running?'pause':'resume'});$('#feedback').textContent='';}catch(e){$('#feedback').textContent=e.message;}finally{render();}};
const recordCache=new Map();$('#history').onclick=async e=>{const b=e.target.closest('[data-record]');if(!b)return;const id=b.dataset.record;b.disabled=true;try{if(!recordCache.has(id)){const r=await apiFetch('/api/matches/'+id);const data=await r.json();if(!r.ok)throw Error(data.error);recordCache.set(id,data);}showRecord(id);}catch(err){b.textContent=err.message;b.disabled=false;}};
function showRecord(id){const el=$('#record-'+id),record=recordCache.get(String(id));if(!el||!record)return;el.innerHTML='<div class="event-log">'+record.match.events.map(e=>`<div class="event"><time>${time(e.time)}</time><span>${esc(e.name)}</span><details><summary>${esc(e.outcome)}</summary><p>${esc(e.reason)}</p><code>${esc(JSON.stringify(e.action))}</code></details></div>`).join('')+'</div>';const b=document.querySelector(`[data-record="${id}"]`);if(b){b.textContent='Transcript loaded';b.disabled=true;}}
$('#follow').onchange=render;$('#seat-strip').onclick=e=>{const b=e.target.closest('[data-player]');if(b){selected=b.dataset.player;$('#follow').checked=false;render();}};
function renderModels(){const q=$('#model-search').value.toLowerCase(),filtered=models.filter(m=>(m.id+' '+m.name).toLowerCase().includes(q));$('#model-list').innerHTML=filtered.slice(0,80).map(m=>`<label class="model-option"><input type="checkbox" value="${esc(m.id)}" ${chosen.has(m.id)?'checked':''}><span>${esc(m.name)}<span class="small">${esc(m.id)} · $${(m.promptPrice*1e6).toFixed(2)} / $${(m.completionPrice*1e6).toFixed(2)}</span></span></label>`).join('')||'<p class="empty">No matching text models.</p>';$('#selected-models').textContent=`${chosen.size} selected: ${[...chosen].join(', ')||'none'}`;$('#catalog-status').textContent=catalogLoaded?`${models.length} text models in the current catalog${filtered.length>80?' · refine your search to see more':''}`:'Loading the current model catalog…';}
function modeChanged(){$('#model-settings').hidden=$('#mode').value==='demo';$('#start').textContent=$('#mode').value==='demo'?'Start bot demo':'Start model table';$('#start').disabled=$('#mode').value==='real'&&!state?.connected;}
$('#configure').onclick=async()=>{if(!state){$('#feedback').textContent='Wait for the runner connection first.';return;}$('#settings-error').textContent='';$('#operator-settings').hidden=!state.requiresAdmin;$('#mode').value=state.browserDemo?'demo':'real';$('#requests').value=state.limits.requestsPerDay;$('#budget').value=state.limits.usdPerDay;$('#pace').value=state.interval/1000;$('#usage-summary').textContent=`Today: ${state.usage.requests} API requests · $${state.usage.cost.toFixed(4)} tracked usage${state.usage.estimatedCost?' (includes $'+state.usage.estimatedCost.toFixed(4)+' in unreconciled reservations)':''}${state.usage.unknownCosts?' · cost missing for one or more responses':''}`;$('#key-status').innerHTML=state.browserDemo?'This free public page runs bots in your browser. Results are saved on this device. The full server and deployment instructions are in the GitHub repository. No model API calls are made.':state.connected?'OpenRouter key is configured on the server. Choose models and limits below.':'OpenRouter is not connected. Add your key to the server’s private <code>terms-apply/.env<br>OPENROUTER_API_KEY=your_key_here</code>Then restart with <code>npm start</code>Do not enter a key in the browser or commit this file.';$('#settings').showModal();chosen=new Set(state.mode==='real'?state.roster.map(m=>m.id):[]);modeChanged();renderModels();if(state.browserDemo){$('#mode').querySelector('option[value=real]').disabled=true;return;}try{const res=await apiFetch('/api/models'),data=await res.json();if(!res.ok||data.error)throw Error(data.error||'Catalog unavailable.');models=data.models;catalogLoaded=true;if(!chosen.size){for(const family of ['openai','anthropic','google','deepseek']){const options=models.filter(m=>m.family===family&&(family!=='google'||m.id.includes('gemini'))&&(family!=='openai'||(!m.id.includes('oss')&&!m.id.includes('audio')))).sort((a,b)=>(a.promptPrice+a.completionPrice)-(b.promptPrice+b.completionPrice));if(options[0])chosen.add(options[0].id);}}renderModels();}catch(e){$('#catalog-status').textContent=e.message;$('#model-list').innerHTML='';}};
$('#close-settings').onclick=()=>$('#settings').close();$('#mode').onchange=modeChanged;$('#model-search').oninput=renderModels;$('#model-list').onchange=e=>{if(e.target.type==='checkbox'){if(e.target.checked){if(chosen.size>=24){e.target.checked=false;$('#settings-error').textContent='Select at most 24 models.';return;}chosen.add(e.target.value);}else chosen.delete(e.target.value);renderModels();}};
$('#settings-form').onsubmit=async e=>{e.preventDefault();$('#start').disabled=true;try{await control({action:'configure',mode:$('#mode').value,models:[...chosen],requestsPerDay:Number($('#requests').value),usdPerDay:Number($('#budget').value),interval:Number($('#pace').value)*1000});$('#settings').close();$('#feedback').textContent='';}catch(e){$('#settings-error').textContent=e.message;}finally{modeChanged();}};
if(isBrowserDemo){$('#configure').textContent='Demo controls';$('#requests').parentElement.hidden=true;$('#budget').parentElement.hidden=true;$('#usage-summary').hidden=true;$('#settings-note').textContent='Starting a new game resets the current game. This demo makes no paid API calls.';document.querySelector('#records .section-heading p').textContent='Finished games and their moves are saved in this browser.';document.querySelector('#players .section-heading p').textContent='Scores from the demo bots on this device. Tied players share the win.';const exportAnchor=document.querySelector('a[href="/api/export"]');exportAnchor.href='#';exportAnchor.addEventListener('click',async e=>{e.preventDefault();const data=await (await apiFetch('/api/export')).json(),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='terms-apply-browser-record.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}
const stream=transport?transport.stream:new EventSource('/api/events');stream.onmessage=e=>{try{state=JSON.parse(e.data);connected=true;render();for(const id of recordCache.keys())showRecord(id);if($('#feedback').textContent==='Unable to read the latest table update.')$('#feedback').textContent='';}catch{$('#feedback').textContent='Unable to read the latest table update.';}};stream.onerror=()=>{connected=false;render();if(!state){$('#loading').textContent='The arena server is unavailable. Start it with npm start, then reload.';}};
