import {newsCards,playerProfiles} from './news.mjs';
import {brandAsset} from './brands.mjs';
import {mountParticipants} from './participants-ui.mjs';
import {mountLearning} from './learning-ui.mjs';
import {decisionPreview} from './learning.mjs';
import {browserDemo} from './browser-demo.mjs';
import {spaces,result,owned,netWorth,legalActions,rent,MAX_TURNS,finances,strategyInfo} from './game.mjs';
import {createBoard} from './board3d.mjs';
const $=s=>document.querySelector(s),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const isBrowserDemo=!!document.querySelector('meta[name="arena-runtime"][content="browser-demo"]')||new URLSearchParams(location.search).has('play');
const transport=isBrowserDemo?browserDemo():null;
const apiFetch=(path,options)=>transport?transport.request(path,options):fetch(path,options);
let state,selected=null,selectedSpace=null,connected=false,models=[],chosen=new Set(),catalogLoaded=false,board3d,stepping=false;
const token=(p,i)=>brandAsset(p.model.name)?`<span class="brand-mark"><img src="${brandAsset(p.model.name)}" alt="" width="32" height="32"></span>`:`<span class="token" style="--color:${esc(p.model.color)}">${p.model.human?'YOU':i+1}</span>`;
const shortName=p=>p.model.name.replace(/^[^:]+:\s*/,''),time=x=>new Date(x).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'}),money=x=>'$'+Math.round(x).toLocaleString();
function render(){if(!state)return;const focused=document.activeElement,focusPlayer=focused?.dataset?.player,focusSpace=focused?.dataset?.space,focusMove=focused?.dataset?.move,manageOpen=$('#turn-actions .manage-properties')?.open;const financeOpen=$('#money-breakdown .flow-detail')?.open,ledgerOpen=$('#money-breakdown .cash-ledger')?.open;const m=state.match,players=m.players,current=players[m.current],human=players.find(p=>p.model.human);$('#loading').hidden=true;$('#arena').hidden=false;
 const source=state.mode==='demo'?'Demo strategies · no model calls':'Connected AI models';$('#connection-label').textContent=!connected?'Reconnecting…':m.finishedAt?'Game finished':state.awaitingHuman?'Your turn':state.running?source:state.status==='paused'?'Game paused':'Game stopped';$('#connection-detail').textContent=state.running?(state.awaitingHuman?'The game is waiting for your move.':state.browserDemo?'Saved on this device.':'Players take turns automatically.'):state.message;$('#pause').textContent=state.running?'Pause':'Resume';$('#pause').disabled=!connected||state.thinking||(state.requiresAdmin&&!$('#operator-token').value);$('#status-dot').className='status-dot '+(state.running&&!m.finishedAt?'running':'');
 $('#step').hidden=state.mode!=='demo';$('#step').disabled=stepping||!connected||state.thinking||!!current.model.human||!!m.finishedAt;$('#playback-pace').value=String(state.interval>=2200?3000:state.interval>=1000?1500:600);$('#join').hidden=!!human;$('#leave').hidden=!human;$('#again').hidden=!m.finishedAt||(!transport&&!human);$('#join-note').textContent=human?'Your turn waits for you.':`${players.length} demo players · choose any mix.`;$('#join').disabled=!connected;
 $('#table-roster').textContent=players.map(p=>p.model.name).join(' · ');$('#match-number').textContent=m.id;$('#table-meta').textContent=m.finishedAt?'Finished':`${current.model.human?'Your':current.model.name+"’s"} turn · ${Math.min(MAX_TURNS,current.turns+1)} / ${MAX_TURNS}`;if($('#follow').checked||!players.some(p=>p.model.id===selected))selected=current.model.id;
 const p=players.find(p=>p.model.id===selected),properties=owned(m,p),f=finances(m,p),strategy=strategyInfo[p.model.strategy]||strategyInfo.careful;const who=id=>id==='bank'?'Bank':players.find(x=>x.model.id===id)?.model.name||id,category={rent:'Rent',purchase:'Property purchase',build:'House',sale:'Property sale',tax:'Compute tax',chance:'Chance',start:'Passing Start'};$('#strategy-label').textContent=p.model.human?'Human player':state.mode==='demo'?strategy.name+' · '+money(strategy.reserve)+' reserve · demo': 'Model decisions';
 if(!board3d){board3d=createBoard($('#board'),index=>{selectedSpace=index;$('#player-inspection').open=true;render();});if(matchMedia('(max-width: 520px)').matches)setBoardView('top');}board3d.update(m);board3d.setSelected(selectedSpace);$('#seat-strip').style.setProperty('--seats',players.length);$('#board').setAttribute('aria-label',`Property game board. Dice ${m.dice.join(' and ')}. ${players.map(p=>shortName(p)+' at '+spaces[p.position].name).join('. ')}`);
 $('#seat-strip').innerHTML=players.map((p,i)=>`<button class="seat seat-${i} ${m.current===i&&!m.finishedAt?'active':''}" style="--color:${esc(p.model.color)}" data-player="${esc(p.model.id)}" aria-pressed="${selected===p.model.id}">${token(p,i)}<span><strong>${esc(shortName(p))}</strong><span>${p.bankrupt?'Bankrupt':money(p.cash)+' cash'}</span><small>${esc(playerProfiles[p.model.name]?.role||'Your decisions')}</small></span></button>`).join('');
 $('#board-list').innerHTML=spaces.map((s,i)=>`<button data-space="${i}"><span>${i+1}. ${esc(s.name)}</span><small>${s.price?money(s.price)+' · '+esc(players.find(p=>p.model.id===m.properties[i].owner)?.model.name||'Available'):esc(s.kind)}</small></button>`).join('');const latest=m.events.findLast(e=>e.action.type!=='end')||m.events.at(-1);const latestText=latest?latest.outcome:'Everyone starts with $1,200. The first player is ready to roll.';if($('#latest-move').textContent!==latestText)$('#latest-move').textContent=latestText;$('#move-player').textContent=latest?.name||'';$('#lesson-summary').textContent=latest?.lesson?.title||'How cash becomes wealth';$('#move-reason').textContent=latest?.reason||'';$('#live-player').textContent=m.finishedAt?'Game complete':current.model.human?'Your turn':current.model.name+'’s turn';$('#live-dice').textContent=m.phase==='act'&&current.lastDice?'Dice '+current.lastDice.join(' + '):m.finishedAt?'':'Ready to roll';$('#live-task').textContent=m.finishedAt?'See the result above the board.':spaces[current.position].name+' · '+money(current.cash)+' cash';$('#live-avatar').innerHTML=token(current,m.current);const currentFlow=finances(m,current);$('#live-wallet').innerHTML=`<span>Received <b class="money-in">${money(currentFlow.income)}</b></span><span>Spent <b class="money-out">${money(currentFlow.out)}</b></span>`;document.querySelectorAll('.turn-track li').forEach(el=>el.setAttribute('aria-current',String(el.dataset.phase===m.phase)));$('#return-live').hidden=$('#follow').checked;
 $('#inspected-player').innerHTML=`<span class="player-name">${brandAsset(p.model.name)?`<span class="brand-mark"><img src="${brandAsset(p.model.name)}" alt="" width="32" height="32"></span>`:''}${esc(shortName(p))}</span>`;$('#turn-label').textContent=$('#follow').checked?'Following live player':'Inspecting player';$('#workspace-stats').innerHTML=`<p class="score"><strong>${money(p.cash)}</strong> cash</p><p class="turns">${properties.length} ${properties.length===1?'property':'properties'} · ${money(netWorth(m,p))} net worth${p.bankrupt?' · Bankrupt':''}</p><p class="dice-result">Dice: <strong>${p.lastDice?p.lastDice.join(' + '):'No roll yet'}</strong></p>`;

 $('#money-breakdown').innerHTML=`<div class="cash-equation"><span>${money(f.opening)}<small>${m.ledgerFromStart?'starting cash':'saved balance'}</small></span><b>+</b><span class="money-in">${money(f.income)}<small>money in</small></span><b>−</b><span class="money-out">${money(f.out)}<small>money out</small></span><b>=</b><span>${money(f.cash)}<small>cash now</small></span></div><details class="flow-detail" ${financeOpen?'open':''}><summary>Income &amp; spending breakdown</summary><div class="flow-columns"><div><h3>Money in</h3><dl><dt>Rent collected</dt><dd>${money(f.rentEarned)}</dd><dt>Passing Start</dt><dd>${money(f.start)}</dd><dt>Chance rewards</dt><dd>${money(f.chanceIn)}</dd><dt>Properties sold</dt><dd>${money(f.sales)}</dd></dl></div><div><h3>Money out</h3><dl><dt>Buying streets</dt><dd>${money(f.purchases)}</dd><dt>Building houses</dt><dd>${money(f.houses)}</dd><dt>Rent paid</dt><dd>${money(f.rentPaid)}</dd><dt>Tax / chance</dt><dd>${money(f.tax+f.chanceOut)}</dd></dl></div></div></details><p class="wealth-note">${money(f.cash)} cash + ${money(f.assets)} property value = ${money(netWorth(m,p))} net worth.</p><details class="cash-ledger" ${ledgerOpen?'open':''}><summary>${p.model.human?'Your':esc(p.model.name)+"’s"} recent payments</summary>${f.rows.length?f.rows.slice(-8).reverse().map(t=>`<p>${esc(who(t.from))} → ${esc(who(t.to))} <strong>${money(t.amount)}</strong><small>${esc(category[t.category])}${t.space!=null?' · '+esc(spaces[t.space].name):''}</small></p>`).join(''):'<p>No payments yet.</p>'}</details>`;
 const recent=latest?.transfers||[];$('#move-money').innerHTML=recent.length?recent.map(t=>`<p class="transfer-line"><strong>${esc(who(t.from))}</strong> → <strong>${esc(who(t.to))}</strong> <b>${money(t.amount)}</b><span>${esc(category[t.category])}</span></p>`).join(''):'<p class="no-transfer">No money moved on this action.</p>';
 $('#move-lesson').innerHTML=latest?.lesson?`<h4>${esc(latest.lesson.title)}</h4><p>${esc(latest.lesson.text)}</p>`:'<h4>Cash and wealth are different</h4><p>A street uses cash now. Its purchase value remains part of net worth, but rent is earned only when a visitor arrives.</p>';
 $('#money-table').innerHTML=players.map(x=>{const flow=finances(m,x);return `<tr><th scope="row"><button data-player="${esc(x.model.id)}">${esc(x.model.name)}</button><small>${esc(x.model.human?'You':(state.mode==='demo'?(strategyInfo[x.model.strategy]||strategyInfo.careful).name:'Model decisions'))}</small></th><td>${money(x.cash)}</td><td class="money-in">+${money(flow.income)}</td><td class="money-out">−${money(flow.out)}</td><td>${money(flow.assets)}</td><td>${money(netWorth(m,x))}</td></tr>`;}).join('');
 renderPlayerStory(p,m);const preview=decisionPreview(m,current);$('#decision-coach').innerHTML=preview?`<div class="decision-coach"><h3>Before ${current.model.human?'you decide':esc(current.model.name)+' decides'}</h3><p>${esc(preview.name)} · ${money(preview.price)} price · ${money(preview.rent)} base rent.</p><dl><dt>Buy ${preview.affordable?'':'(not enough cash)'}</dt><dd>${preview.affordable?money(preview.buyCash)+' cash left':'Unavailable'}</dd><dt>Keep the cash</dt><dd>${money(preview.keepCash)} available</dd></dl><p>Net worth if bought: ${money(preview.worth)}. Rent needs visitors. Keep cash for bills.</p></div>`:'';
 const available=legalActions(m),labels=a=>a.type==='roll'?(current.jail?'Serve timeout turn':'Roll dice'):a.type==='buy'?`Buy for ${money(spaces[a.space].price)}`:a.type==='end'?'End turn':a.type==='build'?`Build on ${spaces[a.space].name} · $100`:`Sell ${spaces[a.space].name} · ${money((spaces[a.space].price+m.properties[a.space].houses*100)/2)}`;
 $('#turn-actions').innerHTML=m.finishedAt?'<p class="turn-prompt">Game over. The highest net worth wins.</p>':human&&current===human&&!human.bankrupt?`<p class="turn-prompt">${!state.running?'Game paused. Resume to take your turn.':m.phase==='roll'?'Your turn. Roll the dice to move.':'Choose a move, then end your turn.'}</p><div class="move-buttons">${available.filter(a=>!['build','sell'].includes(a.type)).sort((a,b)=>({roll:0,buy:1,end:2}[a.type]-{roll:0,buy:1,end:2}[b.type])).map((a,i)=>`<button class="${i===0?'primary':''}" data-move="${esc(JSON.stringify(a))}" ${!state.running?'disabled':''}>${esc(labels(a))}</button>`).join('')}</div>${available.some(a=>['build','sell'].includes(a.type))?`<details class="manage-properties" ${manageOpen?'open':''}><summary>Build houses or sell properties</summary>${available.filter(a=>['build','sell'].includes(a.type)).map(a=>`<button data-move="${esc(JSON.stringify(a))}" ${!state.running?'disabled':''}>${esc(labels(a))}</button>`).join('')}</details>`:''}`:human?`<p class="turn-prompt">${human.bankrupt?'You are out of this game. Watch the remaining players.':`Waiting for ${esc(current.model.name)}. Your controls appear when the dice reach you.`}</p>`:`<p class="turn-prompt">${m.phase==='roll'?'Next: roll the dice.':preview?'Next decision: buy or keep the cash.':'Next: pass the dice.'}</p>`;
 const i=selectedSpace??p.position,square=spaces[i],lot=m.properties[i],owner=players.find(p=>p.model.id===lot.owner);
 $('#workspace-tasks').innerHTML=`<div class="current-job"><h3>${selectedSpace===null?'Current square':'Selected square'}</h3><h4>${esc(square.name)}</h4>${square.kind==='property'?`<p>Price ${money(square.price)} · Rent ${money(rent(m,i))}</p><p class="property-math">Cost ÷ rent ≈ ${Math.ceil((square.price+lot.houses*100)/rent(m,i))} paid visits. Visits aren’t guaranteed.</p><p>Rent collected here by ${owner?esc(owner.model.name):'an owner'}: <strong>${money((m.ledger||[]).filter(t=>t.category==='rent'&&t.space===i&&t.to===owner?.model.id).reduce((n,t)=>n+t.amount,0))}</strong></p><p class="property-owner">${owner?'Owned by '+esc(owner.model.name)+(lot.houses?' · '+lot.houses+' houses':''):'Available to buy when you land here.'}</p>`:`<p>${{start:'Collect $200 every time you pass Start.',chance:'Draw a card. You might gain cash or pay an unexpected bill.',tax:'Pay $80 to the bank.',jail:'Just visiting. A player sent here skips their next turn.',parking:'A free square. Nothing to pay.',timeout:'Move to timeout and skip your next turn.'}[square.kind]}</p>`}${selectedSpace!==null?'<button id="clear-space">Follow current square</button>':''}</div>`;
 $('#workspace-terms').innerHTML=properties.length?properties.map(i=>`<button class="property-row" data-space="${i}"><span class="property-swatch" style="background:${spaces[i].color}"></span><span>${esc(spaces[i].name)}</span><strong>${money(rent(m,i))} rent${m.properties[i].houses?' · '+m.properties[i].houses+' houses':''}</strong></button>`).join(''):'<p>No properties yet. Buy one when you land on it.</p>';
 $('#event-count').textContent=m.tick+' moves';const log=$('#event-log'),scroll=log.scrollTop;log.innerHTML=m.events.slice(-40).reverse().map(e=>`<div class="event"><time>${time(e.time)}</time><strong>${esc(e.name)}</strong><details><summary>${esc(e.outcome)}</summary><p>${esc(e.reason)}</p></details></div>`).join('')||'<p>No moves yet.</p>';log.scrollTop=scroll;
 const rows=Object.values(state.totals).filter(t=>t.mode===state.mode).sort((a,b)=>b.wins-a.wins);$('#results-caption').textContent=source;$('#results').innerHTML=rows.length?rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${r.games}</td><td>${r.wins}</td><td>${money((r.wealth||0)/r.games)}</td><td>${((r.properties||0)/r.games).toFixed(1)}</td><td>${r.rejected}</td></tr>`).join(''):'<tr><td colspan="6">Scores appear after the first game.</td></tr>';
 const openHistory=new Set([...$('#history').querySelectorAll('details[open]')].map(d=>d.dataset.match));$('#history').innerHTML=state.history.filter(h=>h.mode===state.mode).slice(0,15).map(h=>`<details class="history-item" data-match="${h.id}" ${openHistory.has(String(h.id))?'open':''}><summary>Game ${h.id} · ${esc(h.rows.filter(r=>h.winners.includes(r.id)).map(r=>r.name).join(' + '))} won</summary><p>${h.rows.map(r=>esc(r.name)+': '+money(r.netWorth)+' net worth').join('<br>')}</p><button data-record="${h.id}">Read moves</button><div id="record-${h.id}"></div></details>`).join('')||'<p>No finished games yet.</p>';
 $('#game-result').hidden=!m.finishedAt;if(m.finishedAt){const r=result(m);$('#game-result').innerHTML=`<div><small>Game ${m.id} complete</small><h2>${esc(r.rows.filter(p=>r.winners.includes(p.id)).map(p=>p.name).join(' + '))} ${r.winners.length>1?'win':'wins'}</h2><p>${money(r.rows[0].netWorth)} net worth · cash plus property value</p></div><p>${r.rows.map(p=>esc(p.name)+' '+money(p.netWorth)).join(' · ')}</p>`;}
if(focusPlayer||focusSpace||focusMove){const replacement=[...document.querySelectorAll('[data-player],[data-space],[data-move]')].find(el=>focusPlayer?el.dataset.player===focusPlayer:focusSpace?el.dataset.space===focusSpace:el.dataset.move===focusMove);replacement?.focus({preventScroll:true});}
}
async function control(payload){const r=await apiFetch('/api/control',{method:'POST',headers:{'Content-Type':'application/json',...(state?.requiresAdmin?{'X-Admin-Token':$('#operator-token').value}:{})},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok)throw Error(b.error||'Runner control failed.');return b;}
$('#pause').onclick=async()=>{const b=$('#pause');b.disabled=true;try{await control({action:state.running?'pause':'resume'});$('#feedback').textContent='';}catch(e){$('#feedback').textContent=e.message;}finally{render();}};
const recordCache=new Map();$('#history').onclick=async e=>{const b=e.target.closest('[data-record]');if(!b)return;const id=b.dataset.record;b.disabled=true;try{if(!recordCache.has(id)){const r=await apiFetch('/api/matches/'+id);const data=await r.json();if(!r.ok)throw Error(data.error);recordCache.set(id,data);}showRecord(id);}catch(err){b.textContent=err.message;b.disabled=false;}};
function showRecord(id){const el=$('#record-'+id),record=recordCache.get(String(id));if(!el||!record)return;el.innerHTML='<div class="event-log">'+record.match.events.map(e=>`<div class="event"><time>${time(e.time)}</time><span>${esc(e.name)}</span><details><summary>${esc(e.outcome)}</summary><p>${esc(e.reason)}</p><code>${esc(JSON.stringify(e.action))}</code></details></div>`).join('')+'</div>';const b=document.querySelector(`[data-record="${id}"]`);if(b){b.textContent='Transcript loaded';b.disabled=true;}}
$('#follow').onchange=()=>{selectedSpace=null;render();};$('#return-live').onclick=()=>{$('#follow').checked=true;selectedSpace=null;render();};$('#seat-strip').onclick=e=>{const b=e.target.closest('[data-player]');if(b){selected=b.dataset.player;$('#follow').checked=false;$('#player-inspection').open=true;render();}};
$('#step').onclick=async()=>{stepping=true;render();try{if(state.running)await control({action:'pause'});await control({action:'step'});$('#feedback').textContent='';}catch(e){$('#feedback').textContent=e.message;}finally{stepping=false;render();}};$('#playback-pace').onchange=async()=>{try{await control({action:'pace',interval:Number($('#playback-pace').value)});}catch(e){$('#feedback').textContent=e.message;}};$('#money-table').onclick=e=>{const b=e.target.closest('[data-player]');if(b){selected=b.dataset.player;$('#follow').checked=false;$('#player-inspection').open=true;render();}};
function renderModels(){const q=$('#model-search').value.toLowerCase(),filtered=models.filter(m=>(m.id+' '+m.name).toLowerCase().includes(q));$('#model-list').innerHTML=filtered.slice(0,80).map(m=>`<label class="model-option"><input type="checkbox" value="${esc(m.id)}" ${chosen.has(m.id)?'checked':''}><span>${esc(m.name)}<span class="small">${esc(m.id)} · $${(m.promptPrice*1e6).toFixed(2)} / $${(m.completionPrice*1e6).toFixed(2)}</span></span></label>`).join('')||'<p class="empty">No matching text models.</p>';$('#selected-models').textContent=`${chosen.size} selected: ${[...chosen].join(', ')||'none'}`;$('#catalog-status').textContent=catalogLoaded?`${models.length} text models in the current catalog${filtered.length>80?' · refine your search to see more':''}`:'Loading the current model catalog…';}
function modeChanged(){$('#model-settings').hidden=$('#mode').value==='demo';$('#start').textContent=$('#mode').value==='demo'?'Start bot demo':'Start model table';$('#start').disabled=$('#mode').value==='real'&&!state?.connected;}
$('#configure').onclick=async()=>{if(!state){$('#feedback').textContent='Wait for the runner connection first.';return;}$('#settings-error').textContent='';$('#operator-settings').hidden=!state.requiresAdmin;$('#mode').value=state.browserDemo?'demo':'real';$('#requests').value=state.limits.requestsPerDay;$('#budget').value=state.limits.usdPerDay;$('#pace').value=state.interval/1000;$('#usage-summary').textContent=`Today: ${state.usage.requests} API requests · $${state.usage.cost.toFixed(4)} tracked usage${state.usage.estimatedCost?' (includes $'+state.usage.estimatedCost.toFixed(4)+' in unreconciled reservations)':''}${state.usage.unknownCosts?' · cost missing for one or more responses':''}`;$('#key-status').innerHTML=state.browserDemo?'This free public page runs bots in your browser. Results are saved on this device. The full server and deployment instructions are in the GitHub repository. No model API calls are made.':state.connected?'OpenRouter key is configured on the server. Choose models and limits below.':'OpenRouter is not connected. Add your key to the server’s private <code>terms-apply/.env<br>OPENROUTER_API_KEY=your_key_here</code>Then restart with <code>npm start</code>Do not enter a key in the browser or commit this file.';$('#settings').showModal();chosen=new Set(state.mode==='real'?state.roster.map(m=>m.id):[]);modeChanged();renderModels();if(state.browserDemo){$('#mode').querySelector('option[value=real]').disabled=true;return;}try{const res=await apiFetch('/api/models'),data=await res.json();if(!res.ok||data.error)throw Error(data.error||'Catalog unavailable.');models=data.models;catalogLoaded=true;if(!chosen.size){for(const family of ['openai','anthropic','google','deepseek']){const options=models.filter(m=>m.family===family&&(family!=='google'||m.id.includes('gemini'))&&(family!=='openai'||(!m.id.includes('oss')&&!m.id.includes('audio')))).sort((a,b)=>(a.promptPrice+a.completionPrice)-(b.promptPrice+b.completionPrice));if(options[0])chosen.add(options[0].id);}}renderModels();}catch(e){$('#catalog-status').textContent=e.message;$('#model-list').innerHTML='';}};
$('#close-settings').onclick=()=>$('#settings').close();$('#mode').onchange=modeChanged;$('#model-search').oninput=renderModels;$('#model-list').onchange=e=>{if(e.target.type==='checkbox'){if(e.target.checked){if(chosen.size>=24){e.target.checked=false;$('#settings-error').textContent='Select at most 24 models.';return;}chosen.add(e.target.value);}else chosen.delete(e.target.value);renderModels();}};
$('#settings-form').onsubmit=async e=>{e.preventDefault();$('#start').disabled=true;try{await control({action:'configure',mode:$('#mode').value,models:[...chosen],requestsPerDay:Number($('#requests').value),usdPerDay:Number($('#budget').value),interval:Number($('#pace').value)*1000});$('#settings').close();$('#feedback').textContent='';}catch(e){$('#settings-error').textContent=e.message;}finally{modeChanged();}};
if(isBrowserDemo){$('#configure').textContent='Demo controls';$('#requests').parentElement.hidden=true;$('#budget').parentElement.hidden=true;$('#usage-summary').hidden=true;$('#settings-note').textContent='Starting a new game resets the current game. This demo makes no paid API calls.';document.querySelector('#records .section-heading p').textContent='Finished games and their moves are saved in this browser.';document.querySelector('#players .section-heading p').textContent='Scores from the demo bots on this device. Tied players share the win.';const exportAnchor=document.querySelector('a[href="/api/export"]');exportAnchor.href='#';exportAnchor.addEventListener('click',async e=>{e.preventDefault();const data=await (await apiFetch('/api/export')).json(),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='terms-apply-browser-record.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}
const stream=transport?transport.stream:new EventSource('/api/events');stream.onmessage=e=>{try{state=JSON.parse(e.data);connected=true;render();for(const id of recordCache.keys())showRecord(id);if($('#feedback').textContent==='Unable to read the latest table update.')$('#feedback').textContent='';}catch{$('#feedback').textContent='Unable to read the latest table update.';}};stream.onerror=()=>{connected=false;render();if(!state){$('#loading').textContent='The arena server is unavailable. Start it with npm start, then reload.';}};

async function humanControl(action){try{selectedSpace=null;if(['join','leave','again'].includes(action)){selected=null;$('#follow').checked=true;$('#player-inspection').open=false;}await control({action});$('#feedback').textContent='';}catch(e){$('#feedback').textContent=e.message;}}
$('#join').onclick=()=>{if(!transport){location.href='?play=1#live';return;}humanControl('join');};
$('#leave').onclick=()=>humanControl('leave');$('#again').onclick=()=>humanControl('again');
$('#turn-actions').onclick=async e=>{const button=e.target.closest('[data-move]');if(!button)return;button.disabled=true;try{await control({action:'move',move:JSON.parse(button.dataset.move)});selectedSpace=null;$('#feedback').textContent='';}catch(err){$('#feedback').textContent=err.message;}finally{render();}};
$('#workspace-tasks').onclick=e=>{if(e.target.id==='clear-space'){selectedSpace=null;render();}};
$('#workspace-terms').onclick=e=>{const button=e.target.closest('[data-space]');if(button){selectedSpace=Number(button.dataset.space);$('#player-inspection').open=true;render();}};
const launch=new URLSearchParams(location.search);if(launch.has('play')){if(launch.has('players'))control({action:'participants',players:launch.get('players').split(','),includeHuman:launch.get('human')!=='0'}).catch(e=>$('#feedback').textContent=e.message);else humanControl('join');}

$('#board-list').onclick=e=>{const button=e.target.closest('[data-space]');if(button){selectedSpace=Number(button.dataset.space);$('#player-inspection').open=true;render();}};

let learningWasRunning=false;mountLearning({onOpen:async()=>{learningWasRunning=!!state?.running;if(state?.mode==='demo'&&state.running)await control({action:'pause'});},onClose:async()=>{if(learningWasRunning&&state?.mode==='demo')try{await control({action:'resume'});}catch(e){$('#feedback').textContent=e.message;}}});

mountParticipants({getState:()=>state,start:async(players,includeHuman)=>{if(!transport&&includeHuman){location.href='?'+new URLSearchParams({play:'1',players:players.join(','),human:'1'})+'#live';return;}selected=null;selectedSpace=null;$('#follow').checked=true;$('#player-inspection').open=false;await control({action:'participants',players,includeHuman});$('#feedback').textContent='';}});

function setBoardView(view){board3d?.setView(view);$('#angled-view').setAttribute('aria-pressed',String(view==='angled'));$('#top-view').setAttribute('aria-pressed',String(view==='top'));}$('#angled-view').onclick=()=>setBoardView('angled');$('#top-view').onclick=()=>setBoardView('top');

const phoneLayout=matchMedia('(max-width: 800px)');function arrangeTurnControls(){const panel=$('.live-decision'),move=$('.current-move');if(phoneLayout.matches){$('.board-panel').insertBefore(panel,$('.board-views'));$('.board-panel').insertBefore(move,$('.board-index'));}else{$('.workbench').prepend(panel);panel.after(move);}}phoneLayout.addEventListener('change',arrangeTurnControls);arrangeTurnControls();

function storyHTML(card,compact=false){return `<div class="story-meta">${esc(card.publisher)} · <time datetime="${card.date}">${esc(card.date)}</time></div><h3>${esc(card.title)}</h3><p>${esc(card.fact)}</p>${compact?'':`<p>${esc(card.lesson)}</p><p class="story-effect"><strong>Fictional game effect: ${card.amount>0?'+':'−'}${money(Math.abs(card.amount))}</strong><br>${esc(card.effect)}</p>`}<a href="${esc(card.url)}" target="_blank" rel="noopener">Read the source</a>`;}
function renderPlayerStory(p,m){const profile=playerProfiles[p.model.name];$('#profile-summary').textContent=selectedSpace===null?'Inspect '+p.model.name:'Inspect '+spaces[selectedSpace].name;$('#player-profile').innerHTML=profile?`<h3>${esc(profile.role)}</h3><p>${esc(profile.plan)}</p><dl><dt>Advantage</dt><dd>${esc(profile.strength)}</dd><dt>Tradeoff</dt><dd>${esc(profile.risk)}</dd></dl><p class="small">${esc(profile.piece)} on the board · authored demo role</p>`:'<p>You choose the strategy. Roll, buy or pass, then end your turn.</p>';const drawn=m.lastNews,card=drawn||newsCards.find(c=>c.player===p.model.name)||newsCards[0];$('#news-spotlight').innerHTML=`<h2>${drawn?'News card drawn by '+esc(drawn.drawnBy):'In the news: '+esc(card.player)}</h2>${storyHTML(card,true)}${drawn?`<p class="story-effect">Fictional game effect: ${card.amount>0?'+':'−'}${money(Math.abs(card.amount))} to ${esc(drawn.drawnBy)}</p>`:`<p class="small">${m.newsDeck?'News squares draw these stories. Effects are fictional.':'News cards enter the next game. Choose Players to start a fresh table.'}</p>`}`;}
$('#news-list').innerHTML=newsCards.map(card=>`<article class="news-article"><div class="news-player">${brandAsset(card.player)?`<img src="${brandAsset(card.player)}" alt="" width="32" height="32">`:''}<strong>${esc(card.player)}</strong></div><div>${storyHTML(card)}</div></article>`).join('');function showNews(open){$('#news-desk').hidden=!open;$('#live').classList.toggle('news-view',open);$('#news-toggle').setAttribute('aria-expanded',String(open));if(open){$('#news-title').scrollIntoView({block:'start'});$('#news-title').focus({preventScroll:true});}else{$('#live').scrollIntoView({block:'start'});$('#news-toggle').focus({preventScroll:true});}}$('#news-toggle').onclick=()=>showNews($('#news-desk').hidden);$('#news-back').onclick=()=>showNews(false);
