export const demoRoster=[{id:'demo/claude',name:'Claude',family:'Demo persona',color:'#b76444',strategy:'careful'},{id:'demo/gemini',name:'Gemini',family:'Demo persona',color:'#417a69',strategy:'fast'},{id:'demo/codex',name:'Codex',family:'Demo persona',color:'#7a68a0',strategy:'planner'},{id:'demo/grok',name:'Grok',family:'Demo persona',color:'#536d82',strategy:'fast'},{id:'demo/deepseek',name:'DeepSeek',family:'Demo persona',color:'#8e762b',strategy:'minimal'}];
export const humanPlayer={id:'human/you',name:'You',family:'Human',color:'#283d32',human:true};
const property=(name,group,color,price,rent)=>({name,kind:'property',group,color,price,rent});
export const spaces=[{name:'Start',kind:'start'},property('Prompt Place','mint','#51816e',120,20),property('Context Court','mint','#51816e',140,25),{name:'Chance',kind:'chance'},property('Model Market','gold','#b39748',160,30),{name:'Just visiting',kind:'jail'},property('Token Terrace','gold','#b39748',180,35),{name:'Compute tax',kind:'tax',cost:80},property('Agent Avenue','blue','#668ba2',200,40),property('Memory Lane','blue','#668ba2',220,45),{name:'Free parking',kind:'parking'},property('Reasoning Road','violet','#8a789a',240,50),property('Inference Square','violet','#8a789a',260,55),{name:'Chance',kind:'chance'},property('Training Tower','clay','#bf8867',280,60),{name:'Go to timeout',kind:'timeout'},property('Data Drive','clay','#bf8867',300,65),{name:'Chance',kind:'chance'},property('Evaluation Estate','red','#a66055',320,70),property('Alignment Arcade','red','#a66055',340,75)];
export const MAX_TURNS=20,BUILD_COST=100;
export const active=m=>m.players[m.current];
export const owned=(m,p)=>m.properties.flatMap((lot,i)=>lot.owner===p.model.id?[i]:[]);
export const netWorth=(m,p)=>p.bankrupt?0:p.cash+owned(m,p).reduce((sum,i)=>sum+spaces[i].price+m.properties[i].houses*BUILD_COST,0);
export const completeGroup=(m,p,index)=>spaces.filter(s=>s.group&&s.group===spaces[index].group).every(s=>m.properties[spaces.indexOf(s)].owner===p.model.id);
export const rent=(m,index)=>{const lot=m.properties[index],owner=m.players.find(p=>p.model.id===lot.owner);return spaces[index].rent*(1+lot.houses*2)*(owner&&completeGroup(m,owner,index)?2:1);};
export function startMatch(roster,number=1,seed=12345){return {edition:'property',id:number,seed,rng:seed>>>0,startedAt:new Date().toISOString(),finishedAt:null,current:0,tick:0,phase:'roll',dice:[1,1],lastRoll:null,landing:null,turnActions:0,events:[],properties:spaces.map(()=>({owner:null,houses:0})),players:roster.map(model=>({model,cash:1200,position:0,turns:0,jail:0,bankrupt:false,moves:0,rejected:0,incorrect:0,requests:0,latency:null,lastReason:'Ready to play.'}))};}
export function legalActions(m,p=active(m)){if(m.finishedAt||p!==active(m)||p.bankrupt)return [];if(m.phase==='roll')return [{type:'roll'}];const actions=[{type:'end'}];const index=p.position,s=spaces[index],lot=m.properties[index];if(s.kind==='property'&&!lot.owner&&p.cash>=s.price)actions.push({type:'buy',space:index});if(m.turnActions<8){for(const i of owned(m,p)){if(completeGroup(m,p,i)&&m.properties[i].houses<3&&p.cash>=BUILD_COST)actions.push({type:'build',space:i});actions.push({type:'sell',space:i});}}return actions;}
function random(m,n){m.rng=(Math.imul(m.rng,1664525)+1013904223)>>>0;return Math.floor(m.rng/4294967296*n);}
function settle(m,p,amount,recipient=null){let liquidation='';if(p.cash<amount){for(const i of owned(m,p).sort((a,b)=>spaces[a].price-spaces[b].price)){p.cash+=Math.floor((spaces[i].price+m.properties[i].houses*BUILD_COST)/2);m.properties[i]={owner:null,houses:0};liquidation+=`${spaces[i].name} sold to the bank. `;if(p.cash>=amount)break;}}const paid=Math.min(p.cash,amount);p.cash-=paid;if(recipient)recipient.cash+=paid;if(paid<amount){p.bankrupt=true;for(const i of owned(m,p))m.properties[i]={owner:null,houses:0};liquidation+='Bankrupt and out of this game. ';}return {paid,liquidation};}
function finishTurn(m){const p=active(m);p.turns++;m.turnActions=0;const eligible=m.players.map((p,i)=>!p.bankrupt&&p.turns<MAX_TURNS?i:-1).filter(i=>i>=0);if(eligible.length===0||m.players.filter(p=>!p.bankrupt).length===1){m.finishedAt=new Date().toISOString();m.phase='finished';return;}do{m.current=(m.current+1)%m.players.length;}while(!eligible.includes(m.current));m.phase='roll';m.landing=null;}
function landed(m,p){const s=spaces[p.position],lot=m.properties[p.position];m.landing=p.position;if(s.kind==='property'){if(lot.owner&&lot.owner!==p.model.id){const owner=m.players.find(x=>x.model.id===lot.owner),amount=rent(m,p.position),payment=settle(m,p,amount,owner);return `Landed on ${s.name}. Paid $${payment.paid} rent to ${owner.model.name}. ${payment.liquidation}`;}return lot.owner?`Landed on their own ${s.name}.`:`Landed on ${s.name}. Available for $${s.price}; rent starts at $${s.rent}.`;}
if(s.kind==='tax'){const payment=settle(m,p,s.cost);return `Paid $${payment.paid} compute tax. ${payment.liquidation}`;}
if(s.kind==='timeout'){p.position=5;p.jail=1;return 'Sent to timeout. Their next turn will be skipped.';}
if(s.kind==='chance'){const cards=[{text:'A useful release earned $100.',amount:100},{text:'A server repair costs $60.',amount:-60},{text:'An open-source grant earned $150.',amount:150},{text:'A surprise audit costs $90.',amount:-90}];const card=cards[random(m,cards.length)];if(card.amount>0)p.cash+=card.amount;else{const payment=settle(m,p,-card.amount);return `Chance: ${card.text} ${payment.liquidation}`;}return `Chance: ${card.text}`;}
return s.kind==='start'?'Landed on Start.':s.kind==='parking'?'Free parking. Take a breather.':'Just visiting timeout. No penalty.';}
export function applyMove(match,action,reason=''){if(match.finishedAt)return structuredClone(match);const m=structuredClone(match),p=active(m);const valid=legalActions(m).some(a=>Object.keys(a).length===Object.keys(action).length&&Object.entries(a).every(([k,v])=>action[k]===v));let outcome,rejected=false,close=false;const turn=p.turns+1;
if(!valid){p.rejected++;rejected=true;outcome='That move is not available. The turn ended.';close=true;}else if(action.type==='roll'){if(p.jail){p.jail=0;outcome='Sat out a timeout turn. Ready to roll next turn.';close=true;}else{m.dice=[random(m,6)+1,random(m,6)+1];m.lastRoll={player:p.model.id,dice:[...m.dice],tick:m.tick+1};const sum=m.dice[0]+m.dice[1],before=p.position;p.position=(before+sum)%spaces.length;const passed=before+sum>=spaces.length;if(passed)p.cash+=200;m.phase='act';outcome=`Rolled ${m.dice.join(' + ')}. ${passed?'Passed Start and collected $200. ':''}${landed(m,p)}`;if(p.bankrupt)close=true;}}
else if(action.type==='buy'){const s=spaces[action.space];p.cash-=s.price;m.properties[action.space].owner=p.model.id;outcome=`Bought ${s.name} for $${s.price}. Visitors now pay rent.`;}
else if(action.type==='build'){p.cash-=BUILD_COST;m.properties[action.space].houses++;outcome=`Built a house on ${spaces[action.space].name} for $100. Rent is now $${rent(m,action.space)}.`;}
else if(action.type==='sell'){const lot=m.properties[action.space],value=Math.floor((spaces[action.space].price+lot.houses*BUILD_COST)/2);p.cash+=value;m.properties[action.space]={owner:null,houses:0};outcome=`Sold ${spaces[action.space].name} back to the bank for $${value}.`;}
else{outcome='Ended the turn.';close=true;}
p.moves++;m.turnActions++;p.lastReason=String(reason).slice(0,500);m.events.push({id:++m.tick,time:new Date().toISOString(),player:p.model.id,name:p.model.name,round:turn,action,reason:p.lastReason,outcome,rejected});m.events=m.events.slice(-600);if(close||m.turnActions>=10)finishTurn(m);return m;}
export function observation(m,p){return {rules:'Terms Apply is an original property board game. Everyone starts with $1200. Roll two dice, then buy the unowned property you land on or end your turn. Rent is paid automatically on arrival. Passing Start earns $200. Owning both properties of a color doubles rent and unlocks houses at $100 each, maximum three per property. Rent is base rent times (1 + 2 * houses) times color-set bonus. Sell properties to the bank for half their purchase and house costs. Tax and chance cards change cash. Timeout skips the next turn. If you cannot pay, properties are sold automatically; remaining debt means bankruptcy. After 20 turns per player, highest net worth (cash + original property prices + house costs) wins. Last solvent player wins early. No extra turns for doubles. Up to ten actions per turn.',you:{id:p.model.id,cash:p.cash,position:p.position,turn:p.turns+1,properties:owned(m,p),netWorth:netWorth(m,p)},players:m.players.map(x=>({id:x.model.id,name:x.model.name,cash:x.cash,position:x.position,bankrupt:x.bankrupt})),board:spaces.map((s,i)=>({...s,index:i,...m.properties[i],currentRent:s.kind==='property'?rent(m,i):0})),legalActions:legalActions(m,p),previousEvents:m.events.slice(-8).map(e=>({player:e.name,action:e.action,outcome:e.outcome}))};}
export function botMove(m,p){const actions=legalActions(m,p),roll=actions.find(a=>a.type==='roll');if(roll)return {action:roll,reason:'Roll the dice and see where I land.'};const buy=actions.find(a=>a.type==='buy');if(buy&&(p.model.strategy!=='minimal'||p.cash>500))return {action:buy,reason:'Own a property and collect rent when another player lands here.'};const build=actions.find(a=>a.type==='build');if(build&&p.cash>(p.model.strategy==='fast'?180:400))return {action:build,reason:'Build on a complete color set to increase rent.'};return {action:{type:'end'},reason:'Keep the remaining cash and pass the dice.'};}
export function result(m){const rows=m.players.map(p=>({id:p.model.id,name:p.model.name,netWorth:netWorth(m,p),cash:p.cash,properties:owned(m,p).length,bankrupt:p.bankrupt,moves:p.moves,tasks:owned(m,p).length,open:0,incorrect:0,rejected:p.rejected,success:!p.bankrupt})).sort((a,b)=>b.netWorth-a.netWorth);const best=rows[0];return {id:m.id,seed:m.seed,startedAt:m.startedAt,finishedAt:m.finishedAt,rows,winners:rows.filter(r=>r.netWorth===best.netWorth).map(r=>r.id)};}
