import {tasks as originals,services,spaces} from '../content.mjs';
export {services,spaces};
export const tasks=originals.map(t=>({...t,work:2}));
export const active=g=>g.players[0];
export const completed=g=>g.taskState.filter(t=>t.done).length;
export const demoRoster=[{id:'demo/claude',name:'Claude',family:'Demo persona',color:'#b76444',strategy:'careful'},{id:'demo/gemini',name:'Gemini',family:'Demo persona',color:'#417a69',strategy:'fast'},{id:'demo/codex',name:'Codex',family:'Demo persona',color:'#7a68a0',strategy:'planner'},{id:'demo/grok',name:'Grok',family:'Demo persona',color:'#536d82',strategy:'fast'},{id:'demo/deepseek',name:'DeepSeek',family:'Demo persona',color:'#8e762b',strategy:'minimal'}];
export function startMatch(roster,number=1,seed=12345){let v=seed>>>0;const dice=Array.from({length:12},()=>{v=(Math.imul(v,1664525)+1013904223)>>>0;return 1+v%3;});return {edition:'simple',id:number,seed,dice,startedAt:new Date().toISOString(),finishedAt:null,current:0,tick:0,events:[],players:roster.map(model=>({model,game:{phase:'act',round:1,players:[{name:model.name,time:12,position:0}],taskState:tasks.map(t=>({id:t.id,work:0,read:[],done:false})),pending:[],owned:[],used:[],notice:'Ready to play.'},moves:0,turnMoves:0,rejected:0,incorrect:0,usedTime:0,requests:0,latency:null,lastReason:'Waiting for a turn.'}))};}
export function legalActions(g){if(g.phase==='finished')return [];const actions=[];for(const t of g.taskState){if(t.done)continue;if(t.work<2)actions.push({type:'work',task:t.id},{type:'use',service:'writing',task:t.id});if(t.read.length<2)actions.push({type:'source',task:t.id});if(t.work>=2&&t.read.length===2)for(const verdict of ['accept','revise','unknown'])actions.push({type:'submit',task:t.id,verdict});}return actions.length?actions:[{type:'end'}];}
export function observation(match,p){const g=p.game;return {rules:'You have 12 moves to finish at least 3 jobs. Each move costs one turn. Prepare an answer: work adds 1 of the 2 required preparation points, or use writing help to prepare both at once. Check the facts: source reveals both source statements and clears the helper review. Decide: submit accept (right), revise (wrong), or unknown (not enough information). You must prepare and check before deciding. A correct decision finishes the job. A wrong decision costs a turn and leaves it unfinished. Most finished jobs wins, then fewer mistakes. Everyone gets the same movement rolls; board squares are visual landmarks and have no extra rules.',movesLeft:active(g).time,tasks:g.taskState.map(t=>{const d=tasks.find(x=>x.id===t.id);return {...t,title:d.title,question:d.question,claim:d.claim,requiredWork:2,sources:d.sources.map((s,index)=>({index,title:s[0],text:t.read.includes(index)?s[1]:'Inspect this source to reveal it.'}))};}),previousEvents:match.events.filter(e=>e.player===p.model.id).slice(-6).map(e=>({action:e.action,outcome:e.outcome})),legalActions:legalActions(g)};}
export function applyMove(match,action,reason=''){if(match.finishedAt)return structuredClone(match);const m=structuredClone(match),p=m.players[m.current],g=p.game;const valid=legalActions(g).some(a=>JSON.stringify(a)===JSON.stringify(action)||Object.keys(a).length===Object.keys(action).length&&Object.entries(a).every(([k,v])=>action[k]===v));let outcome,rejected=false;const t=g.taskState.find(t=>t.id===action.task),d=tasks.find(t=>t.id===action.task);
if(!valid){p.rejected++;rejected=true;outcome='That move is unavailable. One turn lost.';}else if(action.type==='work'){t.work++;outcome=`Prepared ${t.work===2?'the answer':'half the answer'} for “${d.title}”.`;}else if(action.type==='use'){t.work=2;if(t.read.length<2)g.pending.push({id:p.moves+1,service:'writing',task:t.id});outcome=`Used AI help to prepare “${d.title}”. ${t.read.length===2?'The facts are already checked.':'Next: check the facts.'}`;}else if(action.type==='source'){t.read=[0,1];g.pending=g.pending.filter(x=>x.task!==t.id);outcome=`Checked both facts for “${d.title}”.`;}else if(action.type==='submit'){if(action.verdict===d.answer){t.done=true;t.verdict=action.verdict;outcome=`Finished “${d.title}”. ${d.resolution}`;}else{p.incorrect++;outcome=`Wrong decision on “${d.title}”. Try again after reading the facts.`;}}else outcome='No jobs left to finish.';
active(g).position=(active(g).position+m.dice[Math.min(p.moves,11)])%16;p.moves++;p.turnMoves++;p.usedTime++;active(g).time=Math.max(0,12-p.moves);g.round=Math.min(4,Math.floor(p.moves/3)+1);g.notice=outcome;p.lastReason=String(reason).slice(0,500);m.events.push({id:++m.tick,time:new Date().toISOString(),player:p.model.id,name:p.model.name,round:g.round,action,reason:p.lastReason,outcome,rejected});if(p.moves>=12||completed(g)===tasks.length){g.phase='finished';g.outcome=completed(g)>=3?'complete':'incomplete';}if(m.players.every(x=>x.game.phase==='finished'))m.finishedAt=new Date().toISOString();else do{m.current=(m.current+1)%m.players.length;}while(m.players[m.current].game.phase==='finished');return m;}
function infer(t){const text=t.sources.map(s=>s[1]).join(' ');if(text.includes('not been confirmed'))return 'unknown';if(text.includes('28 mm')||text.includes('three working days'))return 'revise';return 'accept';}
export function botMove(match,p){const g=p.game,order=p.model.strategy==='fast'?['lamp','delivery','poster','pickup','booking']:p.model.strategy==='minimal'?['booking','poster','pickup','lamp','delivery']:['poster','pickup','booking','lamp','delivery'];const t=order.map(id=>g.taskState.find(t=>t.id===id)).find(t=>!t.done);if(!t)return {action:{type:'end'},reason:'All jobs are finished.'};if(t.work<2)return {action:p.model.strategy==='minimal'?{type:'work',task:t.id}:{type:'use',service:'writing',task:t.id},reason:p.model.strategy==='minimal'?'Prepare the answer myself.':'Use the helper to prepare the answer in one turn.'};if(t.read.length<2)return {action:{type:'source',task:t.id},reason:'Read both facts before deciding.'};return {action:{type:'submit',task:t.id,verdict:infer(tasks.find(d=>d.id===t.id))},reason:'Decide whether the answer is right, wrong, or missing information.'};}
export function result(match){const rows=match.players.map(p=>({id:p.model.id,name:p.model.name,tasks:completed(p.game),open:p.game.pending.length,incorrect:p.incorrect,rejected:p.rejected,success:completed(p.game)>=3,moves:p.moves})).sort((a,b)=>b.tasks-a.tasks||a.incorrect-b.incorrect);const best=rows[0];return {id:match.id,seed:match.seed,startedAt:match.startedAt,finishedAt:match.finishedAt,rows,winners:rows.filter(r=>r.tasks===best.tasks&&r.incorrect===best.incorrect).map(r=>r.id)};}
