import {newsCards} from './news.mjs';
export const demoRoster=[{id:'demo/claude',name:'Claude',family:'Demo persona',color:'#c45132',strategy:'careful'},{id:'demo/gemini',name:'Gemini',family:'Demo persona',color:'#1a73e8',strategy:'fast'},{id:'demo/codex',name:'Codex',family:'Demo persona',color:'#202020',strategy:'planner'},{id:'demo/grok',name:'Grok',family:'Demo persona',color:'#d71920',strategy:'builder'},{id:'demo/deepseek',name:'DeepSeek',family:'Demo persona',color:'#4059ed',strategy:'minimal'}];
export const humanPlayer={id:'human/you',name:'You',family:'Human',color:'#283d32',human:true};
const property=(name,group,color,price,rent)=>({name,kind:'property',group,color,price,rent});
export const spaces=[{name:'Start',kind:'start'},property('Prompt Place','mint','#955436',120,20),property('Context Court','mint','#955436',140,25),{name:'Chance',kind:'chance'},property('Model Market','gold','#a9ddf5',160,30),{name:'Just visiting',kind:'jail'},property('Token Terrace','gold','#a9ddf5',180,35),{name:'Compute tax',kind:'tax',cost:80},property('Agent Avenue','blue','#d93a96',200,40),property('Memory Lane','blue','#d93a96',220,45),{name:'Free parking',kind:'parking'},property('Reasoning Road','violet','#f7931d',240,50),property('Inference Square','violet','#f7931d',260,55),{name:'Chance',kind:'chance'},property('Training Tower','clay','#ed1b24',280,60),{name:'Go to timeout',kind:'timeout'},property('Data Drive','clay','#ed1b24',300,65),{name:'Chance',kind:'chance'},property('Evaluation Estate','red','#f5cf00',320,70),property('Alignment Arcade','red','#f5cf00',340,75)];
export const MAX_TURNS=20,BUILD_COST=100;
export const active=m=>m.players[m.current];
export const owned=(m,p)=>m.properties.flatMap((lot,i)=>lot.owner===p.model.id?[i]:[]);
export const netWorth=(m,p)=>p.bankrupt?0:p.cash+owned(m,p).reduce((sum,i)=>sum+spaces[i].price+m.properties[i].houses*BUILD_COST,0);
export const completeGroup=(m,p,index)=>spaces.filter(s=>s.group&&s.group===spaces[index].group).every(s=>m.properties[spaces.indexOf(s)].owner===p.model.id);
export const rent=(m,index)=>{const lot=m.properties[index],owner=m.players.find(p=>p.model.id===lot.owner);return spaces[index].rent*(1+lot.houses*2)*(owner&&completeGroup(m,owner,index)?2:1);};
export function startMatch(roster,number=1,seed=12345){return {edition:'property',newsDeck:structuredClone(newsCards),lastNews:null,ledger:[],ledgerFromStart:true,id:number,seed,rng:seed>>>0,startedAt:new Date().toISOString(),finishedAt:null,current:0,tick:0,phase:'roll',dice:[1,1],lastRoll:null,landing:null,turnActions:0,events:[],properties:spaces.map(()=>({owner:null,houses:0})),players:roster.map(model=>({model,cash:1200,openingCash:1200,lastDice:null,position:0,turns:0,jail:0,bankrupt:false,moves:0,rejected:0,incorrect:0,requests:0,latency:null,lastReason:'Ready to play.'}))};}
export function legalActions(m,p=active(m)){if(m.finishedAt||p!==active(m)||p.bankrupt)return [];if(m.phase==='roll')return [{type:'roll'}];const actions=[{type:'end'}];const index=p.position,s=spaces[index],lot=m.properties[index];if(s.kind==='property'&&!lot.owner&&p.cash>=s.price)actions.push({type:'buy',space:index});if(m.turnActions<8){for(const i of owned(m,p)){if(completeGroup(m,p,i)&&m.properties[i].houses<(m.houseLimit??3)&&p.cash>=BUILD_COST)actions.push({type:'build',space:i});actions.push({type:'sell',space:i});}}return actions;}
function random(m,n){m.rng=(Math.imul(m.rng,1664525)+1013904223)>>>0;return Math.floor(m.rng/4294967296*n);}
function settle(m,p,amount,recipient=null,category='chance',space=null){let liquidation='';if(p.cash<amount){for(const i of owned(m,p).sort((a,b)=>spaces[a].price-spaces[b].price)){transfer(m,'bank',p.model.id,Math.floor((spaces[i].price+m.properties[i].houses*BUILD_COST)/2),'sale',i);m.properties[i]={owner:null,houses:0};liquidation+=`${spaces[i].name} sold to the bank. `;if(p.cash>=amount)break;}}const paid=Math.min(p.cash,amount);transfer(m,p.model.id,recipient?.model.id||'bank',paid,category,space);if(paid<amount){p.bankrupt=true;for(const i of owned(m,p))m.properties[i]={owner:null,houses:0};liquidation+='Bankrupt and out of this game. ';}return {paid,liquidation};}
function finishTurn(m){const p=active(m);p.turns++;m.turnActions=0;const eligible=m.players.map((p,i)=>!p.bankrupt&&p.turns<(m.turnLimit??MAX_TURNS)?i:-1).filter(i=>i>=0);if(eligible.length===0||m.players.filter(p=>!p.bankrupt).length===1){m.finishedAt=new Date().toISOString();m.phase='finished';return;}do{m.current=(m.current+1)%m.players.length;}while(!eligible.includes(m.current));m.phase='roll';m.landing=null;}
function landed(m,p){const s=spaces[p.position],lot=m.properties[p.position];m.landing=p.position;if(s.kind==='property'){if(lot.owner&&lot.owner!==p.model.id){const owner=m.players.find(x=>x.model.id===lot.owner),amount=rent(m,p.position),payment=settle(m,p,amount,owner,'rent',p.position);return `Landed on ${s.name}. Paid $${payment.paid} rent to ${owner.model.name}. ${payment.liquidation}`;}return lot.owner?`Landed on their own ${s.name}.`:`Landed on ${s.name}. Available for $${s.price}; rent starts at $${s.rent}.`;}
if(s.kind==='tax'){const payment=settle(m,p,s.cost,null,'tax',p.position);return `Paid $${payment.paid} compute tax. ${payment.liquidation}`;}
if(s.kind==='timeout'){p.position=5;p.jail=1;return 'Sent to timeout. Their next turn will be skipped.';}
if(s.kind==='chance'){if(m.newsDeck?.length){const card=m.newsDeck[random(m,m.newsDeck.length)];m.lastNews={...card,tick:m.tick+1,drawnBy:p.model.name};let liquidation='';if(card.amount>0)transfer(m,'bank',p.model.id,card.amount,'chance',p.position);else liquidation=settle(m,p,-card.amount,null,'chance',p.position).liquidation;return `News card: ${card.effect} ${liquidation}`;}const cards=[{text:'A useful release earned $100.',amount:100},{text:'A server repair costs $60.',amount:-60},{text:'An open-source grant earned $150.',amount:150},{text:'A surprise audit costs $90.',amount:-90}];const card=cards[random(m,cards.length)];if(card.amount>0)transfer(m,'bank',p.model.id,card.amount,'chance',p.position);else{const payment=settle(m,p,-card.amount,null,'chance',p.position);return `Chance: ${card.text} ${payment.liquidation}`;}return `Chance: ${card.text}`;}
return s.kind==='start'?'Landed on Start.':s.kind==='parking'?'Free parking. Take a breather.':'Just visiting timeout. No penalty.';}
export function applyMove(match,action,reason=''){if(match.finishedAt)return structuredClone(match);const m=structuredClone(match),p=active(m),ledgerStart=m.ledger?.length||0,beforeCash=p.cash,beforeWorth=netWorth(m,p);m.ledger??=[];const valid=legalActions(m).some(a=>Object.keys(a).length===Object.keys(action).length&&Object.entries(a).every(([k,v])=>action[k]===v));let outcome,rejected=false,close=false;const turn=p.turns+1;
if(!valid){p.rejected++;rejected=true;outcome='That move is not available. The turn ended.';close=true;}else if(action.type==='roll'){if(p.jail){p.jail=0;outcome='Sat out a timeout turn. Ready to roll next turn.';close=true;}else{m.dice=[random(m,6)+1,random(m,6)+1];p.lastDice=[...m.dice];m.lastRoll={player:p.model.id,dice:[...m.dice],tick:m.tick+1};const sum=m.dice[0]+m.dice[1],before=p.position;p.position=(before+sum)%spaces.length;const passed=before+sum>=spaces.length;if(passed)transfer(m,'bank',p.model.id,200,'start');m.phase='act';outcome=`Rolled ${m.dice.join(' + ')}. ${passed?'Passed Start and collected $200. ':''}${landed(m,p)}`;if(p.bankrupt)close=true;}}
else if(action.type==='buy'){const s=spaces[action.space];transfer(m,p.model.id,'bank',s.price,'purchase',action.space);m.properties[action.space].owner=p.model.id;outcome=`Bought ${s.name} for $${s.price}. Visitors now pay rent.`;}
else if(action.type==='build'){transfer(m,p.model.id,'bank',BUILD_COST,'build',action.space);m.properties[action.space].houses++;outcome=`Built a house on ${spaces[action.space].name} for $100. Rent is now $${rent(m,action.space)}.`;}
else if(action.type==='sell'){const lot=m.properties[action.space],value=Math.floor((spaces[action.space].price+lot.houses*BUILD_COST)/2);transfer(m,'bank',p.model.id,value,'sale',action.space);m.properties[action.space]={owner:null,houses:0};outcome=`Sold ${spaces[action.space].name} back to the bank for $${value}.`;}
else{outcome='Ended the turn.';close=true;}
p.moves++;m.turnActions++;p.lastReason=String(reason).slice(0,500);m.events.push({id:++m.tick,time:new Date().toISOString(),player:p.model.id,name:p.model.name,round:turn,action,reason:p.lastReason,outcome,rejected,transfers:m.ledger.slice(ledgerStart),cashBefore:beforeCash,cashAfter:p.cash,worthBefore:beforeWorth,worthAfter:netWorth(m,p),lesson:lessonFor(m,p,action,m.ledger.slice(ledgerStart))});m.events=m.events.slice(-600);if(close||m.turnActions>=10)finishTurn(m);return m;}
export function observation(m,p){return {rules:'Terms Apply is an original property board game. Everyone starts with $1200. Roll two dice, then buy the unowned property you land on or end your turn. Rent is paid automatically on arrival. Passing Start earns $200. Owning both properties of a color doubles rent and unlocks houses at $100 each, maximum three per property. Rent is base rent times (1 + 2 * houses) times color-set bonus. Sell properties to the bank for half their purchase and house costs. Tax and chance cards change cash. New games use dated, sourced news cards with fictional cash effects; these are drawn by any player and do not rate model quality. Timeout skips the next turn. If you cannot pay, properties are sold automatically; remaining debt means bankruptcy. After 20 turns per player, highest net worth (cash + original property prices + house costs) wins. Last solvent player wins early. No extra turns for doubles. Up to ten actions per turn.',you:{id:p.model.id,cash:p.cash,position:p.position,turn:p.turns+1,properties:owned(m,p),netWorth:netWorth(m,p)},players:m.players.map(x=>({id:x.model.id,name:x.model.name,cash:x.cash,position:x.position,bankrupt:x.bankrupt})),board:spaces.map((s,i)=>({...s,index:i,...m.properties[i],currentRent:s.kind==='property'?rent(m,i):0})),legalActions:legalActions(m,p),previousEvents:m.events.slice(-8).map(e=>({player:e.name,action:e.action,outcome:e.outcome}))};}
export const strategyInfo={careful:{name:'Cash keeper',reserve:500,description:'Keeps $500 available before buying or building.'},fast:{name:'Collector',reserve:220,description:'Buys available streets while keeping a $220 reserve.'},planner:{name:'Set builder',reserve:350,description:'Prioritizes color pairs; lowers its reserve to $150 to complete a set.'},builder:{name:'Risk taker',reserve:120,description:'Keeps just $120 and builds up to three houses.'},minimal:{name:'Value buyer',reserve:350,description:'Buys streets whose base rent is at least 19% of the price; builds at most one house.'}};
export function botMove(m,p){const actions=legalActions(m,p),roll=actions.find(a=>a.type==='roll'),info=strategyInfo[p.model.strategy]||strategyInfo.careful;if(roll)return {action:roll,reason:p.jail?'Serve the timeout turn.':'Roll to find the next opportunity.'};const buy=actions.find(a=>a.type==='buy');if(buy){const square=spaces[buy.space],pair=owned(m,p).some(i=>spaces[i].group===square.group),reserve=p.model.strategy==='planner'&&pair?150:info.reserve,yieldOK=p.model.strategy!=='minimal'||square.rent/square.price>=.19;if(p.cash-square.price>=reserve&&yieldOK)return {action:buy,reason:`${info.name}: pay $${square.price}, keep $${p.cash-square.price} cash${pair?', and complete a color pair':''}.`};return {action:{type:'end'},reason:`${info.name}: skip this purchase. It would leave $${p.cash-square.price}; my reserve is $${reserve}.${!yieldOK?' Its rent-to-price ratio is below my target.':''}`};}const builds=actions.filter(a=>a.type==='build').sort((a,b)=>rent(m,b.space)-rent(m,a.space));const build=builds.find(a=>m.properties[a.space].houses<(p.model.strategy==='minimal'||p.model.strategy==='careful'?1:p.model.strategy==='fast'?2:3));if(build&&p.cash-BUILD_COST>=info.reserve)return {action:build,reason:`${info.name}: spend $100 to raise rent, with $${p.cash-100} still available.`};return {action:{type:'end'},reason:`${info.name}: keep $${p.cash} available and pass the dice.`};}
export function result(m){const rows=m.players.map(p=>({id:p.model.id,name:p.model.name,netWorth:netWorth(m,p),cash:p.cash,properties:owned(m,p).length,bankrupt:p.bankrupt,moves:p.moves,tasks:owned(m,p).length,open:0,incorrect:0,rejected:p.rejected,success:!p.bankrupt})).sort((a,b)=>b.netWorth-a.netWorth);const best=rows[0];return {id:m.id,seed:m.seed,startedAt:m.startedAt,finishedAt:m.finishedAt,rows,winners:rows.filter(r=>r.netWorth===best.netWorth).map(r=>r.id)};}

function transfer(m,from,to,amount,category,space=null){if(amount<=0)return;const payer=m.players.find(p=>p.model.id===from),receiver=m.players.find(p=>p.model.id===to);if(payer)payer.cash-=amount;if(receiver)receiver.cash+=amount;m.ledger.push({id:m.ledger.length+1,tick:m.tick+1,from,to,amount,category,space});}
export function finances(m,p){const rows=(m.ledger||[]).filter(t=>t.from===p.model.id||t.to===p.model.id),income=rows.filter(t=>t.to===p.model.id).reduce((n,t)=>n+t.amount,0),out=rows.filter(t=>t.from===p.model.id).reduce((n,t)=>n+t.amount,0),sum=(category,incoming)=>rows.filter(t=>t.category===category&&(incoming?t.to===p.model.id:t.from===p.model.id)).reduce((n,t)=>n+t.amount,0);return {opening:p.openingCash??1200,income,out,cash:p.cash,assets:netWorth(m,p)-p.cash,profit:netWorth(m,p)-(p.openingCash??1200),rentEarned:sum('rent',true),rentPaid:sum('rent',false),start:sum('start',true),chanceIn:sum('chance',true),chanceOut:sum('chance',false),sales:sum('sale',true),purchases:sum('purchase',false),houses:sum('build',false),tax:sum('tax',false),rows};}
function lessonFor(m,p,action,rows){if(m.lastNews?.tick===m.tick)return {title:'Real news, fictional game effect',text:m.lastNews.lesson};if(action.type==='buy')return {title:'Cash becomes an asset',text:`Buying this street moves $${spaces[action.space].price} from cash into property value. Net worth stays the same. Earnings only begin when another player lands here.`};if(action.type==='build')return {title:'Higher rent needs cash up front',text:'A house costs $100 now. It raises the rent for future visitors, but a visitor is never guaranteed.'};if(action.type==='sell'||rows.some(t=>t.category==='sale'))return {title:'Forced selling loses value',text:'The bank pays half of the property and house costs. Cash increases, but net worth falls by the other half.'};if(rows.some(t=>t.category==='rent')){const row=rows.find(t=>t.category==='rent'),owner=m.players.find(p=>p.model.id===row.to);return {title:'Rent moves money between players',text:`$${row.amount} leaves ${p.model.name} and reaches ${owner.model.name}. The bank does not take a cut.`};}if(rows.some(t=>t.category==='start'))return {title:'An income source outside the players',text:'Passing Start adds $200 from the bank. This grows the money available at the table.'};if(rows.some(t=>t.category==='tax'||t.category==='chance'))return {title:'Cash can change without a purchase',text:'Tax and chance cards transfer money to or from the bank. A cash reserve helps cover these surprises.'};if(action.type==='end')return {title:'Holding cash keeps options open',text:'Ending a turn can preserve a reserve for rent, tax or a later purchase. It also means giving up the current opportunity.'};return {title:'Luck changes the opportunity',text:'The dice choose the destination. The player decides what to do with the cash and properties available.'};}
export function upgradeMatch(saved){if(saved.ledger&&saved.players.every(p=>p.openingCash!=null))return saved;try{let rebuilt=startMatch(saved.players.map(p=>p.model),saved.id,saved.seed);if(!saved.newsDeck)delete rebuilt.newsDeck;else rebuilt.newsDeck=structuredClone(saved.newsDeck);for(const event of saved.events){rebuilt=applyMove(rebuilt,event.action,event.reason);rebuilt.events.at(-1).time=event.time;}const snapshot=m=>JSON.stringify({rng:m.rng,current:m.current,phase:m.phase,properties:m.properties,players:m.players.map(p=>[p.cash,p.position,p.turns,p.bankrupt,p.jail])});if(snapshot(saved)===snapshot(rebuilt)){rebuilt.players.forEach((p,i)=>{p.requests=saved.players[i].requests;p.latency=saved.players[i].latency;});rebuilt.startedAt=saved.startedAt;rebuilt.finishedAt=saved.finishedAt;return rebuilt;}}catch{}return {...saved,ledger:[],ledgerFromStart:false,players:saved.players.map(p=>({...p,openingCash:p.cash,lastDice:null}))};}
