import {lessons,checkAnswer,houseExample} from './learning.mjs';
export function mountLearning({onOpen=()=>{},onClose=()=>{}}={}){
const room=document.querySelector('#learning-room'),body=document.querySelector('#learning-body'),progress=document.querySelector('#learning-progress'),next=document.querySelector('#lesson-next'),back=document.querySelector('#lesson-back');let index=0,answer=null,completed=new Set();
function render(){const l=lessons[index],correct=checkAnswer(index,answer);progress.textContent=`Lesson ${index+1} of ${lessons.length} · ${completed.size} checked`;body.innerHTML=`<p class="learning-goal">${l.goal}</p><h2 id="lesson-title" tabindex="-1">${l.title}</h2><p class="practice-label">Practice scenario · fictional money</p><p>${l.scene}</p><dl class="lesson-math">${l.rows.map(([label,value])=>`<dt>${label}</dt><dd>${value}</dd>`).join('')}</dl>${l.calculator?'<label class="visitor-label" for="practice-visitors">Try a different number of paying visitors</label><input id="practice-visitors" type="range" min="0" max="6" step="1" value="2"><output id="visitor-result" for="practice-visitors"></output>':''}<fieldset class="lesson-question"><legend>${l.question}</legend>${l.choices.map((choice,i)=>`<button type="button" data-answer="${i}" aria-pressed="${answer===i}" ${correct?'disabled':''}>${choice}</button>`).join('')}</fieldset><div class="answer-feedback" role="status">${answer===null?'Make a prediction. Then see how the numbers work.':correct?`<strong>That’s right.</strong><p>${l.explanation}</p><p class="lesson-limit">${l.limit}</p>`:`<strong>Check the reasoning, then try again.</strong><p>${l.explanation}</p>`}</div>${correct?`<p class="watch-task"><strong>Try it on the board</strong><br>${l.watch}</p>`:''}`;next.disabled=!correct;next.textContent=index===lessons.length-1?'Finish lesson trail':'Next lesson';back.disabled=index===0;if(l.calculator)updateCalculator();}
function updateCalculator(){const f=houseExample(document.querySelector('#practice-visitors').value);document.querySelector('#visitor-result').textContent=`${f.visits} paying visitors × $80 extra rent = $${f.extra}. After the $100 house cost: ${f.net<0?'−':'+'}$${Math.abs(f.net)} cash from this upgrade.`;}
body.onclick=e=>{const button=e.target.closest('[data-answer]');if(!button)return;answer=Number(button.dataset.answer);if(checkAnswer(index,answer))completed.add(index);render();};body.oninput=e=>{if(e.target.id==='practice-visitors')updateCalculator();};
next.onclick=()=>{if(!checkAnswer(index,answer))return;if(index<lessons.length-1){index++;answer=completed.has(index)?lessons[index].correct:null;render();body.querySelector('h2').focus();}else{progress.textContent='Six lessons completed';body.innerHTML='<h2 id="lesson-title" tabindex="-1">Put the lessons into practice.</h2><p>You have checked cash versus assets, transfers, reserves, extra income, chance and AI attribution.</p><ol class="practice-finish"><li>Select a player and explain one money-in and one money-out entry.</li><li>Pause the game. Before the next move, predict what could happen to cash and net worth.</li><li>Join a game. Compare buying with keeping your cash before choosing.</li><li>Before judging an AI, check the decision source and the evidence behind its score.</li></ol><p>Return to the board to inspect a decision. You can revisit these exercises any time.</p>';next.hidden=true;back.hidden=true;document.querySelector('#close-learning').textContent='Return to the board';body.querySelector('h2').focus();}};
back.onclick=()=>{index--;answer=completed.has(index)?lessons[index].correct:null;render();};document.querySelector('#learn').onclick=async()=>{try{await onOpen();index=0;answer=completed.has(0)?lessons[0].correct:null;next.hidden=false;back.hidden=false;document.querySelector('#close-learning').textContent='Back to game';render();room.showModal();}catch(e){document.querySelector('#feedback').textContent=e.message;}};document.querySelector('#close-learning').onclick=()=>room.close();room.onclose=()=>onClose();
}
