import {spaces,BUILD_COST,rent,netWorth,startMatch,applyMove,demoRoster} from './game.mjs';
const practice=startMatch(demoRoster,1,42);practice.phase='act';practice.players[0].position=1;
const bought=applyMove(practice,{type:'buy',space:1});
const built=structuredClone(bought);built.properties[2].owner=demoRoster[0].id;built.properties[1].houses=1;
const beforeRent=spaces[1].rent*2,afterRent=rent(built,1),extraRent=afterRent-beforeRent;
export const lessons=[
 {id:'assets',title:'Cash is not the same as wealth',goal:'Explain what changes when a player buys a street.',scene:'Claude starts with $1,200 and buys Prompt Place for $120.',rows:[['Cash before','$1,200'],['Purchase','−$120 cash'],['Cash after',`$${bought.players[0].cash.toLocaleString()}`],['Property value','$120']],question:'What is Claude’s net worth immediately after buying?',choices:['$1,080','$1,200','$1,320'],correct:1,explanation:`Cash falls to $1,080, but the street counts as a $120 asset. $1,080 + $120 = $${netWorth(bought,bought.players[0]).toLocaleString()}. No rent has been earned yet.`,watch:'Select a player and compare cash with net worth after a purchase.',limit:'This game values streets at their purchase cost. Their resale price is only half that cost.'},
 {id:'rent',title:'Follow a payment from both sides',goal:'Separate money earned from money transferred.',scene:'Gemini visits Claude’s Prompt Place. Claude owns only this street, with no houses, so rent is $20.',rows:[['Gemini pays','−$20'],['Claude receives','+$20'],['Bank receives','$0']],question:'What happens to the total cash held by the players?',choices:['It increases by $20','It stays the same','It decreases by $20'],correct:1,explanation:'The same $20 leaves Gemini and reaches Claude. Rent changes who holds the cash; it does not create cash. Passing Start is different: the bank pays $200 into the game.',watch:'Look for a rent payment in recent moves, then inspect both players’ ledgers.',limit:'Property income depends on visitors. Owning a street alone does not guarantee earnings.'},
 {id:'reserve',title:'Keep enough cash to pay the next bill',goal:'Recognize the tradeoff between owning assets and keeping cash.',scene:'You have $300 cash. A street costs $240. A possible upcoming bill is $80. Compare the two choices before deciding.',rows:[['Buy the street','$60 cash remains'],['Keep the cash','$300 cash remains'],['Possible bill','$80']],question:'If you buy and then owe $80, can your remaining cash cover the bill?',choices:['Yes, because you own a property','No, you are $20 short','Yes, buying earns rent immediately'],correct:1,explanation:'$300 − $240 = $60. That is $20 less than the $80 bill. The game would sell assets at half value to help you pay. Keeping cash avoids that forced sale, but gives up the current street.',watch:'Compare the Cash keeper and Risk taker. Read their reserves before comparing their final scores.',limit:'The bill is a practice scenario, not a prediction of the next dice roll. There is no purchase rule that wins every game.'},
 {id:'building',title:'Calculate the extra income from a house',goal:'Compare the cost of an upgrade with the extra rent it earns.',scene:'You own the brown pair. Prompt Place earns $40 per visitor. A $100 house raises that rent to $120.',rows:[['House cost',`$${BUILD_COST}`],['Rent before',`$${beforeRent}`],['Rent after',`$${afterRent}`],['Extra rent per visitor',`$${extraRent}`]],question:'How many paying visitors cover the $100 house cost through extra rent?',choices:['1 visitor','2 visitors','3 visitors'],correct:1,explanation:'Each visitor adds $80 more than the street earned before. One adds $80, which is below the $100 cost. Two add $160. This calculation uses extra rent, not the full $120 rent.',watch:'Complete a color pair, inspect the rent, and compare it before and after building.',limit:'Two visits are enough only if they happen and the visitors can pay. Tax, other rent and the remaining turns still matter.',calculator:true},
 {id:'luck',title:'A win does not settle the comparison',goal:'Identify why luck can hide the effect of a strategy.',scene:'A cautious player loses one game. A risk-taking player wins. They landed on different squares and drew different chance cards.',rows:[['What differed','Strategy and chance'],['What we observed','One game result'],['What we still need','Repeated, comparable games']],question:'Which conclusion is supported by this single game?',choices:['Risk-taking is always better','The winning player had more net worth in this game','The winner is the most intelligent AI'],correct:1,explanation:'The score tells us who won this game under these rules. To compare strategies, repeat many games, control starting conditions, vary seeds and seat order, and report how often each strategy wins and loses.',watch:'Read the past games rather than treating the latest winner as the strongest player.',limit:'The current table gives a game score. It does not establish a reliable ranking of strategies or general intelligence.'},
 {id:'ai',title:'Check what the AI label actually means',goal:'Distinguish a named demo strategy from a real model evaluation.',scene:'The public page names its players Claude, Gemini, Codex, Grok and DeepSeek. Its status says “Demo strategies · no model calls.”',rows:[['Decision source','Written game rules'],['Real model requests','None in browser demo'],['What the names label','Demo personas']],question:'What can this browser demo teach us about Claude’s real reasoning?',choices:['It proves Claude keeps a $500 reserve','It proves Claude is better than Gemini','It cannot establish real-model behavior'],correct:2,explanation:'The developer wrote the Cash keeper strategy. The name does not make its decisions come from Claude. Actual model comparisons need verified model calls, recorded prompts, the same rules, repeated games and clear limits on the conclusions.',watch:'Check the player source before interpreting any score. Ask what evidence produced the claim.',limit:'Even verified model play would measure behavior in this game, not general ability, safety or trustworthiness.'}
];
export function checkAnswer(index,answer){const lesson=lessons[index];return !!lesson&&Number.isInteger(answer)&&answer===lesson.correct;}
export function houseExample(visits){const count=Math.max(0,Math.min(6,Math.floor(Number(visits)||0)));return {visits:count,extra:count*extraRent,cost:BUILD_COST,net:count*extraRent-BUILD_COST};}
export function decisionPreview(m,p){const square=spaces[p.position],lot=m.properties[p.position];if(m.phase!=='act'||square.kind!=='property'||lot.owner||p.bankrupt)return null;return {name:square.name,price:square.price,rent:square.rent,buyCash:p.cash-square.price,keepCash:p.cash,worth:netWorth(m,p),affordable:p.cash>=square.price};}
