import test from 'node:test';
import assert from 'node:assert/strict';
import {marketNews,newsChecked,newsEdition} from './news.mjs';
import {newsImpact} from './market-news.mjs';
import {startQuick,quickApply} from './quick-game.mjs';
import {demoRoster,finances,applyMove,startMatch} from './game.mjs';
function draw(card,{legacy=false,properties=0}={}){for(let seed=1;seed<200;seed++){const m=legacy?startMatch(demoRoster.slice(0,2),1,seed):startQuick(demoRoster.slice(0,2),1,seed);m.newsDeck=[structuredClone(card)];[1,2,4,6].slice(0,properties).forEach(i=>m.properties[i].owner=m.players[0].model.id);const next=legacy?applyMove(m,{type:'roll'}):quickApply(m,{type:'roll'});if(next.lastNews)return next;}throw Error('No news draw in fixtures');}
test('market deck has bounded sourced facts, categories, status and distinct IDs',()=>{assert.ok(marketNews.length>=8&&marketNews.length<=12);assert.equal(new Set(marketNews.map(c=>c.id)).size,marketNews.length);assert.match(newsChecked,/^\d{4}-\d{2}-\d{2}$/);assert.ok(newsEdition.startsWith(newsChecked));for(const c of marketNews){assert.ok(c.date<=newsChecked);assert.equal(new URL(c.url).protocol,'https:');assert.ok(c.title&&c.publisher&&c.fact&&c.lesson&&c.effect&&c.category&&c.status);assert.ok(['cash','ipo','portfolio-cost'].includes(c.mechanic));assert.ok(Number.isInteger(c.amount)&&Math.abs(c.amount)<=250);const i=newsImpact(c,12);assert.ok(Number.isFinite(i.net)&&i.incoming>=0&&i.outgoing>=0&&i.incoming<=250&&i.outgoing<=250);}});
test('IPO records gross capital and fees as separate transfers with a reconciled net',()=>{const card=marketNews.find(c=>c.mechanic==='ipo'),m=draw(card),p=m.players[0],f=finances(m,p);assert.equal(f.chanceIn,200);assert.equal(f.chanceOut,10);assert.equal(p.cash,1390);assert.equal(f.opening+f.income-f.out,p.cash);assert.equal(m.lastNews.impact.net,190);assert.match(m.lastNews.lesson,/does not simulate shares/);assert.equal(m.events[0].transfers.length,2);});
test('secondary shareholder sale gives no money to the fictional company',()=>{const card=marketNews.find(c=>c.id==='cerebras-secondary-sale'),m=draw(card);assert.equal(m.players[0].cash,1200);assert.equal(m.events[0].transfers.length,0);assert.equal(m.lastNews.impact.net,0);assert.match(card.lesson,/does not prove the sale occurred/);});
test('outage recovery scales with owned streets and has a minimum, without charging unowned streets',()=>{const card=marketNews.find(c=>c.mechanic==='portfolio-cost');assert.equal(draw(card).players[0].cash,1180);const m=draw(card,{properties:3});assert.equal(m.players[0].cash,1140);assert.equal(m.lastNews.impact.outgoing,60);assert.equal(finances(m,m.players[0]).chanceOut,60);});
test('old rules and saved news snapshots are not reinterpreted',()=>{const card=marketNews.find(c=>c.mechanic==='portfolio-cost');assert.equal(draw(card,{legacy:true,properties:3}).players[0].cash,1180);const a=startQuick(demoRoster.slice(0,1));assert.equal(a.rulesVersion,'quick-v2');assert.equal(a.newsEdition,newsEdition);assert.equal(a.newsChecked,newsChecked);a.newsDeck[0].title='Saved edition';assert.notEqual(startQuick(demoRoster.slice(0,1)).newsDeck[0].title,a.newsDeck[0].title);const old=startQuick(demoRoster.slice(0,1));old.rulesVersion='quick-v1';old.newsDeck=[{...card,amount:-60}];let drawn;for(let seed=1;seed<200;seed++){old.seed=old.rng=seed;const m=applyMove(old,{type:'roll'});if(m.lastNews){drawn=m;break;}}assert.equal(drawn.players[0].cash,1140);});
