// Editorial snapshot, checked 2026-10-08. These are game analogies, not model ratings.
export const newsChecked='2026-10-08';
export const newsCards=[
 {id:'haiku-release',player:'Claude',date:'2026-10-07',title:'Anthropic introduces Claude Haiku 5.5',publisher:'Anthropic',url:'https://www.anthropic.com/claude-haiku-5-5',fact:'Anthropic announced a small model designed for high-volume, cost-sensitive work.',lesson:'A smaller model can change the cost of a repeated task. Check whether its quality is sufficient before switching.',amount:100,effect:'A lower-cost workflow saves you $100 in game cash.'},
 {id:'connected-apps',player:'Gemini',date:'2026-10-02',title:'Google’s September recap highlights connected apps',publisher:'Google',url:'https://blog.google/innovation-and-ai/technology/ai/google-ai-updates-september-2026/',fact:'Google’s recap describes new Gemini connections to productivity and creative apps.',lesson:'Connected tools can reduce manual work. They also require choosing which data and permissions to share.',amount:80,effect:'A connected workflow earns you $80 in game cash.'},
 {id:'service-outage',player:'Codex',date:'2026-09-29',title:'OpenAI reports errors across ChatGPT, Codex and APIs',publisher:'OpenAI Status',url:'https://status.openai.com/incidents/35y48hbm',fact:'OpenAI reported elevated errors on September 29. The incident is resolved.',lesson:'Even a capable model depends on available infrastructure. Plan retries, a fallback and a cash reserve.',amount:-60,effect:'A fictional service interruption costs you $60 in game cash.'},
 {id:'grok-decks',player:'Grok',date:'2026-10-07',title:'Grok Bot adds slide-deck creation',publisher:'Grok Bot changelog',url:'https://x.ai/changelog/bot',fact:'The October 7 changelog says Bots can build slide decks and deliver PowerPoint files or Google Slides.',lesson:'Generating an artifact is only part of the job. Check the content and the exported file before using it.',amount:120,effect:'A reviewed presentation earns you $120 in game cash.'},
 {id:'deepseek-flash',player:'DeepSeek',date:'2026-09-10',title:'DeepSeek introduces V4.1-Flash',publisher:'DeepSeek',url:'https://www.deepseek.com/en/news/deepseek-v4-1-flash/',fact:'DeepSeek introduced a smaller architecture-family model with native visual understanding, targeting faster inference and higher throughput.',lesson:'Speed, capability and cost are separate measures. Compare them on your own task rather than treating a release as a universal upgrade.',amount:90,effect:'An efficient workflow saves you $90 in game cash.'}
];
export const playerProfiles={
 Claude:{role:'The patient banker',plan:'Keeps $500 in reserve. Buys carefully and builds one house per street.',strength:'Cash for surprise bills',risk:'Can miss early purchases',piece:'Copper sphere'},
 Gemini:{role:'The collector',plan:'Buys broadly with a $220 reserve. Builds up to two houses per street.',strength:'More chances to collect rent',risk:'Less cash for expensive landings',piece:'Blue cone'},
 Codex:{role:'The set architect',plan:'Chases color pairs. Accepts a $150 reserve to finish a pair; otherwise keeps $350.',strength:'Double rent from complete pairs',risk:'A pair can use up the reserve',piece:'Black cube'},
 Grok:{role:'The aggressive builder',plan:'Keeps only $120 and builds up to three houses per street.',strength:'High rent when visitors arrive',risk:'An unexpected bill can force a sale',piece:'Red diamond'},
 DeepSeek:{role:'The value hunter',plan:'Buys only when base rent is at least 19% of the price. Keeps $350 and builds one house.',strength:'Selective spending',risk:'Can finish with few properties',piece:'Indigo hexagon'}
};
