// Editorial snapshot, checked 2026-10-10. These are game analogies, not model ratings.
export const newsChecked='2026-10-10';
export const newsCards=[
 {id:'haiku-release',player:'Claude',date:'2026-10-07',title:'Anthropic introduces Claude Haiku 5.5',publisher:'Anthropic',url:'https://www.anthropic.com/claude-haiku-5-5',fact:'Anthropic announced a small model designed for high-volume, cost-sensitive work.',lesson:'A smaller model can change the cost of a repeated task. Check whether its quality is sufficient before switching.',amount:100,effect:'A lower-cost workflow saves you $100 in game cash.'},
 {id:'connected-apps',player:'Gemini',date:'2026-10-02',title:'Google’s September recap highlights connected apps',publisher:'Google',url:'https://blog.google/innovation-and-ai/technology/ai/google-ai-updates-september-2026/',fact:'Google’s recap describes new Gemini connections to productivity and creative apps.',lesson:'Connected tools can reduce manual work. They also require choosing which data and permissions to share.',amount:80,effect:'A connected workflow earns you $80 in game cash.'},
 {id:'service-outage',player:'Codex',date:'2026-09-29',title:'OpenAI reports errors across ChatGPT, Codex and APIs',publisher:'OpenAI Status',url:'https://status.openai.com/incidents/35y48hbm',fact:'OpenAI reported elevated errors on September 29. The incident is resolved.',lesson:'Even a capable model depends on available infrastructure. Plan retries, a fallback and a cash reserve.',amount:-60,effect:'A fictional service interruption costs you $60 in game cash.'},
 {id:'grok-decks',player:'Grok',date:'2026-10-07',title:'Grok Bot adds slide-deck creation',publisher:'Grok Bot changelog',url:'https://x.ai/changelog/bot',fact:'The October 7 changelog says Bots can build slide decks and deliver PowerPoint files or Google Slides.',lesson:'Generating an artifact is only part of the job. Check the content and the exported file before using it.',amount:120,effect:'A reviewed presentation earns you $120 in game cash.'},
 {id:'deepseek-flash',player:'DeepSeek',date:'2026-09-10',title:'DeepSeek introduces V4.1-Flash',publisher:'DeepSeek',url:'https://www.deepseek.com/en/news/deepseek-v4-1-flash/',fact:'DeepSeek introduced a smaller architecture-family model with native visual understanding, targeting faster inference and higher throughput.',lesson:'Speed, capability and cost are separate measures. Compare them on your own task rather than treating a release as a universal upgrade.',amount:90,effect:'An efficient workflow saves you $90 in game cash.'}
];
export const playerProfiles={
 Claude:{role:'The patient banker',plan:'Keeps $500 in reserve. Buys carefully and builds one house per street.',strength:'Cash for surprise bills',risk:'Can miss early purchases',piece:'Copper sphere'},
 Gemini:{role:'The collector',plan:'Buys broadly with a $220 reserve. Builds up to two houses per street.',strength:'More chances to collect rent',risk:'Less cash for expensive landings',piece:'Blue cone'},
 Codex:{role:'The set architect',plan:'Chases color pairs. Accepts a $150 reserve to finish a pair; otherwise keeps $350.',strength:'Double rent from complete pairs',risk:'A pair can use up the reserve',piece:'Black cube'},
 Grok:{role:'The aggressive builder',plan:'Keeps only $120 and builds up to three houses per street.',strength:'High rent when visitors arrive',risk:'An unexpected bill can force a sale',piece:'Red diamond'},
 DeepSeek:{role:'The value hunter',plan:'Buys only when base rent is at least 19% of the price. Keeps $350 and builds one house.',strength:'Selective spending',risk:'Can finish with few properties',piece:'Indigo hexagon'}
};

// Facts are sourced; these bounded cash effects are authored teaching examples.
// Update only new-match decks. The referee reads the snapshot saved in the match.
export const newsEdition='2026-10-10-market-v1';
export const marketNews=[
 ...newsCards.map(c=>({...c,status:'Confirmed',category:c.id==='service-outage'?'Outage':'Product launch',...(c.id==='service-outage'?{mechanic:'portfolio-cost',amount:-20,perStreet:20,effect:'Recovery costs $20 per street you own, with a $20 minimum.',lesson:'An outage can create recovery costs. In this fictional example, a larger portfolio costs more to restore; real incident costs are not measured by this card.'}:{mechanic:'cash'})})),
 {id:'gemini-personal-access',player:'Gemini',date:'2026-10-09',category:'Model access',status:'Announced rollout',title:'Google changes personal-account Gemini model access',publisher:'Google Gemini Apps Help',url:'https://support.google.com/gemini/answer/17004136',fact:'Google says model-access changes for personal accounts without an AI subscription begin on October 9. Auto selection sends most prompts to Flash-Lite and may route deeper-reasoning prompts to Flash or Pro. AI Plus users receive a separate rollout timetable by email.',lesson:'Check the current plan, routing settings and available models before relying on a workflow. Consumer-app access does not establish which models your API provider offers.',mechanic:'cash',amount:-60,effect:'Adapting your fictional workflow to changed model availability costs $60 in game cash. This is an authored teaching cost, not Google’s subscription price.'},
 {id:'gemini-work-agent',player:'Gemini',date:'2026-10-08',category:'Product launch',status:'Confirmed announcement',title:'Google Cloud announces the Gemini agent',publisher:'Google',url:'https://blog.google/innovation-and-ai/infrastructure-and-cloud/google-cloud/gemini-at-work/',fact:'Google Cloud announced a work agent that it says connects to business systems, uses tools and includes model selection and cost controls.',lesson:'Before an agent acts in business systems, set its permissions and spending limits, then check the result. A product announcement does not prove savings on your task.',mechanic:'cash',amount:80,effect:'A reviewed workflow earns your fictional company $80 in game cash. This is an authored example, not a measured result from Google.'},
 {id:'nvidia-science-commitment',player:'Market',date:'2026-10-08',category:'Compute and research',status:'Announced commitment',title:'NVIDIA commits $1 billion to US science over five years',publisher:'NVIDIA',url:'https://nvidianews.nvidia.com/news/nvidia-commits-1-billion-to-advance-us-science-over-the-next-five-years',fact:'NVIDIA announced commitments valued at $1 billion over the next five years to support US scientific research, quantum computing and cloud infrastructure.',lesson:'An announced multi-year commitment is not proof that money has been paid or compute delivered. Check timing and delivery before treating future resources as available cash.',mechanic:'cash',amount:0,effect:'Your fictional company records a future resource commitment but receives $0 today. The game does not simulate its later delivery.'},
 {id:'anthropic-private-funding',player:'Market',date:'2026-05-28',category:'Private funding',status:'Confirmed · market lesson',title:'Anthropic announces Series H funding',publisher:'Anthropic',url:'https://www.anthropic.com/news/series-h',fact:'Anthropic announced $65 billion of Series H funding at a $965 billion post-money valuation.',lesson:'Funding supplies capital; valuation is not money in the bank or operating profit. Issuing equity can dilute existing owners. Equity dilution is not simulated here.',mechanic:'cash',amount:120,effect:'Investors supply your fictional company with $120 of capital. This is funding, not sales revenue.'},
 {id:'cerebras-ipo',player:'Market',date:'2026-05-15',category:'IPO',status:'Confirmed listing · market lesson',title:'Cerebras closes its IPO',publisher:'Cerebras investor relations',url:'https://investors.cerebras.ai/news-releases/news-release-details/cerebras-systems-announces-closing-initial-public-offering',fact:'Cerebras announced its IPO had closed. Its shares began Nasdaq trading on May 14, 2026, under CBRS.',lesson:'Primary share issuance can raise company capital. Fees reduce the proceeds, and new shares can dilute owners. The game shows gross capital minus fees; it does not simulate shares, dilution or a stock price.',mechanic:'ipo',capital:200,fee:10,amount:190,effect:'Your fictional company raises $200 and pays $10 listing costs: $190 net capital, not profit.'},
 {id:'cerebras-secondary-sale',player:'Market',date:'2026-05-14',category:'Shareholder sale',status:'Confirmed filing · market lesson',title:'Shareholder sales do not fund the company',publisher:'SEC · Cerebras filing',url:'https://www.sec.gov/Archives/edgar/data/2021728/000162828026034800/resales-8xmay2026.htm',fact:'Cerebras’s reoffer prospectus covers shares sold by existing shareholders and states that the company receives no proceeds from those sales.',lesson:'Money from a secondary share sale goes to the selling shareholder, rather than funding the company. This card adds no company cash. A filing describes a possible sale; it does not prove the sale occurred.',mechanic:'cash',amount:0,effect:'Existing shareholders may sell their shares. Your fictional company receives $0.'}
];
