import {createBoard} from './board3d.mjs';
import {brandAsset} from './brands.mjs';
import {demoRoster,spaces,active,owned,netWorth,finances,result,rent} from './game.mjs';
import {quickActions,quickStage} from './quick-game.mjs';
import {createCredentials,cleanCallbackURL} from './credentials.mjs';
import {createPrivateRunner,loadCatalog} from './private-runner.mjs';
import {newsCards,playerProfiles} from './news.mjs';
const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=x=>'$'+Math.round(x).toLocaleString(),usd=x=>'$'+Number(x).toFixed(4);
const families=['Claude','Gemini','OpenAI','Grok','DeepSeek'],demoFor=family=>demoRoster.find(p=>p.name===(family==='OpenAI'?'Codex':family)),asset=family=>brandAsset(family==='OpenAI'?'Codex':family),mark=p=>p.model.human?'<span class="you-token">YOU</span>':`<img src="${asset(p.model.brand||p.model.name)}" alt="" width="28" height="28">`;
const credentials=createCredentials(),runner=createPrivateRunner({credentials});let state,board,view=matchMedia('(max-width:760px)').matches?'top':'angled',setupMode='demo',picked=new Set(['Claude','Gemini']),catalog=[],catalogStatus='idle',modelChoice=new Map(),detailTab='players',selectedPlayer='human/you',selectedSquare=null,setupWasRunning=false,detailsWasRunning=false,lastAnnouncement='',connectBusy=false,callbackBusy=false;
function beginnerPlan(name){return playerProfiles[name]?.plan.replace(/builds up to (two|three) houses per street\./gi,t=>t[0]==='b'?'builds one house per street.':'Builds one house per street.');}
function detailsInert(value){document.querySelectorAll('.topbar,main,footer,#setup-panel,#end-panel,.skip').forEach(el=>el.inert=value);}
function setView(value){view=value;board?.setView(value);$('angled').setAttribute('aria-pressed',String(value==='angled'));$('top').setAttribute('aria-pressed',String(value==='top'));}
function render(s){const focusWasMove=$('move-buttons').contains(document.activeElement);state=s;const m=s.match,p=active(m),you=m.players.find(p=>p.model.human),stage=quickStage(m);
 if(!board){board=createBoard($('board'),index=>{selectedSquare=index;detailTab='squares';openDetails();});setView(view);}board.update(m);board.setSelected(selectedSquare);
 $('board').setAttribute('aria-label',`Property game board. ${m.players.map(p=>p.model.name+' at '+spaces[p.position].name).join('. ')}. Dice ${m.dice.join(' and ')}.`);
 $('mode-label').textContent=s.mode==='real'?'Real models · your key':'Free demo · written strategies';$('game-title').textContent=s.started?(p.model.human?'Your move':p.model.name+'’s move'):'Can you beat the AI?';$('round-label').textContent=s.started?`Round ${Math.min(10,p.turns+1)} of 10 · ${money(netWorth(m,you))} your wealth`:'10 turns each · highest wealth wins';
 $('roster').innerHTML=m.players.map(p=>`<button class="player" data-player="${esc(p.model.id)}" aria-current="${s.started&&!m.finishedAt&&p===active(m)}" aria-label="Inspect ${esc(p.model.name)}, ${money(p.cash)} cash, ${owned(m,p).length} properties">${mark(p)}<span><strong>${esc(p.model.name)}</strong><small>${p.bankrupt?'Out':money(p.cash)+' · '+owned(m,p).length+' streets'}</small></span></button>`).join('');
 const latest=m.events.findLast(e=>e.action.type!=='end');const text=latest?`${latest.name}: ${latest.outcome}`:'You start with $1,200. Rent comes from visitors, not from owning a street alone.';if(text!==lastAnnouncement){$('outcome').textContent=text;lastAnnouncement=text;}
 const after=id=>{const player=m.players.find(p=>p.model.id===id);return player?' · '+player.model.name+' now '+money(player.cash):'';};const who=id=>id==='bank'?'Bank':m.players.find(p=>p.model.id===id)?.model.name||id;$('payments').innerHTML=(latest?.transfers||[]).map(t=>`<span class="payment ${t.from==='human/you'?'out':''}">${esc(who(t.from))} → ${esc(who(t.to))} ${money(t.amount)}${esc(after(t.from))}${esc(after(t.to))}</span>`).join('');
 $('api-spend').hidden=s.mode!=='real';$('api-spend').textContent=`API spending ${usd(s.usage.cost)} / $${s.budget.toFixed(2)} · ${s.usage.requests}/80 requests${s.usage.reserved?' · '+usd(s.usage.reserved)+' reserved':''}${s.usage.uncertain?' · billing unresolved':''}`;
 $('pause-game').hidden=!s.started||!!m.finishedAt;$('pause-game').textContent=s.paused?'Resume':'Pause';$('board-hint').textContent=s.started?(s.mode==='real'?'Game dollars are fictional. API charges are separate.':'Demo opponents use written strategies. No API charges.'):'Roll. Buy or pass. Collect rent.';
 $('game-error').textContent=s.message&&s.started&&s.paused&&!m.finishedAt?s.message:'';
 let title,help,buttons;
 if(!s.started){title='Your seat is ready';help='Try a free game with Claude and Gemini, or bring your key to play real models.';buttons='<button data-command="demo" class="primary">Play free demo</button><button data-command="real">Play real AI</button>';}
 else if(s.paused&&!m.finishedAt){title='Your game is paused';help=s.mode==='real'&&!s.connected?'Reconnect your key to continue from this turn.':'Resume when you are ready. No new requests run while paused.';buttons=s.mode==='real'&&!s.connected?'<button data-command="real" class="primary">Reconnect OpenRouter</button>':'<button data-command="resume" class="primary">Resume game</button>';}
 else if(!p.model.human){title=s.busy&&s.mode==='real'?p.model.name+' is choosing…':p.model.name+'’s turn';help=s.mode==='real'?`${p.model.label} · ${stage==='roll'?'rolling locally':s.busy?'waiting for one decision':'next decision'}`:'Watch their dice and payments. Then it is your turn again.';buttons='<button data-command="pause">Pause game</button>';}
 else if(stage==='roll'){title=p.jail?'Timeout turn':'Roll to find your next street';help=you.turns===0?'First, roll the dice. The square you reach sets your next choice.':'You have '+money(you.cash)+' cash available.';buttons='<button class="primary" data-move="roll">'+(p.jail?'Take timeout turn':'Roll dice')+'</button>';}
 else if(stage==='purchase'){const square=spaces[p.position];title='Buy '+square.name+'?';help=`Price ${money(square.price)} · rent ${money(square.rent)} per visitor. Buying leaves ${money(p.cash-square.price)} cash. Keeping cash leaves ${money(p.cash)}. Wealth stays ${money(netWorth(m,p))}.`;buttons=`<button class="primary" data-move="buy" data-space="${p.position}">Buy for ${money(square.price)}</button><button data-move="pass">Keep your cash</button>`;}
 else if(stage==='build'){const builds=quickActions(m).filter(a=>a.type==='build');title='Your color pair unlocks houses';help=`Building leaves ${money(p.cash-100)} cash; passing leaves ${money(p.cash)}. One house this turn. Rent still needs visitors.`;buttons=`<label class="sr-only" for="build-street">Street to build on</label><select id="build-street">${builds.map(a=>`<option value="${a.space}">${esc(spaces[a.space].name)} · rent ${money(rent(m,a.space))} → ${money(rent(m,a.space)*3)}</option>`).join('')}</select><button class="primary" data-move="build">Build for $100</button><button data-move="pass">Keep your cash</button>`;}
 else{title='Game complete';help='See the results.';buttons='';}
 $('next-title').textContent=title;$('next-help').textContent=help;$('move-buttons').innerHTML=buttons;if(focusWasMove)$('move-buttons').querySelector('button')?.focus({preventScroll:true});
 document.body.classList.toggle('body-end',!!m.finishedAt);$('end-panel').hidden=!m.finishedAt;if(m.finishedAt)renderEnd(m);
 if(!$('details-panel').hidden)renderDetails();if(!$('setup-panel').hidden)renderConnection();
}
function renderEnd(m){const r=result(m),winners=r.rows.filter(p=>r.winners.includes(p.id));$('end-title').textContent=winners.some(p=>p.id==='human/you')?(winners.length>1?'You share the win!':'You won!'):winners.map(p=>p.name).join(' + ')+(winners.length>1?' win':' wins');$('end-scores').innerHTML='<div class="end-scores">'+r.rows.map(p=>`<p><span>${esc(p.name)}</span><strong>${money(p.netWorth)} wealth</strong></p>`).join('')+'</div>';const decisions=m.events.filter(e=>['buy','build','pass'].includes(e.action.type));const human=decisions.find(e=>e.player==='human/you'),opponent=decisions.findLast(e=>e.player!=='human/you');const selected=[human,opponent].filter(Boolean);if(selected.length<2){const extra=m.events.filter(e=>e.action.type==='roll'&&e.transfers.length).find(e=>!selected.includes(e));if(extra)selected.push(extra);} $('end-decisions').innerHTML=selected.length?selected.slice(0,2).map(e=>`<p><strong>${esc(e.name)}</strong> ${esc(e.outcome)}<br>${esc(e.lesson?.text||e.reason)}</p>`).join(''):'<p>No purchase or building decision was available in this game.</p>';}
function renderConnection(){const connected=credentials.connected();$('key-status').textContent=callbackBusy?'Completing OpenRouter connection…':connectBusy?'Validating key…':connected?'OpenRouter connected for this tab':'OpenRouter not connected';$('key-status').className=connected?'connected':'';$('disconnect').hidden=!connected;$('validate-key').disabled=connectBusy||callbackBusy;$('oauth-connect').disabled=connectBusy||callbackBusy;$('start-match').disabled=state?.busy||connectBusy||callbackBusy||picked.size===0||(setupMode==='real'&&(!connected||catalogStatus!=='ready'||[...picked].some(f=>!chosenModel(f))));}
function chosenModel(family){return catalog.find(m=>m.id===modelChoice.get(family)&&m.brand===family)||catalog.find(m=>m.brand===family);}
function renderOptions(){const focus=document.activeElement,focusFamily=focus?.dataset.family,focusModel=focus?.dataset.modelFamily;const real=setupMode==='real';$('opponent-options').innerHTML=families.map(f=>{const options=catalog.filter(m=>m.brand===f),chosen=chosenModel(f);if(chosen)modelChoice.set(f,chosen.id);const missing=real&&!options.length;return `<div class="opponent-row"><label><input type="checkbox" data-family="${f}" ${picked.has(f)?'checked':''} ${missing&&!picked.has(f)?'disabled':''}><img src="${asset(f)}" alt="" width="28" height="28"><strong>${f==='OpenAI'&&!real?'Codex':f}</strong></label><div>${real?options.length?`<label class="sr-only" for="model-${f}">${f} model</label><select id="model-${f}" data-model-family="${f}">${options.map(m=>`<option value="${esc(m.id)}" ${m.id===chosen?.id?'selected':''}>${esc(m.label)}</option>`).join('')}</select><small>${esc(chosen?.id)} · $${(chosen?.promptPrice*1e6).toFixed(2)} input / $${(chosen?.completionPrice*1e6).toFixed(2)} output per million tokens</small>`:`<small>${catalogStatus==='loading'?'Loading supported models…':'No eligible model available. Reload the catalog or choose another opponent.'}</small>`:`<small>${esc(playerProfiles[demoFor(f).name].role)} · ${esc(beginnerPlan(demoFor(f).name))}</small>`}</div></div>`;}).join('');$('opponent-summary').textContent=`You + ${[...picked].join(', ')||'choose at least one opponent'} · 10 turns each`;renderConnection();if(focusFamily)$('opponent-options').querySelector(`[data-family="${focusFamily}"]`)?.focus({preventScroll:true});if(focusModel)$('opponent-options').querySelector(`[data-model-family="${focusModel}"]`)?.focus({preventScroll:true});}
async function fetchModels(){catalogStatus='loading';renderOptions();try{catalog=await loadCatalog();catalogStatus='ready';$('setup-error').textContent='';}catch{catalogStatus='error';$('setup-error').textContent='Model loading failed. Reload the models or play the free demo.';}renderOptions();}
function setMode(mode){setupMode=mode;document.querySelectorAll('[name=source]').forEach(el=>el.checked=el.value===mode);$('connection-panel').hidden=mode!=='real';$('budget-controls').hidden=mode!=='real';$('reload-catalog').hidden=mode!=='real';$('start-match').textContent=mode==='real'?'Start real AI game':'Start free game';$('setup-description').textContent=mode==='real'?'Choose one to five models. Your key pays for these opponents. No paid requests run until you start.':'You play first. Ten turns each. Demo opponents use written strategies.';renderOptions();if(mode==='real'&&catalogStatus==='idle')fetchModels();}
function openSetup(mode=state.mode){setupWasRunning=state.started&&!state.paused;runner.pause();$('setup-panel').hidden=false;$('details-panel').hidden=true;detailsInert(false);$('end-panel').hidden=true;document.body.classList.add('body-setup');document.body.classList.remove('body-end');$('setup-error').textContent='';setMode(mode);$('setup-title').setAttribute('tabindex','-1');$('setup-title').focus();}
function closeSetup(resume=true){$('setup-panel').hidden=true;document.body.classList.remove('body-setup');if(resume&&setupWasRunning&&!state.match.finishedAt){try{runner.resume();}catch{}}else render(runner.snapshot());$('open-setup').focus();}
function openDetails(){detailsWasRunning=state.started&&!state.paused;runner.pause();$('details-panel').hidden=false;detailsInert(true);$('toggle-details').setAttribute('aria-expanded','true');renderDetails();$('close-details').focus();}
function closeDetails(){ $('details-panel').hidden=true;detailsInert(false);$('toggle-details').setAttribute('aria-expanded','false');if(detailsWasRunning){try{runner.resume();}catch(e){$('game-error').textContent=e.message;}}$('toggle-details').focus();}
function renderDetails(){const m=state.match;document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tab===detailTab)));let html;
 if(detailTab==='players'){html=m.players.map(p=>{const f=finances(m,p),profile=playerProfiles[p.model.name];return `<article class="detail-player" id="detail-${esc(p.model.id.replace(/[^a-z0-9]/gi,'-'))}"><h3>${esc(p.model.name)}</h3><p>${state.mode==='real'&&!p.model.human?esc(p.model.label)+'<br>'+esc(p.model.id):p.model.human?'You choose each decision.':esc(profile?.role||'Demo opponent')}</p>${state.mode==='demo'&&profile?`<p>${esc(beginnerPlan(p.model.name))}</p><p>Tradeoff: ${esc(profile.risk)}</p>`:''}<dl><dt>Cash</dt><dd>${money(p.cash)}</dd><dt>Money received</dt><dd>${money(f.income)}</dd><dt>Money spent</dt><dd>${money(f.out)}</dd><dt>Property value</dt><dd>${money(f.assets)}</dd><dt>Total wealth</dt><dd>${money(netWorth(m,p))}</dd></dl><p class="small">${money(f.opening)} starting cash + ${money(f.income)} received − ${money(f.out)} spent = ${money(p.cash)} cash.</p><details><summary>Recent payments</summary>${f.rows.slice(-8).reverse().map(t=>`<p class="small">${esc(m.players.find(p=>p.model.id===t.from)?.model.name||'Bank')} → ${esc(m.players.find(p=>p.model.id===t.to)?.model.name||'Bank')} ${money(t.amount)} · ${esc(t.category)}</p>`).join('')||'<p>No payments yet.</p>'}</details></article>`;}).join('');}
 else if(detailTab==='squares'){const selected=selectedSquare===null?null:spaces[selectedSquare],lot=selectedSquare===null?null:m.properties[selectedSquare];html=selected?`<section class="street-info"><h3>${esc(selected.kind==='chance'?'News':selected.name)}</h3>${selected.price?`<p>Price ${money(selected.price)} · current rent ${money(rent(m,selectedSquare))}</p><p>${lot.owner?'Owner: '+esc(m.players.find(p=>p.model.id===lot.owner)?.model.name):'Available when you land here.'}</p><p>About ${Math.ceil((selected.price+lot.houses*100)/rent(m,selectedSquare))} paying visits cover the property and house cost. Visits are not guaranteed.</p>`:`<p>${{start:'Passing Start pays $200 from the bank.',chance:'Draw a sourced story. Its cash effect is fictional and applies to whoever draws it.',tax:'Pay $80 compute tax.',jail:'Just visiting. A player sent here skips one turn.',timeout:'Move to timeout and skip the next turn.',parking:'Nothing to pay here.'}[selected.kind]}</p>`}<button data-clear-square>All streets</button></section>`:spaces.map((s,i)=>`<button class="street-row" data-square="${i}"><strong>${esc(s.kind==='chance'?'News':s.name)}</strong><small>${s.price?money(s.price)+' price · '+money(rent(m,i))+' rent':esc(s.kind)}</small></button>`).join('');}
 else if(detailTab==='news'){html='<p class="small">Curated snapshot checked October 8, 2026. Facts are sourced; cash effects are fictional. Any player can draw any card.</p>'+(m.newsDeck||newsCards).map(c=>`<article class="news-item"><time>${esc(c.date)} · ${esc(c.publisher)}</time><h3>${esc(c.title)}</h3><p>${esc(c.fact)}</p><p>${esc(c.lesson)}</p><p>Fictional effect: ${c.amount>0?'+':'−'}${money(Math.abs(c.amount))}</p><a href="${esc(c.url)}" target="_blank" rel="noopener">Read the source</a></article>`).join('');}
 else html='<ol class="rules-list"><li>Start with $1,200. Play ten turns each. Highest cash plus property and house value wins.</li><li>Roll to move. Buy the street you reach or keep your cash. Rent, tax and news payments resolve automatically.</li><li>A color pair doubles rent. It unlocks one $100 house per street, with one optional building decision per turn.</li><li>Passing Start pays $200. Timeout skips one turn.</li><li>If cash runs short, the bank sells properties at half value. Unpaid debt means you are out.</li><li>Scores describe this game, not general AI ability. Brand logos identify players, without endorsement.</li></ol><p class="small"><a href="privacy.html">Privacy, API keys and game conditions</a></p><p class="small">The earlier saved demo and shared operator arena retain their original twenty-turn rules. <a href="play.html">Original tabletop prototype</a> · <a href="case-study.html">Project study</a></p>';
 $('detail-content').innerHTML=html;if(detailTab==='players'&&selectedPlayer){const id='detail-'+selectedPlayer.replace(/[^a-z0-9]/gi,'-');$(id)?.scrollIntoView({block:'nearest'});}}
$('move-buttons').onclick=e=>{const button=e.target.closest('button');if(!button)return;try{if(button.dataset.command==='demo'){runner.start(demoRoster.slice(0,2));return;}if(button.dataset.command==='real'){openSetup('real');return;}if(button.dataset.command==='resume'){runner.resume();return;}if(button.dataset.command==='pause'){runner.pause();return;}if(button.dataset.move){const action={type:button.dataset.move};if(action.type==='buy')action.space=Number(button.dataset.space);if(action.type==='build')action.space=Number($('build-street').value);runner.move(action);}}catch(err){$('game-error').textContent=err.message;}};
$('open-setup').onclick=()=>openSetup();$('close-setup').onclick=()=>closeSetup();document.querySelectorAll('[name=source]').forEach(el=>el.onchange=()=>setMode(el.value));$('reload-catalog').onclick=fetchModels;
$('opponent-options').onchange=e=>{if(e.target.dataset.family){if(e.target.checked)picked.add(e.target.dataset.family);else picked.delete(e.target.dataset.family);}if(e.target.dataset.modelFamily)modelChoice.set(e.target.dataset.modelFamily,e.target.value);renderOptions();};
$('start-match').onclick=()=>{try{const opponents=families.filter(f=>picked.has(f)).map(f=>setupMode==='real'?chosenModel(f):demoFor(f));if(opponents.some(m=>!m))throw Error('Choose available models.');runner.start(opponents,setupMode,Number($('match-budget').value));closeSetup(false);$('move-buttons').querySelector('button')?.focus();}catch(e){$('setup-error').textContent=e.message;}};
$('key-form').onsubmit=async e=>{e.preventDefault();const candidate=$('api-key').value;$('api-key').value='';connectBusy=true;$('setup-error').textContent='';renderConnection();try{await credentials.connect(candidate);}catch(error){$('setup-error').textContent=error.message;}finally{connectBusy=false;renderConnection();}};
$('oauth-connect').onclick=async()=>{try{const url=await credentials.begin(location.origin+location.pathname);location.assign(url);}catch{$('setup-error').textContent='OpenRouter connection could not start. Try the paste-key option.';}};
$('disconnect').onclick=()=>{credentials.disconnect();$('api-key').value='';renderConnection();};credentials.onChange(()=>renderConnection());
$('pause-game').onclick=()=>{try{if(state.paused)runner.resume();else runner.pause();}catch(e){$('game-error').textContent=e.message;}};
$('angled').onclick=()=>setView('angled');$('top').onclick=()=>setView('top');$('toggle-details').onclick=()=>{$('details-panel').hidden?openDetails():closeDetails();};$('close-details').onclick=closeDetails;
$('roster').onclick=e=>{const b=e.target.closest('[data-player]');if(b){selectedPlayer=b.dataset.player;detailTab='players';openDetails();}};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{detailTab=b.dataset.tab;renderDetails();});$('detail-content').onclick=e=>{const b=e.target.closest('[data-square]');if(b){selectedSquare=Number(b.dataset.square);board.setSelected(selectedSquare);renderDetails();}if(e.target.closest('[data-clear-square]')){selectedSquare=null;board.setSelected(null);renderDetails();}};
$('rematch').onclick=()=>{try{runner.start(state.match.players.filter(p=>!p.model.human).map(p=>p.model),state.mode,state.budget);}catch(e){openSetup(state.mode);$('setup-error').textContent=e.message;}};$('change-opponents').onclick=()=>openSetup(state.mode);
$('export-game').onclick=()=>{const url=URL.createObjectURL(new Blob([runner.export()],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='terms-apply-private-game.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
addEventListener('keydown',e=>{if(e.key==='Tab'&&!$('details-panel').hidden){const focusable=[...$('details-panel').querySelectorAll('button,a,summary,input,select')].filter(el=>!el.disabled&&el.getClientRects().length);const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}if(e.key==='Escape'){if(!$('details-panel').hidden)closeDetails();else if(!$('setup-panel').hidden)closeSetup();}});
const phone=matchMedia('(max-width:760px)');phone.addEventListener('change',e=>setView(e.matches?'top':'angled'));
runner.subscribe(render);
// Remove callback credentials from the address bar before making any network request.
const callbackURL=location.href;if(new URL(callbackURL).searchParams.has('code')||new URL(callbackURL).searchParams.has('error')){history.replaceState(null,'',cleanCallbackURL(callbackURL));openSetup('real');callbackBusy=true;renderConnection();credentials.finish(callbackURL).catch(e=>$('setup-error').textContent=e.message).finally(()=>{callbackBusy=false;renderConnection();});}
