export async function catalog(fetcher=fetch){const res=await fetcher('https://openrouter.ai/api/v1/models',{signal:AbortSignal.timeout(20000)});if(!res.ok)throw Error('OpenRouter model catalog is unavailable.');const body=await res.json();return body.data.filter(m=>m.architecture?.output_modalities?.includes('text')&&!m.id.includes(':')&&Number.isFinite(Number(m.pricing?.prompt))&&Number.isFinite(Number(m.pricing?.completion))).map(m=>({id:m.id,name:m.name,family:m.id.split('/')[0],promptPrice:Number(m.pricing.prompt),completionPrice:Number(m.pricing.completion),context:m.context_length}));}
export function parseReply(text){const clean=String(text).trim().replace(/^```(?:json)?\s*/,'').replace(/\s*```$/,'');let body;try{body=JSON.parse(clean);}catch{throw Error('The model did not return a JSON move. Match paused; no bot move was substituted.');}if(!body.action||typeof body.action.type!=='string')throw Error('The model response has no action. Match paused.');return {action:body.action,reason:typeof body.reason==='string'?body.reason.slice(0,500):'No move explanation supplied.'};}
export async function modelMove(model,observation,key,fetcher=fetch){
 const res=await fetcher('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json','X-OpenRouter-Title':'Terms Apply'},signal:AbortSignal.timeout(60000),body:JSON.stringify({model:model.id,provider:{allow_fallbacks:false},messages:[{role:'system',content:'You are a player in Terms Apply, an original board game. Select exactly one action from legalActions. Inspect sources before judging. Never invent an action. Return only JSON with action (copied exactly from the list) and reason (a short public explanation of the move, not private reasoning). Do not use markdown.'},{role:'user',content:JSON.stringify(observation)}],max_tokens:500,temperature:0.3,stream:false})});
 const body=await res.json().catch(()=>({}));if(!res.ok||body.error)throw Error(`OpenRouter request failed (${res.status}). Check credentials, credit balance, rate limits and model availability. Match paused.`);
 const text=body.choices?.[0]?.message?.content;if(!text)throw Error('The model returned no move text. Match paused.');
 // Return usage even if parsing fails, so a billed malformed completion still enters the budget ledger.
 return {text,usage:body.usage||{},reportedModel:body.model||model.id};
}
