import {createHash} from 'node:crypto';
import './build-client.mjs';
import {mkdir,copyFile,readFile,writeFile,rm} from 'node:fs/promises';
import {dirname,resolve} from 'node:path';
const output=resolve('_site');await rm(output,{recursive:true,force:true});
const files=['index.html','play.html','app.mjs','style.css','content.mjs','engine.mjs','case-study.html','print.html','rules.md','arena/client.mjs','arena/client.bundle.js','arena/arena.css','arena/game.mjs','arena/provider.mjs','arena/browser-demo.mjs','assets/board.svg','assets/brands/claude.png','assets/brands/gemini.png','assets/brands/openai.svg','assets/brands/grok.svg','assets/brands/deepseek.ico','output/pdf/terms-apply-kit.pdf'];
for(const file of files){await mkdir(dirname(resolve(output,file)),{recursive:true});await copyFile(file,resolve(output,file));}
let html=await readFile(resolve(output,'index.html'),'utf8');
html=html.replace('<title>Terms Apply | Own the board</title>','<title>Terms Apply | Free browser demo</title><meta name="arena-runtime" content="browser-demo">').replace('href="/"','href="./"').replace('Terms Apply / continuous game arena','Terms Apply / browser demo').replace('Watch each player decide what comes next.','Watch local bots decide what comes next.<br>This free demo runs while your page is open.').replace('The server continues when you close the page.','This demo runs in your browser and stops when the page closes. The full server is available in the repository.').replace('Full transcript retained in server','Full transcript retained in browser').replace('Local prototype · fictional scenarios','Browser demo · no real-model calls').replace('Visual direction informed by','<a href="https://github.com/Parthawe/terms-apply">Source &amp; full server setup ↗</a><br>Visual direction informed by');
html=html.replace('Every finished table keeps its result and full move transcript on the server.','Finished tables and their transcripts are saved in this browser.').replace('Daily request and dollar limits stop new requests; missing cost data pauses the runner. An always-on host is required for a public 24/7 arena.','The full server has daily request and dollar limits. This browser demo makes no model calls. An always-on backend and an API key are still required for a public 24/7 real-model arena.');
for(const file of ['arena/client.bundle.js','arena/arena.css']){const bytes=await readFile(resolve(output,file));const hashed=file.replace(/(\.[^.]+)$/,'-'+createHash('sha256').update(bytes).digest('hex').slice(0,10)+'$1');await writeFile(resolve(output,hashed),bytes);html=html.replace(file,hashed);}
await writeFile(resolve(output,'index.html'),html);await writeFile(resolve(output,'.nojekyll'),'');console.log('Built a public browser demo. No server secrets or runtime data included.');
